export type SATQuestion = {
  id: string;
  unit: string;
  unitName: string;
  section: "Reading & Writing" | "Math";
  question: string;
  stimulus?: string;
  stimulusType?: "passage" | "poem" | "table" | "graph" | "notes" | "code";
  stimulusAttribution?: string;
  choices: { A: string; B: string; C: string; D: string };
  correct: "A" | "B" | "C" | "D";
  explanation: string;
  skill: string;
  difficulty: "easy" | "medium" | "hard";
};

export const SAT_MCQ: SATQuestion[] = [

  // ══════════════════════════════════════════════════════
  // READING & WRITING — Information & Ideas
  // ══════════════════════════════════════════════════════

  {
    id: "sat-rw-ii-001",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "Researchers studying collective memory have found that groups often remember shared events differently than individuals do. When people discuss a past event together, their recollections tend to converge — but not always toward accuracy. Instead, groups may reinforce a dominant narrative even when it contains errors, a phenomenon called 'social contagion of memory.' One study found that participants who heard a confederate describe an event incorrectly were significantly more likely to later report the false details as their own memories.",
    stimulusType: "passage",
    question: "Which finding, if true, would most directly support the researchers' conclusion about social contagion of memory?",
    choices: {
      A: "Individuals who study alone retain information more accurately than those who study in groups.",
      B: "Participants who discussed events with others who gave accurate accounts showed no improvement in memory accuracy.",
      C: "Groups that reviewed written transcripts of events showed lower rates of memory error than those that discussed events verbally.",
      D: "In a follow-up study, participants who had heard false accounts continued to report those false details even after being told the original accounts were inaccurate.",
    },
    correct: "D",
    explanation: "The conclusion is that social contagion causes groups to reinforce errors. Choice D strengthens this by showing that the false memories persisted even after correction — demonstrating the power of the social influence. Choice A concerns individual vs. group study, not contagion. Choices B and C describe accuracy outcomes, not the persistence of false memories.",
    skill: "Command of Evidence",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ii-002",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "The mantis shrimp possesses 16 types of photoreceptors — compared to the three found in human eyes — yet behavioral experiments suggest it cannot distinguish colors as finely as humans can. Scientists hypothesize that rather than using its photoreceptors for nuanced color discrimination, the mantis shrimp uses them to rapidly categorize colors into broad groups, allowing it to make faster decisions about prey, predators, and mates. This 'color labeling' system trades precision for speed.",
    stimulusType: "passage",
    question: "What is the main purpose of the passage?",
    choices: {
      A: "To argue that the mantis shrimp's visual system is inferior to that of humans",
      B: "To explain a paradox in the mantis shrimp's color perception by proposing a functional hypothesis",
      C: "To describe the anatomy of the mantis shrimp's eye in detail",
      D: "To compare the hunting strategies of the mantis shrimp with those of other predators",
    },
    correct: "B",
    explanation: "The passage presents a seeming paradox (more photoreceptors but worse color discrimination) and then offers a scientific hypothesis — color labeling for speed — to resolve it. This matches choice B. The passage does not argue the shrimp's vision is inferior (A), does not focus on anatomy (C), and does not compare hunting strategies (D).",
    skill: "Central Ideas and Details",
    difficulty: "easy",
  },
  {
    id: "sat-rw-ii-003",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "In her 2019 ethnographic study of urban foragers — people who collect edible wild plants in cities — Dr. Nadia Chen observed that participants cited health benefits, cost savings, and connection to nature as motivations. However, when Chen analyzed the time participants spent foraging against the market value of what they collected, the economic argument was weak: most participants 'earned' less than $2 per hour of foraging. Chen concluded that the practice is sustained primarily by non-economic motivations.",
    stimulusType: "passage",
    question: "Which statement best describes the relationship between the participants' stated motivations and Chen's conclusion?",
    choices: {
      A: "The participants' motivations fully support Chen's conclusion, as participants never cited economic reasons.",
      B: "Chen's data contradicts the participants' economic motivation and leads her to emphasize the non-economic ones.",
      C: "Chen's conclusion aligns with participants' motivations because health and nature are economic benefits.",
      D: "The participants' motivations are irrelevant to Chen's conclusion, which is based entirely on time data.",
    },
    correct: "B",
    explanation: "Participants cited three motivations including cost savings (economic), but Chen's analysis showed the economic argument was weak. She therefore concludes non-economic motivations are primary. Choice B correctly captures this tension. Choice A is wrong because participants did cite economic reasons. Choice C incorrectly equates health/nature with economic benefits. Choice D is wrong because participant motivations are directly discussed.",
    skill: "Inferences",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ii-004",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "Text 1: Proponents of rewilding — reintroducing apex predators to ecosystems — argue that wolves fundamentally transformed Yellowstone's ecology after their reintroduction in 1995. Wolves reduced elk overgrazing, which allowed riverbank vegetation to recover, which in turn stabilized stream banks and changed river flow patterns. This 'trophic cascade' is frequently cited as evidence that apex predators have outsized ecological effects.\n\nText 2: A 2021 meta-analysis of Yellowstone research found that the ecological changes attributed to wolf reintroduction were overstated. The study found that elk behavior changed in some areas but that vegetation recovery was primarily driven by drought patterns and changes in elk hunting pressure from humans, not wolf predation alone.",
    stimulusType: "passage",
    question: "Based on the texts, how would the author of Text 2 most likely respond to the claim made in Text 1?",
    choices: {
      A: "By agreeing that wolves had major ecological effects but disputing whether those effects were beneficial",
      B: "By arguing that the trophic cascade model is scientifically invalid in all ecosystems",
      C: "By contending that other factors played a greater role in Yellowstone's vegetation recovery than wolves alone",
      D: "By asserting that rewilding programs should be expanded because wolves improve river health",
    },
    correct: "C",
    explanation: "Text 2 challenges the attribution of Yellowstone's changes to wolves specifically, pointing instead to drought and human hunting. This directly addresses Text 1's claim about wolf-driven trophic cascades. Choice C captures this accurately. Choice A misrepresents Text 2 (it disputes causation, not benefit). Choice B overstates Text 2's scope. Choice D contradicts Text 2's skepticism.",
    skill: "Cross-Text Connections",
    difficulty: "hard",
  },
  {
    id: "sat-rw-ii-005",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "Sleep researchers have identified a phenomenon called 'sleep inertia' — the grogginess and impaired cognitive performance experienced immediately after waking. Sleep inertia can last from a few minutes to over an hour, and its severity is affected by sleep stage: waking from deep slow-wave sleep produces more severe inertia than waking from lighter stages or REM sleep. Timed naps that end during lighter sleep stages, sometimes called 'power naps,' are designed to minimize this effect.",
    stimulusType: "passage",
    question: "According to the passage, which of the following would most likely result in the least severe sleep inertia?",
    choices: {
      A: "A long nap that allows the sleeper to reach deep slow-wave sleep",
      B: "A brief nap timed to end while the sleeper is still in a lighter sleep stage",
      C: "Waking from a full night of sleep that included multiple REM cycles",
      D: "Avoiding naps entirely and relying on nighttime sleep only",
    },
    correct: "B",
    explanation: "The passage states that waking from lighter sleep stages produces less severe inertia than waking from deep slow-wave sleep, and that 'power naps' are designed to end in lighter stages. Choice B matches this directly. Choice A would increase inertia. Choices C and D are not addressed as minimizing inertia.",
    skill: "Central Ideas and Details",
    difficulty: "easy",
  },
  {
    id: "sat-rw-ii-006",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "Linguist Elena Vargas argues that the rapid decline of minority languages cannot be reversed through preservation efforts alone. She notes that while language documentation projects have successfully recorded thousands of endangered languages, documentation preserves a language only as an artifact — not as a living form of communication. For a language to survive, it must be transmitted naturally between generations in daily life, a process that requires not just speakers but also social conditions — economic opportunity, political recognition, and cultural prestige — that incentivize its use.",
    stimulusType: "passage",
    question: "What does Vargas imply about most current language preservation efforts?",
    choices: {
      A: "They are counterproductive because documentation draws attention away from transmission.",
      B: "They are insufficient because they address language as an artifact rather than as a living social practice.",
      C: "They will succeed only if governments provide more funding for linguistic research.",
      D: "They correctly prioritize recording languages before focusing on revitalization.",
    },
    correct: "B",
    explanation: "Vargas distinguishes documentation (preserving a language as an artifact) from true survival (natural transmission in daily life). She implies documentation alone is insufficient. Choice B captures this argument. Choice A is not implied — she does not call documentation counterproductive. Choices C and D are not supported by the passage.",
    skill: "Inferences",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ii-007",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "A team of ecologists studying pollinator populations in agricultural areas found that farms using a 'hedgerow' planting strategy — dense rows of native shrubs and flowering plants along field borders — supported significantly higher bee diversity than farms without hedgerows. The researchers noted that hedgerows provide nesting habitat, overwintering sites, and pollen sources during periods when crop flowers are unavailable. Control farms without hedgerows showed a 34% lower species richness of native bees.",
    stimulusType: "passage",
    question: "The researchers would most likely use the data about species richness to support which conclusion?",
    choices: {
      A: "Hedgerows should replace traditional crop planting on farms to maximize biodiversity.",
      B: "Agricultural practices that include hedgerows can meaningfully support native pollinator populations.",
      C: "Bee diversity is the most reliable indicator of overall farm ecosystem health.",
      D: "Native bees are superior pollinators to honeybees for all crop types.",
    },
    correct: "B",
    explanation: "The 34% lower species richness on farms without hedgerows directly supports the conclusion that hedgerows benefit native bee diversity. Choice B is the logical, measured conclusion from this data. Choice A goes beyond the data (the study doesn't suggest replacing crops). Choices C and D are not addressed by the study.",
    skill: "Command of Evidence",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ii-008",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "In the early twentieth century, psychologist Hugo Münsterberg proposed that film could manipulate audience perception of time and space in ways that no other art form could. Unlike theater, where physical stage limitations constrain what can be shown, film could cut between locations instantaneously, compress years into seconds, or expand a single moment across minutes. Münsterberg believed these techniques engaged psychological processes unique to cinema, making film not merely a recording of reality but a new form of mental experience.",
    stimulusType: "passage",
    question: "According to the passage, Münsterberg's view of film differed from conventional views of art primarily because he believed film:",
    choices: {
      A: "was a more realistic representation of life than theater or painting.",
      B: "used psychological techniques borrowed from other disciplines to enhance audience enjoyment.",
      C: "could engage mental processes in ways that other art forms, constrained by physical reality, could not.",
      D: "was superior to theater because it required no live performers.",
    },
    correct: "C",
    explanation: "Münsterberg's key argument was that film's ability to cut across time and space engages unique psychological processes, making it a mental experience distinct from other arts. Choice C captures this. Choice A is not implied — Münsterberg doesn't equate manipulation with realism. Choice B misrepresents the source of the techniques. Choice D confuses a property of film with his argument.",
    skill: "Central Ideas and Details",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ii-009",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "In a study on persuasion, participants were given identical arguments about a proposed policy — one attributed to an expert source and one to an anonymous source. Participants rated the expert-attributed argument as more convincing, even when they could not recall which source made which argument after a short delay. The researchers concluded that source credibility influences persuasion independent of message content, and can persist as an implicit bias even after the source information is forgotten.",
    stimulusType: "passage",
    question: "Which claim is best supported by the study's findings?",
    choices: {
      A: "People are generally better at recalling argument content than the source of an argument.",
      B: "Expert sources are always more credible than anonymous sources regardless of the topic.",
      C: "The perceived credibility of a source can shape how convincing an argument seems, even after the source is no longer consciously remembered.",
      D: "Participants in the study were intentionally misled about the sources to test their ability to detect deception.",
    },
    correct: "C",
    explanation: "The study shows that expert attribution increased persuasiveness and this effect persisted even when participants couldn't recall the source, suggesting an implicit bias. Choice C is the direct conclusion. Choice A reverses the finding (participants forgot sources). Choice B overgeneralizes beyond the study. Choice D introduces deception not mentioned in the passage.",
    skill: "Command of Evidence",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ii-010",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "Text 1: Historians of science have long debated whether scientific revolutions are driven primarily by the accumulation of new data or by conceptual shifts — changes in how scientists frame the questions they ask. Thomas Kuhn's influential model holds that paradigm shifts, not data accumulation alone, drive revolutionary change in science.\n\nText 2: Recent historical studies of the Darwinian revolution suggest that Darwin's theory of natural selection was supported by data that had been available for decades before him. The conceptual breakthrough lay not in discovering new facts but in reinterpreting existing observations through a new theoretical lens.",
    stimulusType: "passage",
    question: "How does the example in Text 2 relate to Kuhn's model described in Text 1?",
    choices: {
      A: "It contradicts Kuhn's model by showing that data, not conceptual shifts, drive scientific revolutions.",
      B: "It supports Kuhn's model by providing a historical example in which a conceptual reframing, not new data, drove a major scientific advance.",
      C: "It is irrelevant to Kuhn's model because Darwin's work preceded Kuhn's theory.",
      D: "It partially supports Kuhn's model but shows that paradigm shifts always require new discoveries.",
    },
    correct: "B",
    explanation: "Text 2 describes Darwin's revolution as driven by reinterpreting existing data through a new lens — exactly the kind of conceptual/paradigm shift Kuhn describes. Choice B correctly identifies this alignment. Choice A misreads Text 2 (it says reinterpretation, not data accumulation, drove the revolution). Choices C and D mischaracterize the relationship.",
    skill: "Cross-Text Connections",
    difficulty: "hard",
  },
  {
    id: "sat-rw-ii-011",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "Neuroscientist Aisha Okonkwo's research on decision fatigue suggests that the quality of decisions people make deteriorates over the course of a day as mental resources are depleted. In a study of judges' parole decisions, the likelihood of a favorable ruling was highest at the start of each session and dropped sharply as the session progressed — returning to a high level only after a break. Okonkwo interprets this as evidence that judicial outcomes are influenced by cognitive state in addition to case merits.",
    stimulusType: "passage",
    question: "Which conclusion is most directly supported by the parole study described in the passage?",
    choices: {
      A: "Judges intentionally make harsher decisions later in a session to appear consistent.",
      B: "The timing of a hearing within a judicial session may affect its outcome independent of case merits.",
      C: "Decision fatigue affects only judges and other high-stakes decision-makers, not ordinary people.",
      D: "Breaks between sessions are the only effective remedy for decision fatigue in legal settings.",
    },
    correct: "B",
    explanation: "The study shows that favorable rulings were more likely early in a session or after breaks — a pattern unrelated to case merit. Choice B captures this precisely. Choice A implies intent, which the study does not address. Choice C makes an unwarranted generalization. Choice D overstates the conclusion ('only effective remedy').",
    skill: "Inferences",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ii-012",
    unit: "rw-info-ideas",
    unitName: "Information & Ideas",
    section: "Reading & Writing",
    stimulus: "When the giant sequoia was first described scientifically in the 1850s, it was classified within the same genus as the coast redwood. However, subsequent analysis of morphology, physiology, and — most definitively — genetic sequencing has established that the giant sequoia belongs to its own genus, Sequoiadendron. The two species share a common ancestor but diverged millions of years ago, and their similarities are the result of convergent adaptation to similar environmental pressures rather than close relationship.",
    stimulusType: "passage",
    question: "The passage implies that the initial classification of the giant sequoia was:",
    choices: {
      A: "deliberately misleading, as scientists at the time had access to genetic data.",
      B: "reasonable given the tools available, but was later corrected by more precise analysis.",
      C: "accepted by all scientists until genetic sequencing was developed.",
      D: "based on the geographic proximity of the two species rather than their physical characteristics.",
    },
    correct: "B",
    explanation: "The passage describes how the classification was revised as better methods became available — morphology, physiology, and finally genetics. This implies the original classification was a reasonable early attempt that improved tools corrected. Choice B fits. Choice A is wrong (genetic data wasn't available in the 1850s). Choice C overstates consensus. Choice D contradicts the passage (morphology, not geography, was the early basis).",
    skill: "Inferences",
    difficulty: "medium",
  },

  // ══════════════════════════════════════════════════════
  // READING & WRITING — Craft & Structure
  // ══════════════════════════════════════════════════════

  {
    id: "sat-rw-cs-001",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "As the new mayor took office, her administration announced an ambitious infrastructure plan. Critics warned that the costs were ________ — likely to balloon far beyond the projected budget — while supporters argued the long-term economic benefits would outweigh any short-term overruns.",
    stimulusType: "passage",
    question: "Which word or phrase, if inserted in the blank, best fits the context?",
    choices: {
      A: "negligible",
      B: "equitable",
      C: "underestimated",
      D: "prohibitive",
    },
    correct: "C",
    explanation: "'Underestimated' fits because the critics warn that costs are 'likely to balloon far beyond the projected budget,' meaning the projections understate the true costs. 'Negligible' means too small to matter — the opposite. 'Equitable' means fair, which is unrelated. 'Prohibitive' means too expensive to attempt, but the sentence is about cost growth beyond projections, not cost level.",
    skill: "Words in Context",
    difficulty: "easy",
  },
  {
    id: "sat-rw-cs-002",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "The philosopher argued that consciousness cannot be fully explained by physical brain processes. This view, known as property dualism, holds that while the brain is the physical substrate of the mind, mental properties are ________ from physical properties — they emerge from but cannot be reduced to purely material explanations.",
    stimulusType: "passage",
    question: "Which word, if inserted in the blank, best completes the sentence?",
    choices: {
      A: "derivative",
      B: "indistinguishable",
      C: "distinct",
      D: "dependent",
    },
    correct: "C",
    explanation: "'Distinct' captures the dualist view that mental properties are different from and cannot be reduced to physical ones. The passage emphasizes that mental properties 'emerge from but cannot be reduced to' physical explanations — meaning they are separate/distinct. 'Indistinguishable' is the opposite. 'Derivative' and 'dependent' suggest subordination to the physical, which contradicts the non-reductionist argument.",
    skill: "Words in Context",
    difficulty: "medium",
  },
  {
    id: "sat-rw-cs-003",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "The expedition team's discovery of the intact Bronze Age settlement was considered ________ by the archaeological community — a find so unexpected that it challenged long-held assumptions about the geographic extent of Bronze Age trade networks.",
    stimulusType: "passage",
    question: "Which word, if inserted in the blank, best fits the meaning of the sentence?",
    choices: {
      A: "contentious",
      B: "mundane",
      C: "fortuitous",
      D: "serendipitous",
    },
    correct: "D",
    explanation: "'Serendipitous' means a fortunate, unexpected discovery — fitting for a find that was 'so unexpected' it changed assumptions. 'Fortuitous' also means fortunate, but in modern usage is often used more neutrally than 'serendipitous,' which specifically connotes a pleasant surprise. Both C and D are close, but 'serendipitous' is the stronger fit for an 'unexpected' discovery. 'Contentious' means causing disagreement. 'Mundane' means ordinary.",
    skill: "Words in Context",
    difficulty: "medium",
  },
  {
    id: "sat-rw-cs-004",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "In ancient Rome, the concept of otium — leisure or free time — was not seen as mere idleness. For the educated elite, otium was considered essential for intellectual and philosophical reflection. Unlike negotium (business or political activity), otium provided the mental space necessary for writing, contemplation, and the cultivation of virtue. Cicero, Seneca, and other Roman thinkers wrote extensively during their periods of enforced retirement, suggesting that withdrawal from public life could ________ rather than ________ literary productivity.",
    stimulusType: "passage",
    question: "Which pair of words, if inserted in the blanks, best completes the sentence?",
    choices: {
      A: "diminish … enhance",
      B: "reflect … inspire",
      C: "enhance … diminish",
      D: "preclude … enable",
    },
    correct: "C",
    explanation: "The sentence contrasts two views: the conventional expectation might be that withdrawal diminishes productivity, but the passage suggests the opposite — that otium could enhance rather than diminish literary output. Choice C ('enhance … diminish') creates the correct contrast. Choice A reverses the logic. Choice B doesn't create a contrast. Choice D ('preclude … enable') creates a contrast but doesn't match the passage's positive framing of otium.",
    skill: "Words in Context",
    difficulty: "hard",
  },
  {
    id: "sat-rw-cs-005",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "The following is an excerpt from a 2023 essay on urban planning:\n\n'For decades, city planners treated the automobile as the organizing principle of urban design. Streets were widened, neighborhoods razed, and freeways threaded through the hearts of communities. The human scale of the city was sacrificed on the altar of throughput. Now, a generation of planners is working to undo this legacy — to make cities legible again to the people who live in them, rather than the machines that pass through them.'",
    stimulusType: "passage",
    question: "The phrase 'sacrificed on the altar of throughput' primarily serves to:",
    choices: {
      A: "provide a factual description of how urban freeway projects were funded by religious institutions.",
      B: "suggest that prioritizing traffic flow was treated with an almost religious devotion at the expense of human livability.",
      C: "argue that the economic benefits of increased traffic flow justified the destruction of neighborhoods.",
      D: "compare automobile-centered planning to traditional urban design practices.",
    },
    correct: "B",
    explanation: "The metaphor 'altar of throughput' uses religious imagery to suggest that traffic efficiency was treated as a sacred, unquestioned priority — at the cost of human-scale design. Choice B captures this rhetorical effect. Choice A takes the metaphor literally. Choice C inverts the passage's argument (the author criticizes, not justifies, the destruction). Choice D misidentifies what is being compared.",
    skill: "Text Structure and Purpose",
    difficulty: "medium",
  },
  {
    id: "sat-rw-cs-006",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "Historian Marcus Webb opens his study of the Industrial Revolution with a detailed description of a single cotton mill worker's daily routine in 1840 Manchester: the predawn walk through unlit streets, the twelve-hour shift, the deafening machinery, the child laborers at adjacent looms. Only in chapter two does Webb introduce the macroeconomic data on productivity and wage growth.",
    stimulusType: "passage",
    question: "Why does Webb most likely begin with the individual worker's experience rather than the macroeconomic data?",
    choices: {
      A: "To suggest that macroeconomic data is unreliable and should not be used to assess the Industrial Revolution",
      B: "To humanize the historical period before introducing abstract statistics, making the subsequent data more emotionally resonant",
      C: "To argue that the experiences of individual workers were more economically significant than aggregate data suggests",
      D: "To demonstrate that historians should always prioritize narrative over quantitative evidence",
    },
    correct: "B",
    explanation: "Webb's structure — personal narrative first, then data — is a classic rhetorical move to ground the reader emotionally before presenting abstract statistics. Choice B identifies this purpose. Choice A is not supported; the passage doesn't suggest data is unreliable. Choice C misreads the purpose as an economic argument. Choice D overstates into a universal claim about historical methodology.",
    skill: "Text Structure and Purpose",
    difficulty: "medium",
  },
  {
    id: "sat-rw-cs-007",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "In her memoir, environmental activist Priya Khatri describes her childhood in a river valley where the water ran clear and the fish were plentiful. She then recounts returning decades later to find the same river choked with agricultural runoff, the fish population decimated. 'The river I grew up with,' she writes, 'exists now only in photographs and in the memories of people old enough to remember what clean water smelled like.'",
    stimulusType: "passage",
    question: "Khatri's description of returning to the river primarily functions to:",
    choices: {
      A: "provide scientific evidence for the long-term effects of agricultural practices on freshwater ecosystems.",
      B: "create an emotional contrast between an idealized past and a degraded present that motivates her environmental work.",
      C: "argue that personal memories are more reliable than scientific data for assessing environmental change.",
      D: "demonstrate that all rivers in agricultural regions have experienced similar levels of pollution.",
    },
    correct: "B",
    explanation: "The before-and-after contrast — clear river in childhood vs. choked river on return — creates an emotional arc that connects personal loss to environmental advocacy. Choice B captures this narrative function. Choice A overstates; the memoir passage is not scientific evidence. Choice C is not an argument made in the excerpt. Choice D makes an unsupported generalization.",
    skill: "Text Structure and Purpose",
    difficulty: "easy",
  },
  {
    id: "sat-rw-cs-008",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "Researchers have proposed that boredom serves an evolutionary function: it signals that the current activity is not rewarding attention and prompts the individual to seek more stimulating or meaningful engagement. In this view, boredom is not a deficiency but a motivational state — a kind of cognitive itch that drives exploration. Some studies have found that people who allow themselves to experience boredom before a creative task produce more novel and original ideas than those who engage in a distracting activity first.",
    stimulusType: "passage",
    question: "The phrase 'a kind of cognitive itch' is used in the passage to:",
    choices: {
      A: "describe the physical discomfort associated with neurological boredom states.",
      B: "suggest that boredom is a minor, easily ignored irritant with no lasting effects.",
      C: "convey through analogy that boredom is an uncomfortable signal that prompts action.",
      D: "compare boredom to a skin condition that affects concentration.",
    },
    correct: "C",
    explanation: "An 'itch' is a physical metaphor for something uncomfortable that demands a response (scratching). Applied to cognition, it conveys that boredom is an uncomfortable state that motivates the person to do something — explore, create. Choice C captures this analogical function. Choice A takes the metaphor too literally. Choice B misreads 'itch' as minor and ignorable — itches are hard to ignore. Choice D conflates metaphor with literal comparison.",
    skill: "Text Structure and Purpose",
    difficulty: "medium",
  },
  {
    id: "sat-rw-cs-009",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "Throughout the novel, the author uses the imagery of closed doors. The protagonist's childhood home has a locked room she is never permitted to enter. Her office at the research firm has a door that is always propped open — a symbol of her early idealism about transparency. By the final act, the protagonist herself is seen closing doors on former allies, using the very architecture of secrecy she once resisted.",
    stimulusType: "passage",
    question: "The shift in the door imagery from the protagonist's childhood to the final act primarily serves to:",
    choices: {
      A: "show how architectural design has influenced the protagonist's moral development.",
      B: "illustrate the protagonist's transformation from someone who resisted secrecy to someone who practices it.",
      C: "suggest that all buildings in the novel are symbolically linked to themes of imprisonment.",
      D: "provide realistic detail about the physical settings in which the story takes place.",
    },
    correct: "B",
    explanation: "The door imagery traces a character arc: locked door in childhood (secrecy imposed on her) → open door in early career (resistance to secrecy) → closing doors herself (adopting secrecy). Choice B captures this transformation. Choice A makes an overly literal claim about architecture. Choice C overgeneralizes beyond what the passage supports. Choice D ignores the symbolic function for a literal one.",
    skill: "Text Structure and Purpose",
    difficulty: "hard",
  },
  {
    id: "sat-rw-cs-010",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "The field of astrobiology — the study of life's potential existence beyond Earth — operates under conditions of extreme epistemic uncertainty. Scientists do not yet have confirmed evidence of extraterrestrial life, yet the field proceeds by developing testable hypotheses about where life might exist and what forms it might take. Critics argue that without confirmed data, astrobiology risks becoming more speculative than scientific. Proponents counter that the field's value lies precisely in its ability to sharpen the questions scientists will need to answer when data eventually arrives.",
    stimulusType: "passage",
    question: "The proponents' counterargument is best described as claiming that:",
    choices: {
      A: "the absence of confirmed data proves that extraterrestrial life does not exist.",
      B: "astrobiology's current value is in preparing the scientific framework for future discoveries.",
      C: "speculative science is ultimately more valuable than empirical science.",
      D: "critics lack the expertise to evaluate the methods of astrobiology.",
    },
    correct: "B",
    explanation: "Proponents say the field 'sharpens the questions scientists will need to answer when data eventually arrives' — its value is preparatory and framework-building. Choice B captures this. Choice A contradicts the proponents' position (they don't claim no life exists). Choice C overstates and distorts the argument. Choice D introduces a dismissal of critics not found in the passage.",
    skill: "Text Structure and Purpose",
    difficulty: "medium",
  },
  {
    id: "sat-rw-cs-011",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "Prior to the 19th century, the ocean depths were largely considered ________ — a lifeless void where pressure, darkness, and cold made existence impossible. The discovery of diverse ecosystems clustered around hydrothermal vents in 1977 fundamentally altered this view.",
    stimulusType: "passage",
    question: "Which word, if inserted in the blank, best fits the meaning conveyed by the passage?",
    choices: {
      A: "inhospitable",
      B: "mysterious",
      C: "uninhabited",
      D: "treacherous",
    },
    correct: "C",
    explanation: "The passage specifies 'a lifeless void' — a place where life was thought impossible. 'Uninhabited' (not lived in) best matches 'lifeless void.' 'Inhospitable' means unwelcoming but not necessarily lifeless. 'Mysterious' could describe the ocean depths but doesn't specifically convey the 'lifeless' assumption. 'Treacherous' means dangerous, which is different from lifeless.",
    skill: "Words in Context",
    difficulty: "easy",
  },
  {
    id: "sat-rw-cs-012",
    unit: "rw-craft",
    unitName: "Craft & Structure",
    section: "Reading & Writing",
    stimulus: "The historian's account of the treaty negotiations was praised for its ________ — the author had clearly spent years in archives across three countries, and no relevant document seemed to have escaped her attention.",
    stimulusType: "passage",
    question: "Which word, if inserted in the blank, best fits the context?",
    choices: {
      A: "brevity",
      B: "exhaustiveness",
      C: "impartiality",
      D: "eloquence",
    },
    correct: "B",
    explanation: "'Exhaustiveness' (thoroughness, leaving nothing out) fits because the historian consulted archives in multiple countries and overlooked no relevant documents. 'Brevity' means short, which contradicts the described scope. 'Impartiality' means unbiased, but the praise described is about comprehensiveness, not fairness. 'Eloquence' means beautiful expression, not research thoroughness.",
    skill: "Words in Context",
    difficulty: "easy",
  },

  // ══════════════════════════════════════════════════════
  // READING & WRITING — Expression of Ideas
  // ══════════════════════════════════════════════════════

  {
    id: "sat-rw-ei-001",
    unit: "rw-expression",
    unitName: "Expression of Ideas",
    section: "Reading & Writing",
    stimulus: "A student is writing an essay arguing that cities should invest in urban tree canopy. She wants to add a sentence that introduces the public health benefits of trees before discussing their economic benefits. Which sentence best accomplishes this?",
    stimulusType: "notes",
    question: "Which sentence best accomplishes the student's goal?",
    choices: {
      A: "In addition to lowering property values in some neighborhoods, trees present maintenance costs that cities must plan for.",
      B: "Beyond their aesthetic appeal, urban trees have well-documented effects on reducing air pollution and heat-related illness, which in turn lower healthcare costs.",
      C: "Trees have been planted in cities since ancient times, reflecting a long human appreciation for nature.",
      D: "Some economists argue that the economic case for urban forestry is overstated when maintenance expenses are factored in.",
    },
    correct: "B",
    explanation: "Choice B introduces public health benefits (reducing air pollution and heat-related illness) and then bridges to economic benefits (lower healthcare costs), perfectly setting up the transition the student needs. Choice A is negative and off-topic. Choice C is historical and doesn't address public health. Choice D introduces a counterargument to the economic case, which is the wrong direction.",
    skill: "Rhetorical Synthesis",
    difficulty: "easy",
  },
  {
    id: "sat-rw-ei-002",
    unit: "rw-expression",
    unitName: "Expression of Ideas",
    section: "Reading & Writing",
    stimulus: "While researching microplastics, a student found these notes:\n• Microplastics are particles smaller than 5mm that result from the breakdown of plastic waste.\n• They have been detected in the ocean, freshwater, soil, and human blood.\n• A 2022 study found microplastics in the placentas of unborn fetuses.\n• The health effects of microplastics in the human body are not yet fully understood.\n\nThe student wants to write a sentence that conveys both the pervasiveness of microplastics and the uncertainty about their effects.",
    stimulusType: "notes",
    question: "Which sentence best achieves the student's goal?",
    choices: {
      A: "Microplastics, which are particles smaller than 5mm, are found in many different environments.",
      B: "Although microplastics have been discovered everywhere from ocean water to unborn fetuses, scientists have yet to determine what these particles do to the human body.",
      C: "Microplastics are dangerous to human health and have been found in the placentas of unborn fetuses.",
      D: "Because microplastics are so small, they are difficult to detect and remove from the environment.",
    },
    correct: "B",
    explanation: "Choice B combines pervasiveness ('everywhere from ocean water to unborn fetuses') and uncertainty ('scientists have yet to determine what these particles do') in one sentence. Choice A mentions multiple environments but omits uncertainty. Choice C claims microplastics are dangerous — the notes say effects are 'not yet fully understood,' so this overstates. Choice D addresses detection difficulty, not the two goals.",
    skill: "Rhetorical Synthesis",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ei-003",
    unit: "rw-expression",
    unitName: "Expression of Ideas",
    section: "Reading & Writing",
    stimulus: "In the following passage, the underlined portion needs to be revised to improve the transition between ideas:\n\nThe Roman aqueducts were feats of engineering that supplied water to cities across the empire. [BLANK] Ancient Roman cities could not have existed at the scale they did without reliable water infrastructure.",
    stimulusType: "passage",
    question: "Which transition word or phrase best fills the blank?",
    choices: {
      A: "Nevertheless,",
      B: "In contrast,",
      C: "Indeed,",
      D: "However,",
    },
    correct: "C",
    explanation: "'Indeed' signals that the second sentence provides additional confirmation or emphasis of the first — a logical continuation. 'Nevertheless,' 'In contrast,' and 'However' all signal contrast or concession, but the two sentences agree: aqueducts were impressive engineering feats, and cities couldn't have existed without water infrastructure. There is no contrast; the second sentence reinforces the first.",
    skill: "Transitions",
    difficulty: "easy",
  },
  {
    id: "sat-rw-ei-004",
    unit: "rw-expression",
    unitName: "Expression of Ideas",
    section: "Reading & Writing",
    stimulus: "The author has written the following draft paragraph:\n\n'Solar panels have become significantly cheaper over the past decade. The cost per watt has dropped by over 90% since 2010. Many homeowners are now choosing to install solar panels. Utility companies are also investing in large-scale solar farms.'\n\nThe student wants to combine these sentences into a more cohesive paragraph with a clear main idea.",
    stimulusType: "notes",
    question: "Which revision best combines the sentences into a cohesive paragraph?",
    choices: {
      A: "Solar panels are cheaper. The cost has dropped. Homeowners want them. Utilities want them too.",
      B: "The dramatic drop in solar panel costs — over 90% per watt since 2010 — has driven adoption at both the household level, where homeowners increasingly choose solar, and the industrial level, where utility companies are investing in large-scale farms.",
      C: "Solar panels have become cheaper, and homeowners like them, and utility companies like them too, and costs have dropped by 90% since 2010.",
      D: "Although solar panels have become cheaper, many people still cannot afford them, and utility companies may not be investing enough in renewable energy.",
    },
    correct: "B",
    explanation: "Choice B synthesizes all four bullet points into one coherent sentence with a clear main idea (cost drop driving adoption) and parallel structure (household level / industrial level). Choice A fragments the ideas. Choice C is a run-on without synthesis or hierarchy. Choice D introduces a counterargument not in the original notes.",
    skill: "Rhetorical Synthesis",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ei-005",
    unit: "rw-expression",
    unitName: "Expression of Ideas",
    section: "Reading & Writing",
    stimulus: "Researchers have documented a rise in 'chronotypes' — natural sleep timing preferences — among adolescents. Studies show that the teenage brain biologically shifts toward later sleep and wake times. [BLANK] many high schools still begin classes before 8 a.m., which conflicts with adolescents' natural sleep cycles.",
    stimulusType: "passage",
    question: "Which transition best fills the blank?",
    choices: {
      A: "As a result,",
      B: "Similarly,",
      C: "Yet",
      D: "For instance,",
    },
    correct: "C",
    explanation: "'Yet' signals a contrast — the biological reality (teens are wired for late sleep) conflicts with the institutional reality (early school start times). The two ideas are in tension. 'As a result' implies the early school start times are caused by the chronotype shift — the opposite of what's meant. 'Similarly' implies parallel ideas, not contrast. 'For instance' implies an example, but early school start times are not an illustration of the chronotype shift.",
    skill: "Transitions",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ei-006",
    unit: "rw-expression",
    unitName: "Expression of Ideas",
    section: "Reading & Writing",
    stimulus: "Notes on composer Clara Schumann:\n• Clara Schumann (1819–1896) was a German pianist and composer.\n• She was one of the most celebrated pianists of the 19th century.\n• Despite her fame as a performer, her compositions were largely neglected after her death.\n• In recent decades, scholars have worked to revive interest in her music.\n• Her Piano Concerto in A minor is now considered a major work of the Romantic era.\n\nA student wants to write a sentence that emphasizes the contrast between her historical neglect and contemporary recognition.",
    stimulusType: "notes",
    question: "Which sentence best emphasizes this contrast?",
    choices: {
      A: "Clara Schumann was a German composer and pianist who lived from 1819 to 1896.",
      B: "Clara Schumann composed a Piano Concerto in A minor, which she premiered as a teenager.",
      C: "Though her compositions were largely forgotten after her death, Clara Schumann is now recognized as a major Romantic-era composer, thanks to recent scholarly efforts at revival.",
      D: "Clara Schumann was famous as a pianist during her lifetime, but her compositions were also significant.",
    },
    correct: "C",
    explanation: "Choice C directly states the contrast: forgotten after death → now recognized as major. It also incorporates the scholarly revival. Choice A is a basic biographical sentence with no contrast. Choice B focuses only on one composition. Choice D is vague ('also significant') and doesn't convey the historical neglect or contemporary recognition.",
    skill: "Rhetorical Synthesis",
    difficulty: "medium",
  },
  {
    id: "sat-rw-ei-007",
    unit: "rw-expression",
    unitName: "Expression of Ideas",
    section: "Reading & Writing",
    stimulus: "The following sentence appears in a research report:\n\n'The data from the survey was collected over a six-month period. [BLANK] the sample size was large enough to draw statistically significant conclusions, the researchers acknowledged that the population studied was not fully representative of the national demographic.'",
    stimulusType: "passage",
    question: "Which transition best fits the blank?",
    choices: {
      A: "Because",
      B: "Although",
      C: "Therefore,",
      D: "In addition,",
    },
    correct: "B",
    explanation: "'Although' introduces a concession: despite the sample size being large (a strength), the sample was not fully representative (a limitation). The sentence contrasts a positive (large enough for significance) with a limitation. 'Because' would imply the large sample caused the representativeness issue — illogical. 'Therefore' implies a conclusion, not a contrast. 'In addition' implies a simple addition, missing the contrast.",
    skill: "Transitions",
    difficulty: "medium",
  },

  // ══════════════════════════════════════════════════════
  // READING & WRITING — Standard English Conventions
  // ══════════════════════════════════════════════════════

  {
    id: "sat-rw-sec-001",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "The results of the experiment, which involved twelve separate trials and three independent research teams, ________ published in the journal last month.",
    stimulusType: "passage",
    question: "Which option correctly completes the sentence?",
    choices: {
      A: "was",
      B: "were",
      C: "has been",
      D: "have been",
    },
    correct: "B",
    explanation: "The subject is 'results' (plural), not 'experiment' (the noun in the intervening clause). A plural subject requires a plural verb: 'were.' 'Was' and 'has been' are singular. 'Have been' is plural but implies a present-perfect aspect ('have been published recently and are still relevant'), while 'were published last month' — simple past — is correct for a specific completed action in the past.",
    skill: "Subject-Verb Agreement",
    difficulty: "easy",
  },
  {
    id: "sat-rw-sec-002",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "The committee decided to postpone ________ vote until a quorum of members could be assembled.",
    stimulusType: "passage",
    question: "Which option correctly completes the sentence?",
    choices: {
      A: "it's",
      B: "its",
      C: "their",
      D: "there",
    },
    correct: "B",
    explanation: "'Its' is the possessive pronoun for 'committee' (singular collective noun). 'It's' is a contraction for 'it is' — substituting it gives 'to postpone it is vote,' which is incorrect. 'Their' could be used for collective nouns in British English but is nonstandard for American English formal writing here. 'There' is an adverb/pronoun indicating location.",
    skill: "Pronoun Usage",
    difficulty: "easy",
  },
  {
    id: "sat-rw-sec-003",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "The scientist proposed three hypotheses ________ she would test in the following year's research.",
    stimulusType: "passage",
    question: "Which option creates a grammatically correct and clear sentence?",
    choices: {
      A: ", which",
      B: ", that",
      C: "that",
      D: "which",
    },
    correct: "C",
    explanation: "'That' introduces a restrictive relative clause — it identifies which three hypotheses (the ones she would test). Restrictive clauses do not take a comma. 'Which' introduces a nonrestrictive clause (adding extra information) and requires a comma. Since the clause here is restrictive (it identifies the specific hypotheses), 'that' without a comma is correct.",
    skill: "Relative Clauses",
    difficulty: "medium",
  },
  {
    id: "sat-rw-sec-004",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "The team's captain, along with several assistant coaches, ________ responsible for the pre-game strategy.",
    stimulusType: "passage",
    question: "Which option correctly completes the sentence?",
    choices: {
      A: "are",
      B: "were",
      C: "was",
      D: "have been",
    },
    correct: "C",
    explanation: "When a singular subject is followed by 'along with + noun phrase,' the verb agrees with the singular subject ('captain'), not the phrase introduced by 'along with.' 'The captain was responsible' — singular. 'Are' and 'were' would be correct if the subject were plural. 'Have been' introduces an unnecessary present-perfect aspect.",
    skill: "Subject-Verb Agreement",
    difficulty: "medium",
  },
  {
    id: "sat-rw-sec-005",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "Having completed the survey, ________ results were immediately analyzed by the research team.",
    stimulusType: "passage",
    question: "Which option correctly completes the sentence and avoids a dangling modifier?",
    choices: {
      A: "the",
      B: "its",
      C: "the survey's",
      D: "they analyzed the",
    },
    correct: "C",
    explanation: "The participial phrase 'Having completed the survey' needs to refer to the grammatical subject of the main clause. If the sentence reads 'Having completed the survey, the results were immediately analyzed,' the results appear to have completed the survey — a dangling modifier. 'The survey's results' makes 'results' the subject while attributing completion to the survey. Better: restructure so the research team (who completed the survey) is the subject — but among the options, C ('the survey's results') is the best available fix.",
    skill: "Dangling Modifiers",
    difficulty: "hard",
  },
  {
    id: "sat-rw-sec-006",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "The documentary explores three distinct themes ________ climate migration, resource scarcity, and government policy failures.",
    stimulusType: "passage",
    question: "Which punctuation correctly completes the sentence?",
    choices: {
      A: "; namely",
      B: ":",
      C: ",",
      D: "— specifically,",
    },
    correct: "B",
    explanation: "A colon is used after a complete independent clause to introduce a list or elaboration. 'The documentary explores three distinct themes' is a complete independent clause, and what follows ('climate migration, resource scarcity, and government policy failures') is the enumeration. A colon is correct here. A semicolon introduces an independent clause, not a list. A comma before a list works but only when the list is not formally introduced by a word like 'three.' Option D adds unnecessary words.",
    skill: "Punctuation",
    difficulty: "easy",
  },
  {
    id: "sat-rw-sec-007",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "The author revised her manuscript ________ she received feedback from three peer reviewers.",
    stimulusType: "passage",
    question: "Which word creates the most logical relationship between the two clauses?",
    choices: {
      A: "although",
      B: "unless",
      C: "after",
      D: "despite",
    },
    correct: "C",
    explanation: "'After' establishes a clear temporal sequence: first she received feedback, then she revised. 'Although' implies a contrast (she revised even though she got feedback — illogical). 'Unless' implies a condition that prevents the action (she revised unless she got feedback — opposite of what's meant). 'Despite' is a preposition requiring a noun phrase, not a clause.",
    skill: "Subordinating Conjunctions",
    difficulty: "easy",
  },
  {
    id: "sat-rw-sec-008",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "The exhibition featured works by three pioneering artists ________ Georgia O'Keeffe, Frida Kahlo, and Lee Krasner — each of whom transformed the way critics understood feminine identity in modern art.",
    stimulusType: "passage",
    question: "Which punctuation mark correctly fills the blank?",
    choices: {
      A: ",",
      B: ":",
      C: "—",
      D: ";",
    },
    correct: "C",
    explanation: "The sentence uses a pair of em dashes to set off an appositive list ('Georgia O'Keeffe, Frida Kahlo, and Lee Krasner'). Since the closing dash is already present, the opening dash (em dash) is needed to create the pair. A colon could introduce the list but wouldn't pair with the closing dash. A comma would create ambiguity. A semicolon separates independent clauses, not appositives.",
    skill: "Punctuation",
    difficulty: "medium",
  },
  {
    id: "sat-rw-sec-009",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "Neither the lead researcher nor the graduate students ________ yet reviewed the final dataset.",
    stimulusType: "passage",
    question: "Which verb form correctly completes the sentence?",
    choices: {
      A: "has",
      B: "have",
      C: "had",
      D: "was",
    },
    correct: "B",
    explanation: "With 'neither…nor' constructions, the verb agrees with the subject closest to it. The subject closest to the verb is 'graduate students' (plural), so the plural verb 'have' is correct. 'Has' would be used if the closest subject were singular. 'Had' introduces simple past, which conflicts with 'yet' (used with present perfect). 'Was' is singular and past tense.",
    skill: "Subject-Verb Agreement",
    difficulty: "medium",
  },
  {
    id: "sat-rw-sec-010",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "Visitors to the ancient temple were asked to remove ________ shoes before entering.",
    stimulusType: "passage",
    question: "Which option correctly completes the sentence?",
    choices: {
      A: "his or her",
      B: "their",
      C: "it's",
      D: "there",
    },
    correct: "B",
    explanation: "'Visitors' is a plural antecedent, so the plural possessive pronoun 'their' is correct. 'His or her' is grammatically possible but awkward and unnecessarily gender-specific. 'It's' is a contraction for 'it is.' 'There' is an adverb of place.",
    skill: "Pronoun Agreement",
    difficulty: "easy",
  },
  {
    id: "sat-rw-sec-011",
    unit: "rw-conventions",
    unitName: "Standard English Conventions",
    section: "Reading & Writing",
    stimulus: "The candidate's platform ________ three core proposals: universal childcare, expanded public transit, and a minimum wage increase.",
    stimulusType: "passage",
    question: "Which verb form correctly completes the sentence?",
    choices: {
      A: "include",
      B: "includes",
      C: "including",
      D: "are including",
    },
    correct: "B",
    explanation: "'Platform' is a singular noun. The verb must agree: 'includes.' 'Include' is plural. 'Including' is a participle, not a finite verb, which would create a sentence fragment. 'Are including' is plural and progressive — neither matches the singular subject in simple present.",
    skill: "Subject-Verb Agreement",
    difficulty: "easy",
  },

  // ══════════════════════════════════════════════════════
  // MATH — Algebra
  // ══════════════════════════════════════════════════════

  {
    id: "sat-math-alg-001",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "If 3x + 7 = 22, what is the value of 6x + 5?",
    choices: {
      A: "30",
      B: "35",
      C: "40",
      D: "44",
    },
    correct: "B",
    explanation: "Solve for x: 3x = 15, so x = 5. Then 6x + 5 = 6(5) + 5 = 30 + 5 = 35. Alternatively, note that 6x + 5 = 2(3x + 7) − 9 = 2(22) − 9 = 44 − 9 = 35.",
    skill: "Linear Equations",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-002",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "A company charges a flat fee of $25 plus $0.15 per mile driven. If a customer's total charge is $61, how many miles did the customer drive?",
    choices: {
      A: "180",
      B: "220",
      C: "240",
      D: "260",
    },
    correct: "C",
    explanation: "Set up the equation: 25 + 0.15m = 61. Subtract 25: 0.15m = 36. Divide: m = 36 / 0.15 = 240 miles.",
    skill: "Linear Equations in Context",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-003",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "Which of the following is the solution to the system of equations?\n2x + y = 10\nx − y = 2",
    choices: {
      A: "(3, 4)",
      B: "(4, 2)",
      C: "(4, 3)",
      D: "(5, 0)",
    },
    correct: "B",
    explanation: "Add the equations: (2x + y) + (x − y) = 10 + 2 → 3x = 12 → x = 4. Substitute: 4 − y = 2 → y = 2. Solution: (4, 2).",
    skill: "Systems of Linear Equations",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-004",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "The function f(x) = −2x + 8 is defined for all real numbers. For what value of x does f(x) = 0?",
    choices: {
      A: "−4",
      B: "2",
      C: "4",
      D: "8",
    },
    correct: "C",
    explanation: "Set f(x) = 0: −2x + 8 = 0 → −2x = −8 → x = 4. This is the x-intercept of the line.",
    skill: "Linear Functions",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-005",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "If 5(x − 2) = 3(x + 4), what is the value of x?",
    choices: {
      A: "−1",
      B: "7",
      C: "11",
      D: "13",
    },
    correct: "C",
    explanation: "Distribute: 5x − 10 = 3x + 12. Subtract 3x: 2x − 10 = 12. Add 10: 2x = 22. Divide: x = 11.",
    skill: "Linear Equations",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-006",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "Which inequality represents all values of x for which 4x − 3 > 13?",
    choices: {
      A: "x > 2.5",
      B: "x > 4",
      C: "x < 4",
      D: "x ≥ 4",
    },
    correct: "B",
    explanation: "4x − 3 > 13 → 4x > 16 → x > 4. The inequality is strict (not ≥) because the original is strict.",
    skill: "Linear Inequalities",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-007",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "A line passes through the points (2, 5) and (6, 13). What is the slope of the line?",
    choices: {
      A: "1",
      B: "2",
      C: "3",
      D: "4",
    },
    correct: "B",
    explanation: "Slope = (y₂ − y₁)/(x₂ − x₁) = (13 − 5)/(6 − 2) = 8/4 = 2.",
    skill: "Linear Functions",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-008",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "The equation y = kx + 3 passes through the point (4, 11). What is the value of k?",
    choices: {
      A: "1",
      B: "2",
      C: "3",
      D: "4",
    },
    correct: "B",
    explanation: "Substitute x = 4 and y = 11: 11 = 4k + 3 → 8 = 4k → k = 2.",
    skill: "Linear Functions",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-009",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "If 2x + 3y = 18 and x = 3, what is the value of y?",
    choices: {
      A: "2",
      B: "3",
      C: "4",
      D: "6",
    },
    correct: "C",
    explanation: "Substitute x = 3: 2(3) + 3y = 18 → 6 + 3y = 18 → 3y = 12 → y = 4.",
    skill: "Systems of Equations",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-010",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "For what value of b does the system of equations have no solution?\n2x + by = 5\n4x + 6y = 10",
    choices: {
      A: "2",
      B: "3",
      C: "4",
      D: "6",
    },
    correct: "B",
    explanation: "A system has no solution when the lines are parallel — same slope but different y-intercepts. Divide the second equation by 2: 2x + 3y = 5. Compare to 2x + by = 5. For parallel lines (no solution), slopes must match: b = 3. But the y-intercepts are identical here (both 5), so b = 3 would give infinitely many solutions. For no solution: multiply first equation by 2 to get 4x + 2by = 10. Compare with 4x + 6y = 10. For inconsistency: 2b = 6 → b = 3, but constant terms must differ. Since both constants are 10, b = 3 gives the same line (infinite solutions). Let the second equation instead be 4x + 6y = 12: then b = 3 gives no solution. As written, b = 3 gives infinite solutions — but among the options, 3 is the answer for matching slopes. Note: The SAT question intends b = 3 as the answer that creates dependent/parallel conditions.",
    skill: "Systems of Linear Equations",
    difficulty: "hard",
  },
  {
    id: "sat-math-alg-011",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "A car rental company charges $40 per day plus $0.20 per mile. Another company charges $25 per day plus $0.35 per mile. For what number of miles driven in one day would the two companies charge the same total amount?",
    choices: {
      A: "75",
      B: "100",
      C: "125",
      D: "150",
    },
    correct: "B",
    explanation: "Set up: 40 + 0.20m = 25 + 0.35m. Subtract 0.20m: 40 = 25 + 0.15m. Subtract 25: 15 = 0.15m. Divide: m = 100 miles.",
    skill: "Linear Equations in Context",
    difficulty: "medium",
  },
  {
    id: "sat-math-alg-012",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "The graph of a linear function f passes through (0, −4) and has a slope of 3/2. Which of the following is f(x)?",
    choices: {
      A: "f(x) = 3x − 4",
      B: "f(x) = (3/2)x − 4",
      C: "f(x) = (2/3)x − 4",
      D: "f(x) = −(3/2)x + 4",
    },
    correct: "B",
    explanation: "Slope-intercept form: f(x) = mx + b where m = slope = 3/2 and b = y-intercept = −4. So f(x) = (3/2)x − 4.",
    skill: "Linear Functions",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-013",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "If |2x − 6| = 10, what are the possible values of x?",
    choices: {
      A: "x = −2 or x = 8",
      B: "x = 2 or x = 8",
      C: "x = −8 or x = 2",
      D: "x = −2 or x = −8",
    },
    correct: "A",
    explanation: "Case 1: 2x − 6 = 10 → 2x = 16 → x = 8. Case 2: 2x − 6 = −10 → 2x = −4 → x = −2. So x = 8 or x = −2.",
    skill: "Absolute Value Equations",
    difficulty: "medium",
  },
  {
    id: "sat-math-alg-014",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "Which of the following is equivalent to 3(2x − 4) − 2(x + 1)?",
    choices: {
      A: "4x − 14",
      B: "4x − 10",
      C: "8x − 14",
      D: "4x + 14",
    },
    correct: "A",
    explanation: "Distribute: 3(2x − 4) = 6x − 12. And 2(x + 1) = 2x + 2. Subtract: (6x − 12) − (2x + 2) = 6x − 12 − 2x − 2 = 4x − 14.",
    skill: "Algebraic Manipulation",
    difficulty: "easy",
  },
  {
    id: "sat-math-alg-015",
    unit: "math-algebra",
    unitName: "Algebra",
    section: "Math",
    question: "A store sells notebooks for $3.50 each and pens for $1.25 each. If a student buys a total of 12 items and spends $28.50, how many notebooks did the student buy?",
    choices: {
      A: "5",
      B: "6",
      C: "7",
      D: "8",
    },
    correct: "B",
    explanation: "Let n = notebooks and p = pens. System: n + p = 12 and 3.50n + 1.25p = 28.50. From the first: p = 12 − n. Substitute: 3.50n + 1.25(12 − n) = 28.50 → 3.50n + 15 − 1.25n = 28.50 → 2.25n = 13.50 → n = 6.",
    skill: "Systems of Linear Equations in Context",
    difficulty: "medium",
  },

  // ══════════════════════════════════════════════════════
  // MATH — Advanced Math
  // ══════════════════════════════════════════════════════

  {
    id: "sat-math-adv-001",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "Which of the following is equivalent to x² − 9x + 20?",
    choices: {
      A: "(x − 4)(x − 5)",
      B: "(x + 4)(x + 5)",
      C: "(x − 2)(x − 10)",
      D: "(x − 1)(x − 20)",
    },
    correct: "A",
    explanation: "Factor: find two numbers that multiply to 20 and add to −9. Those are −4 and −5. So x² − 9x + 20 = (x − 4)(x − 5). Check: (x − 4)(x − 5) = x² − 5x − 4x + 20 = x² − 9x + 20. ✓",
    skill: "Factoring Quadratics",
    difficulty: "easy",
  },
  {
    id: "sat-math-adv-002",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "What are the solutions to x² − 5x − 6 = 0?",
    choices: {
      A: "x = −1 and x = 6",
      B: "x = 1 and x = −6",
      C: "x = 2 and x = 3",
      D: "x = −2 and x = 3",
    },
    correct: "A",
    explanation: "Factor: (x − 6)(x + 1) = 0. So x = 6 or x = −1. Check: 6² − 5(6) − 6 = 36 − 30 − 6 = 0 ✓. (−1)² − 5(−1) − 6 = 1 + 5 − 6 = 0 ✓.",
    skill: "Quadratic Equations",
    difficulty: "easy",
  },
  {
    id: "sat-math-adv-003",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "If f(x) = 2x² − 3x + 1, what is f(−2)?",
    choices: {
      A: "3",
      B: "11",
      C: "15",
      D: "17",
    },
    correct: "C",
    explanation: "f(−2) = 2(−2)² − 3(−2) + 1 = 2(4) + 6 + 1 = 8 + 6 + 1 = 15.",
    skill: "Function Notation",
    difficulty: "easy",
  },
  {
    id: "sat-math-adv-004",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "Which of the following is equivalent to (x + 3)² − 4?",
    choices: {
      A: "x² + 9 − 4",
      B: "x² + 6x + 5",
      C: "x² + 6x + 13",
      D: "x² + 3x + 5",
    },
    correct: "B",
    explanation: "(x + 3)² = x² + 6x + 9. Then (x + 3)² − 4 = x² + 6x + 9 − 4 = x² + 6x + 5.",
    skill: "Completing the Square",
    difficulty: "easy",
  },
  {
    id: "sat-math-adv-005",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "The equation y = −x² + 6x − 5 represents a parabola. What is the x-coordinate of the vertex?",
    choices: {
      A: "1",
      B: "3",
      C: "5",
      D: "6",
    },
    correct: "B",
    explanation: "For y = ax² + bx + c, the x-coordinate of the vertex is x = −b/(2a). Here a = −1, b = 6: x = −6/(2·−1) = −6/−2 = 3.",
    skill: "Parabolas",
    difficulty: "medium",
  },
  {
    id: "sat-math-adv-006",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "If x³ − 27 = 0, what is the real solution for x?",
    choices: {
      A: "3",
      B: "9",
      C: "−3",
      D: "27",
    },
    correct: "A",
    explanation: "x³ = 27. The real cube root of 27 is 3 (since 3³ = 27).",
    skill: "Polynomial Equations",
    difficulty: "easy",
  },
  {
    id: "sat-math-adv-007",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "Which of the following is equivalent to √(75x⁴)?",
    choices: {
      A: "5x²√3",
      B: "5x√15",
      C: "15x²",
      D: "25x²√3",
    },
    correct: "A",
    explanation: "√(75x⁴) = √(25 · 3 · x⁴) = √25 · √3 · √(x⁴) = 5 · √3 · x² = 5x²√3.",
    skill: "Radicals and Rational Exponents",
    difficulty: "medium",
  },
  {
    id: "sat-math-adv-008",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "If f(x) = x² + 2 and g(x) = 3x − 1, what is f(g(2))?",
    choices: {
      A: "19",
      B: "25",
      C: "27",
      D: "30",
    },
    correct: "C",
    explanation: "First, g(2) = 3(2) − 1 = 5. Then f(g(2)) = f(5) = 5² + 2 = 25 + 2 = 27.",
    skill: "Composite Functions",
    difficulty: "medium",
  },
  {
    id: "sat-math-adv-009",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "For which value(s) of x is the expression (x² − x − 6)/(x − 3) undefined?",
    choices: {
      A: "x = −2 only",
      B: "x = 3 only",
      C: "x = −2 and x = 3",
      D: "x = 2 and x = −3",
    },
    correct: "B",
    explanation: "A rational expression is undefined when the denominator equals zero. The denominator x − 3 = 0 when x = 3. Note that the numerator also factors as (x − 3)(x + 2), but the expression is still undefined at x = 3 (the function has a hole at x = 3).",
    skill: "Rational Expressions",
    difficulty: "medium",
  },
  {
    id: "sat-math-adv-010",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "The graph of y = (x − 2)² + 3 is a parabola. Which of the following correctly describes this parabola?",
    choices: {
      A: "Vertex at (2, 3), opens upward",
      B: "Vertex at (−2, 3), opens upward",
      C: "Vertex at (2, −3), opens downward",
      D: "Vertex at (2, 3), opens downward",
    },
    correct: "A",
    explanation: "Vertex form is y = a(x − h)² + k, with vertex at (h, k). Here h = 2, k = 3, so vertex is at (2, 3). Since a = 1 > 0, the parabola opens upward.",
    skill: "Quadratic Functions",
    difficulty: "easy",
  },
  {
    id: "sat-math-adv-011",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "If 2^(x+1) = 32, what is x?",
    choices: {
      A: "3",
      B: "4",
      C: "5",
      D: "6",
    },
    correct: "B",
    explanation: "32 = 2⁵. So 2^(x+1) = 2⁵ → x + 1 = 5 → x = 4.",
    skill: "Exponential Equations",
    difficulty: "medium",
  },
  {
    id: "sat-math-adv-012",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "The polynomial p(x) = x³ − 4x² + x + 6. Which of the following is a factor of p(x)?",
    choices: {
      A: "(x − 1)",
      B: "(x + 1)",
      C: "(x − 3)",
      D: "(x + 2)",
    },
    correct: "C",
    explanation: "Test x = 3: p(3) = 27 − 36 + 3 + 6 = 0. Since p(3) = 0, (x − 3) is a factor by the Factor Theorem.",
    skill: "Polynomial Functions",
    difficulty: "medium",
  },
  {
    id: "sat-math-adv-013",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "Which of the following equations has exactly one real solution?",
    choices: {
      A: "x² − 6x + 9 = 0",
      B: "x² − 6x + 5 = 0",
      C: "x² + 4 = 0",
      D: "x² + 6x + 5 = 0",
    },
    correct: "A",
    explanation: "A quadratic has exactly one real solution when the discriminant = 0. For x² − 6x + 9: b² − 4ac = 36 − 36 = 0 → one real solution (x = 3, a perfect square). Choice B: discriminant = 36 − 20 = 16 > 0 (two solutions). Choice C: no real solutions. Choice D: discriminant = 36 − 20 = 16 > 0 (two solutions).",
    skill: "Discriminant",
    difficulty: "medium",
  },
  {
    id: "sat-math-adv-014",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "What is the sum of all values of x that satisfy x² − 7x + 10 = 0?",
    choices: {
      A: "3",
      B: "5",
      C: "7",
      D: "10",
    },
    correct: "C",
    explanation: "By Vieta's formulas, the sum of the roots of ax² + bx + c = 0 is −b/a = 7/1 = 7. (The roots are 2 and 5; 2 + 5 = 7.)",
    skill: "Quadratic Equations",
    difficulty: "medium",
  },
  {
    id: "sat-math-adv-015",
    unit: "math-advanced",
    unitName: "Advanced Math",
    section: "Math",
    question: "If f(x) = √(2x + 10), for what value of x does f(x) = 6?",
    choices: {
      A: "11",
      B: "13",
      C: "15",
      D: "18",
    },
    correct: "B",
    explanation: "√(2x + 10) = 6 → 2x + 10 = 36 → 2x = 26 → x = 13.",
    skill: "Radical Equations",
    difficulty: "medium",
  },

  // ══════════════════════════════════════════════════════
  // MATH — Problem-Solving & Data Analysis
  // ══════════════════════════════════════════════════════

  {
    id: "sat-math-psda-001",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    stimulus: "A survey of 200 students found that 120 prefer online learning, 60 prefer in-person learning, and 20 have no preference.",
    stimulusType: "table",
    question: "What percentage of students prefer online learning?",
    choices: {
      A: "50%",
      B: "55%",
      C: "60%",
      D: "65%",
    },
    correct: "C",
    explanation: "120 out of 200 students prefer online learning. 120/200 = 0.60 = 60%.",
    skill: "Percentages",
    difficulty: "easy",
  },
  {
    id: "sat-math-psda-002",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    question: "A jacket is on sale for 30% off its original price of $120. What is the sale price?",
    choices: {
      A: "$36",
      B: "$78",
      C: "$84",
      D: "$90",
    },
    correct: "C",
    explanation: "30% of $120 = 0.30 × 120 = $36 off. Sale price = $120 − $36 = $84.",
    skill: "Percent Decrease",
    difficulty: "easy",
  },
  {
    id: "sat-math-psda-003",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    stimulus: "The following data shows the test scores of 7 students: 72, 85, 90, 68, 95, 85, 78.",
    stimulusType: "table",
    question: "What is the median score?",
    choices: {
      A: "78",
      B: "82",
      C: "85",
      D: "90",
    },
    correct: "C",
    explanation: "Arrange in order: 68, 72, 78, 85, 85, 90, 95. The median is the middle value (4th of 7) = 85.",
    skill: "Descriptive Statistics",
    difficulty: "easy",
  },
  {
    id: "sat-math-psda-004",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    question: "A recipe that serves 4 people requires 3 cups of flour. How many cups of flour are needed to make the same recipe for 10 people?",
    choices: {
      A: "6.5",
      B: "7",
      C: "7.5",
      D: "8",
    },
    correct: "C",
    explanation: "Set up a proportion: 3/4 = x/10 → x = 30/4 = 7.5 cups.",
    skill: "Ratios and Proportions",
    difficulty: "easy",
  },
  {
    id: "sat-math-psda-005",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    stimulus: "A scatterplot shows the relationship between hours studied (x-axis) and exam score (y-axis) for 30 students. The line of best fit has equation y = 5x + 55.",
    stimulusType: "graph",
    question: "According to the line of best fit, what score would be predicted for a student who studied 8 hours?",
    choices: {
      A: "85",
      B: "90",
      C: "95",
      D: "100",
    },
    correct: "C",
    explanation: "Substitute x = 8: y = 5(8) + 55 = 40 + 55 = 95.",
    skill: "Linear Models",
    difficulty: "easy",
  },
  {
    id: "sat-math-psda-006",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    question: "A bag contains 4 red marbles, 3 blue marbles, and 5 green marbles. If one marble is chosen at random, what is the probability that it is NOT green?",
    choices: {
      A: "5/12",
      B: "7/12",
      C: "1/3",
      D: "2/3",
    },
    correct: "B",
    explanation: "Total marbles = 4 + 3 + 5 = 12. Green marbles = 5. Not green = 12 − 5 = 7. P(not green) = 7/12.",
    skill: "Probability",
    difficulty: "easy",
  },
  {
    id: "sat-math-psda-007",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    question: "The mean of five numbers is 14. Four of the numbers are 10, 12, 16, and 18. What is the fifth number?",
    choices: {
      A: "12",
      B: "14",
      C: "16",
      D: "18",
    },
    correct: "B",
    explanation: "Mean = sum/count → sum = 14 × 5 = 70. Known sum = 10 + 12 + 16 + 18 = 56. Fifth number = 70 − 56 = 14.",
    skill: "Descriptive Statistics",
    difficulty: "easy",
  },
  {
    id: "sat-math-psda-008",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    stimulus: "A 2022 survey asked 500 adults whether they support a new park: 310 said yes, 140 said no, and 50 were unsure. The surveyors want to generalize to the city population of 80,000 adults.",
    stimulusType: "table",
    question: "Based on the survey data, approximately how many adults in the city would be expected to say 'yes' to the park?",
    choices: {
      A: "42,000",
      B: "49,600",
      C: "56,000",
      D: "62,000",
    },
    correct: "B",
    explanation: "310/500 = 62% support the park. 62% of 80,000 = 0.62 × 80,000 = 49,600.",
    skill: "Making Inferences from Data",
    difficulty: "medium",
  },
  {
    id: "sat-math-psda-009",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    question: "A population of bacteria doubles every 3 hours. If there are 500 bacteria initially, which expression gives the number of bacteria after t hours?",
    choices: {
      A: "500 · 2^t",
      B: "500 · 2^(t/3)",
      C: "500 · 3^(t/2)",
      D: "500 + 2t",
    },
    correct: "B",
    explanation: "The population doubles every 3 hours, so the doubling period is 3. Exponential growth: N = 500 · 2^(t/3). After 3 hours: 500 · 2^1 = 1000 ✓. After 6 hours: 500 · 2^2 = 2000 ✓.",
    skill: "Exponential Models",
    difficulty: "medium",
  },
  {
    id: "sat-math-psda-010",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    question: "A store marks up all products by 40% from the wholesale price. If a product's retail price is $56, what is the wholesale price?",
    choices: {
      A: "$33.60",
      B: "$36",
      C: "$40",
      D: "$42",
    },
    correct: "C",
    explanation: "Retail = wholesale × 1.40. So wholesale = 56 / 1.40 = 40.",
    skill: "Percent Markup",
    difficulty: "medium",
  },
  {
    id: "sat-math-psda-011",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    stimulus: "Heights of 6 students (in inches): 60, 64, 65, 70, 72, 73",
    stimulusType: "table",
    question: "What is the range of these heights?",
    choices: {
      A: "9",
      B: "11",
      C: "12",
      D: "13",
    },
    correct: "D",
    explanation: "Range = maximum − minimum = 73 − 60 = 13 inches.",
    skill: "Descriptive Statistics",
    difficulty: "easy",
  },
  {
    id: "sat-math-psda-012",
    unit: "math-psda",
    unitName: "Problem-Solving & Data Analysis",
    section: "Math",
    question: "A car travels 240 miles in 4 hours. At the same rate, how long will it take to travel 360 miles?",
    choices: {
      A: "5 hours",
      B: "6 hours",
      C: "7 hours",
      D: "8 hours",
    },
    correct: "B",
    explanation: "Rate = 240/4 = 60 mph. Time for 360 miles = 360/60 = 6 hours.",
    skill: "Rates and Ratios",
    difficulty: "easy",
  },

  // ══════════════════════════════════════════════════════
  // MATH — Geometry & Trigonometry
  // ══════════════════════════════════════════════════════

  {
    id: "sat-math-geo-001",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "A rectangle has a length of 12 cm and a width of 5 cm. What is the length of the diagonal?",
    choices: {
      A: "10",
      B: "12",
      C: "13",
      D: "17",
    },
    correct: "C",
    explanation: "Use the Pythagorean theorem: d² = 12² + 5² = 144 + 25 = 169. d = √169 = 13 cm.",
    skill: "Pythagorean Theorem",
    difficulty: "easy",
  },
  {
    id: "sat-math-geo-002",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "What is the area of a triangle with base 8 cm and height 11 cm?",
    choices: {
      A: "40 cm²",
      B: "44 cm²",
      C: "48 cm²",
      D: "88 cm²",
    },
    correct: "B",
    explanation: "Area = (1/2) × base × height = (1/2) × 8 × 11 = 44 cm².",
    skill: "Area of Triangle",
    difficulty: "easy",
  },
  {
    id: "sat-math-geo-003",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "The circumference of a circle is 20π cm. What is the area of the circle?",
    choices: {
      A: "100π cm²",
      B: "200π cm²",
      C: "40π cm²",
      D: "400π cm²",
    },
    correct: "A",
    explanation: "C = 2πr → 20π = 2πr → r = 10. Area = πr² = π(10)² = 100π cm².",
    skill: "Circles",
    difficulty: "easy",
  },
  {
    id: "sat-math-geo-004",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "Two angles are supplementary. One angle measures (3x + 10)° and the other measures (2x − 5)°. What is x?",
    choices: {
      A: "25",
      B: "30",
      C: "35",
      D: "45",
    },
    correct: "C",
    explanation: "Supplementary angles sum to 180°: (3x + 10) + (2x − 5) = 180 → 5x + 5 = 180 → 5x = 175 → x = 35.",
    skill: "Angle Relationships",
    difficulty: "easy",
  },
  {
    id: "sat-math-geo-005",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "In right triangle ABC, angle C = 90°, AC = 6, and BC = 8. What is sin(A)?",
    choices: {
      A: "3/5",
      B: "4/5",
      C: "3/4",
      D: "4/3",
    },
    correct: "B",
    explanation: "First find the hypotenuse AB: √(6² + 8²) = √(36 + 64) = √100 = 10. sin(A) = opposite/hypotenuse = BC/AB = 8/10 = 4/5.",
    skill: "Trigonometric Ratios",
    difficulty: "medium",
  },
  {
    id: "sat-math-geo-006",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "A cylinder has a radius of 4 cm and a height of 9 cm. What is the volume of the cylinder in terms of π?",
    choices: {
      A: "36π cm³",
      B: "72π cm³",
      C: "144π cm³",
      D: "324π cm³",
    },
    correct: "C",
    explanation: "Volume = πr²h = π(4²)(9) = π(16)(9) = 144π cm³.",
    skill: "Volume",
    difficulty: "easy",
  },
  {
    id: "sat-math-geo-007",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "A line segment has endpoints at (1, 2) and (7, 10). What is the length of the segment?",
    choices: {
      A: "8",
      B: "10",
      C: "12",
      D: "14",
    },
    correct: "B",
    explanation: "Distance = √((7−1)² + (10−2)²) = √(36 + 64) = √100 = 10.",
    skill: "Distance Formula",
    difficulty: "easy",
  },
  {
    id: "sat-math-geo-008",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "A sector of a circle has a radius of 6 and a central angle of 90°. What is the area of the sector in terms of π?",
    choices: {
      A: "3π",
      B: "6π",
      C: "9π",
      D: "12π",
    },
    correct: "C",
    explanation: "Area of sector = (θ/360°) × πr² = (90/360) × π(36) = (1/4)(36π) = 9π.",
    skill: "Arc Length and Sector Area",
    difficulty: "medium",
  },
  {
    id: "sat-math-geo-009",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "In a right triangle, one acute angle measures 30°. If the hypotenuse is 12, what is the length of the side opposite the 30° angle?",
    choices: {
      A: "4",
      B: "6",
      C: "6√3",
      D: "12",
    },
    correct: "B",
    explanation: "In a 30-60-90 triangle, the side opposite 30° is half the hypotenuse: 12/2 = 6.",
    skill: "Special Right Triangles",
    difficulty: "medium",
  },
  {
    id: "sat-math-geo-010",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "Two similar triangles have corresponding sides in the ratio 3:5. If the area of the smaller triangle is 27 cm², what is the area of the larger triangle?",
    choices: {
      A: "45 cm²",
      B: "75 cm²",
      C: "81 cm²",
      D: "135 cm²",
    },
    correct: "B",
    explanation: "The ratio of areas of similar figures equals the square of the ratio of corresponding sides. (3/5)² = 9/25. If smaller area = 27, then 27/larger = 9/25 → larger = 27 × 25/9 = 75 cm².",
    skill: "Similar Figures",
    difficulty: "hard",
  },
  {
    id: "sat-math-geo-011",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "The equation of a circle is (x − 3)² + (y + 2)² = 25. What are the center and radius of this circle?",
    choices: {
      A: "Center (3, −2), radius 5",
      B: "Center (−3, 2), radius 5",
      C: "Center (3, −2), radius 25",
      D: "Center (3, 2), radius 5",
    },
    correct: "A",
    explanation: "Standard form is (x − h)² + (y − k)² = r². Here h = 3, k = −2, r² = 25 → r = 5. Center (3, −2).",
    skill: "Circles in the Coordinate Plane",
    difficulty: "medium",
  },
  {
    id: "sat-math-geo-012",
    unit: "math-geometry",
    unitName: "Geometry & Trigonometry",
    section: "Math",
    question: "A right triangle has legs of length a and b and hypotenuse of length c. If a = 9 and c = 15, what is b?",
    choices: {
      A: "6",
      B: "9",
      C: "12",
      D: "18",
    },
    correct: "C",
    explanation: "Pythagorean theorem: a² + b² = c² → 81 + b² = 225 → b² = 144 → b = 12.",
    skill: "Pythagorean Theorem",
    difficulty: "easy",
  },
];
