export type Flashcard = {
  id: string;
  unit: string;
  unitName: string;
  front: string;
  back: string;
  tags: string[];
};

export const AP_WORLD_FLASHCARDS: Flashcard[] = [
  // ─────────────────────────────────────────────
  // UNIT 1 — The Global Tapestry (1200–1450)
  // ─────────────────────────────────────────────
  {
    id: "w1-001",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the significance of the Song Dynasty's use of paper money?",
    back: "Song China pioneered paper money (jiaozi) to facilitate large-scale trade, reducing the need to transport heavy coins and stimulating commercial growth. This reflects China's sophisticated market economy during this period.",
    tags: ["song dynasty", "china", "economy", "trade"],
  },
  {
    id: "w1-002",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the role of the Swahili Coast in Indian Ocean trade?",
    back: "Swahili city-states (Kilwa, Mombasa, Zanzibar) served as crucial intermediaries in Indian Ocean trade, exporting gold, ivory, and enslaved people from interior Africa in exchange for Indian textiles and Chinese porcelain. They developed a hybrid Bantu-Arabic culture and converted to Islam.",
    tags: ["swahili", "africa", "indian ocean", "trade"],
  },
  {
    id: "w1-003",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the Pax Mongolica and how did it affect trade?",
    back: "The Pax Mongolica ('Mongol Peace') was a period of relative stability across Eurasia under Mongol rule. It facilitated long-distance trade along the Silk Roads and allowed merchants, diplomats, and missionaries like Marco Polo to travel from China to Europe with relative safety.",
    tags: ["mongols", "silk road", "pax mongolica", "trade"],
  },
  {
    id: "w1-004",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What were the key features of the Delhi Sultanate?",
    back: "The Delhi Sultanate (1206–1526) was a Muslim sultanate in northern India that introduced Persian administrative practices, spread Islam, and built mosques and madrasas. It resisted Mongol invasions but eventually gave way to the Mughal Empire.",
    tags: ["delhi sultanate", "india", "islam", "south asia"],
  },
  {
    id: "w1-005",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the significance of Mali's Mansa Musa?",
    back: "Mansa Musa (r. 1312–1337) was Mali's most powerful ruler. His 1324 pilgrimage to Mecca displayed Mali's enormous wealth (he brought ~60,000 men and camels laden with gold), spread Islam, and put Mali on European maps. He patronized Islamic scholarship in Timbuktu.",
    tags: ["mali", "mansa musa", "islam", "africa", "trade"],
  },
  {
    id: "w1-006",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "How did Neo-Confucianism shape Song Dynasty society?",
    back: "Neo-Confucianism synthesized Confucian ethics with Buddhist and Daoist ideas. It reinforced social hierarchies, emphasized filial piety, and promoted the civil service examination. It also reinforced patriarchal norms, including the practice of foot binding among elite women.",
    tags: ["confucianism", "song dynasty", "china", "social structure"],
  },
  {
    id: "w1-007",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the role of camels in trans-Saharan trade?",
    back: "The domestication of camels made trans-Saharan trade viable by allowing merchants to cross the Sahara carrying heavy loads of gold, salt, and enslaved people. Camels can travel long periods without water, making them ideal for desert travel.",
    tags: ["trans-saharan", "trade", "africa", "camels"],
  },
  {
    id: "w1-008",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the Byzantine Empire's relationship with trade in 1200–1450?",
    back: "The Byzantine Empire controlled key trade routes between Europe and Asia through Constantinople. Though weakened by the Fourth Crusade (1204), it remained a commercial hub until it fell to the Ottoman Turks in 1453, shifting trade route control to the Ottomans.",
    tags: ["byzantine", "trade", "constantinople", "europe"],
  },
  {
    id: "w1-009",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What were the main goods traded on the Silk Roads?",
    back: "Silk, porcelain, and spices moved westward from China and Southeast Asia. Horses, cotton textiles, and glassware moved eastward. Beyond goods, the Silk Roads facilitated exchange of religions (Buddhism, Islam), technologies (paper, gunpowder), and diseases (Black Death).",
    tags: ["silk road", "trade", "goods", "exchange"],
  },
  {
    id: "w1-010",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "How did monsoon winds enable Indian Ocean trade?",
    back: "Merchants used predictable seasonal monsoon winds to navigate the Indian Ocean. Summer monsoons blew northeast toward India and Arabia; winter monsoons blew southwest toward Africa and Southeast Asia. This enabled regular, reliable trade across the entire ocean basin.",
    tags: ["indian ocean", "monsoon", "trade", "navigation"],
  },
  {
    id: "w1-011",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the role of the civil service examination in Tang/Song China?",
    back: "The civil service examination tested knowledge of Confucian texts and selected government officials based on merit rather than hereditary privilege. It created a professional bureaucracy (scholar-gentry class), reduced aristocratic power, and tied social advancement to education.",
    tags: ["civil service", "china", "confucianism", "meritocracy"],
  },
  {
    id: "w1-012",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the Great Zimbabwe and why was it significant?",
    back: "Great Zimbabwe (c. 1100–1450) was a massive stone-walled city in southern Africa, capital of a wealthy kingdom that controlled gold trade from interior Africa to the Swahili Coast. Its sophisticated stone architecture (built without mortar) demonstrates advanced engineering and complex political organization.",
    tags: ["great zimbabwe", "africa", "trade", "gold"],
  },
  {
    id: "w1-013",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the Aztec (Mexica) Empire's tribute system?",
    back: "The Aztec Empire ruled through a tributary system — conquered peoples paid tribute in goods (cacao, textiles, jade, sacrificial captives) to Tenochtitlan rather than being directly governed. This built enormous wealth at the capital while leaving local governance intact, but bred resentment that Spanish conquistadors exploited.",
    tags: ["aztec", "mexica", "tribute", "mesoamerica"],
  },
  {
    id: "w1-014",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "How did the Inca Empire maintain control over a vast territory without a written language?",
    back: "The Inca used quipus (knotted strings encoding numerical data), a network of roads (40,000 km), a system of relay runners (chasquis), mit'a labor obligations (mandatory state labor), and a practice of moving conquered populations (mitmaqs) to prevent rebellion. The road system also enabled rapid troop movement.",
    tags: ["inca", "south america", "administration", "quipu"],
  },
  {
    id: "w1-015",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the significance of Timbuktu as a center of Islamic scholarship?",
    back: "Timbuktu (in the Mali and later Songhai empires) housed the University of Sankore, attracting scholars from across the Islamic world. It held hundreds of thousands of manuscripts covering theology, law, mathematics, and astronomy, making it one of the world's great intellectual centers in the 14th–16th centuries.",
    tags: ["timbuktu", "mali", "islam", "scholarship"],
  },
  {
    id: "w1-016",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the role of Venetian and Genoese merchants in Mediterranean trade?",
    back: "Italian city-states, especially Venice and Genoa, dominated Mediterranean commerce in the 1200s–1400s. They established trading colonies across the eastern Mediterranean, brokered trade between Europe and the Islamic world/Asia, and developed early capitalist institutions (bills of exchange, insurance, banking).",
    tags: ["venice", "genoa", "mediterranean", "trade", "europe"],
  },
  {
    id: "w1-017",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the significance of the Crusades for cross-cultural exchange?",
    back: "The Crusades (1096–1291) were European Christian military campaigns to capture the Holy Land. They intensified contact between Christian Europe and the Islamic world, facilitating transfer of goods (spices, silk), ideas (Arabic numerals, philosophy, medicine), and technologies. They also stimulated demand for Asian luxury goods in Europe.",
    tags: ["crusades", "europe", "islam", "exchange"],
  },
  {
    id: "w1-018",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the Champa rice and why did it matter for China?",
    back: "Champa rice, introduced from Vietnam to China during the Song Dynasty, was drought-resistant, fast-ripening (allowing 2–3 harvests per year), and could grow on poor soils. It enabled a massive population increase (from ~50 million to ~100 million in Song China) that fueled urbanization and commercialization.",
    tags: ["champa rice", "song dynasty", "agriculture", "population"],
  },
  {
    id: "w1-019",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the role of the horse collar in medieval European agriculture?",
    back: "The heavy horse collar (adopted c. 800–1000 CE) allowed horses to pull plows without choking, making horse-powered agriculture far more efficient than ox-drawn plows. Combined with the three-field system, it dramatically increased agricultural output in medieval Europe, supporting population growth.",
    tags: ["technology", "europe", "agriculture", "medieval"],
  },
  {
    id: "w1-020",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    front: "What was the significance of the Mongol conquest of the Abbasid Caliphate (1258)?",
    back: "The Mongols under Hulagu Khan sacked Baghdad in 1258, killing the Caliph and destroying the Abbasid Caliphate — the center of the Islamic world for 500 years. The House of Wisdom (major library) was reportedly destroyed. This ended the Islamic Golden Age and shifted Islamic cultural centers to Cairo, Persia, and India.",
    tags: ["mongols", "abbasid", "baghdad", "islam", "1258"],
  },

  // ─────────────────────────────────────────────
  // UNIT 2 — Networks of Exchange (1200–1450)
  // ─────────────────────────────────────────────
  {
    id: "w2-001",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "How did the Black Death spread and what were its effects?",
    back: "The Black Death (bubonic plague) spread along trade routes from Central Asia, reaching Europe by 1347. It killed 30–50% of Europe's population, disrupted feudal labor systems, led to peasant revolts (Jacquerie, English Peasants' Revolt), weakened the Church's authority, and accelerated social change.",
    tags: ["black death", "plague", "europe", "trade routes"],
  },
  {
    id: "w2-002",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the significance of Ibn Battuta?",
    back: "Ibn Battuta was a Moroccan Muslim scholar who traveled 75,000+ miles across the Islamic world (1325–1354), visiting Mali, the Swahili Coast, India, and China. His travel account (Rihla) provides invaluable primary source evidence about medieval trade networks and Islamic civilization's geographic reach.",
    tags: ["ibn battuta", "travel", "islam", "primary source"],
  },
  {
    id: "w2-003",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "How did the Mongol conquests affect the Silk Road?",
    back: "Mongol conquests initially disrupted trade through violence (sacking Baghdad, 1258). Once consolidated, the Pax Mongolica secured trade routes from China to Persia, allowing merchants like Marco Polo to travel safely. The Mongols also actively promoted commerce, reducing tariffs and protecting merchants.",
    tags: ["mongols", "silk road", "pax mongolica", "trade"],
  },
  {
    id: "w2-004",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the role of Sufism in spreading Islam?",
    back: "Sufi missionaries spread Islam through mystical practices, poetry, and music that appealed to local populations. Unlike strict Islamic law, Sufism often accommodated local customs, making conversion more attractive. Sufis were key in spreading Islam to Sub-Saharan Africa, Central Asia, and Southeast Asia.",
    tags: ["sufism", "islam", "missionaries", "spread"],
  },
  {
    id: "w2-005",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What technologies diffused along the Silk Roads during 1200–1450?",
    back: "Key technologies spreading along Silk Roads: papermaking and printing (China → West), gunpowder (China → Islamic world → Europe), magnetic compass (facilitating navigation), astrolabe, and steel production techniques. Agricultural products (citrus, cotton, sugarcane) also spread, transforming diets and economies.",
    tags: ["technology", "diffusion", "silk road", "innovation"],
  },
  {
    id: "w2-006",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the role of Timbuktu in trans-Saharan trade?",
    back: "Timbuktu was a major commercial and intellectual center in Mali (later Songhai). It sat at the intersection of trans-Saharan trade routes, trading gold and salt. It housed the University of Sankore, attracting thousands of Islamic scholars, making it both a trade hub and center of learning.",
    tags: ["timbuktu", "mali", "trade", "scholarship", "islam"],
  },
  {
    id: "w2-007",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "How did diasporic merchant communities facilitate trade?",
    back: "Merchant diasporas (Chinese in Southeast Asia, Indian in East Africa, Jewish across Eurasia, Arab across the Indian Ocean) created trust networks across long distances. They maintained cultural identity while adapting locally, reducing transaction costs through shared legal norms and community enforcement of contracts.",
    tags: ["diaspora", "merchants", "trade", "networks"],
  },
  {
    id: "w2-008",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the significance of Samarkand on the Silk Road?",
    back: "Samarkand (modern Uzbekistan) was a key Silk Road node. Under Timur (Tamerlane, r. 1370–1405), it became a magnificent imperial capital filled with scholars and artisans from across the Islamic world. It was a center of Persian Islamic culture, trade, and astronomy, connecting China, Persia, and the Mediterranean.",
    tags: ["samarkand", "silk road", "central asia", "timur"],
  },
  {
    id: "w2-009",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the significance of the Zheng He voyages (1405–1433)?",
    back: "Admiral Zheng He led 7 massive voyages from China to Southeast Asia, India, Arabia, and East Africa. The voyages demonstrated Chinese naval power, established tributary relationships, and exchanged goods. However, the Ming Dynasty later banned maritime trade (haijin policy), abandoning China's maritime expansion.",
    tags: ["zheng he", "china", "ming dynasty", "indian ocean"],
  },
  {
    id: "w2-010",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the significance of the Hanseatic League?",
    back: "The Hanseatic League was a commercial confederation of merchant guilds and market towns in Northern Europe (c. 1200s–1600s). It dominated Baltic and North Sea trade in goods like grain, timber, fur, and fish. It developed standardized commercial practices and demonstrated the power of economic cooperation.",
    tags: ["hanseatic league", "europe", "trade", "guild"],
  },
  {
    id: "w2-011",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the Indian Ocean trading system's role in spreading Hinduism and Buddhism?",
    back: "Indian merchants and missionaries spread Hinduism and Buddhism across Southeast Asia (Funan, Khmer, Srivijaya, Majapahit empires) via Indian Ocean trade routes. Local rulers adopted Indian religious concepts, writing systems, and political ideas (divine kingship), creating 'Indianized' kingdoms blending local and Indian cultures.",
    tags: ["hinduism", "buddhism", "indian ocean", "southeast asia", "diffusion"],
  },
  {
    id: "w2-012",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the significance of the city of Kilwa?",
    back: "Kilwa (modern Tanzania) was the wealthiest Swahili city-state, controlling the gold trade from Great Zimbabwe through the port of Sofala. Ibn Battuta called it one of the most beautiful cities in the world. It minted its own coins and had elaborate stone architecture, demonstrating the wealth of East African trade.",
    tags: ["kilwa", "swahili", "africa", "gold", "indian ocean"],
  },
  {
    id: "w2-013",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "How did the plague affect the Islamic world differently than Europe?",
    back: "The Black Death also devastated the Islamic world — it killed ~1/3 of Egypt's population and severely disrupted Mamluk Egypt and the Middle East. Islamic scholars debated whether it was divine punishment or mercy (martyrdom for believers). Like Europe, it disrupted labor systems and trade, but the Ottoman Empire later filled the power vacuum.",
    tags: ["black death", "plague", "islam", "middle east"],
  },
  {
    id: "w2-014",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the role of the Arabian Sea in connecting the Indian Ocean network?",
    back: "The Arabian Sea was the western arm of the Indian Ocean trade network, connecting the Persian Gulf, Red Sea, and Indian subcontinent. Arab, Indian, and Persian merchants used it to trade spices, textiles, gold, and enslaved people. It was controlled by Arab and later Persian merchants who acted as intermediaries between India and the Mediterranean.",
    tags: ["arabian sea", "indian ocean", "arab", "trade"],
  },
  {
    id: "w2-015",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the significance of the spread of Islam to Southeast Asia?",
    back: "Islam spread to Southeast Asia primarily through Muslim merchants along Indian Ocean trade routes (not military conquest). By 1400, coastal trading cities like Malacca had converted to Islam, which facilitated commerce with other Muslim merchants. Malacca became a major hub controlling the Strait of Malacca, the key chokepoint for spice trade.",
    tags: ["islam", "southeast asia", "malacca", "trade", "conversion"],
  },
  {
    id: "w2-016",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the significance of gold and salt in trans-Saharan trade?",
    back: "Gold from West African kingdoms (Ghana, Mali, Songhai) was traded northward across the Sahara for salt from Saharan mines (like Taghaza). Salt was essential for food preservation in tropical West Africa, while gold was the foundation of the trans-Saharan economy and paid for North African and European goods.",
    tags: ["gold", "salt", "trans-saharan", "mali", "ghana"],
  },
  {
    id: "w2-017",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "How did the Mongols affect the diffusion of culture and disease?",
    back: "Mongol conquests created a connected Eurasian world: the plague traveled west along Mongol trade routes; Chinese technologies (printing, gunpowder) reached the Islamic world and Europe; Persian administrators spread administrative practices; and artistic styles merged (Ilkhanate art blended Persian and Chinese elements).",
    tags: ["mongols", "diffusion", "plague", "culture", "exchange"],
  },
  {
    id: "w2-018",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What were the four main trade networks of 1200–1450?",
    back: "1. Silk Roads (overland Eurasian routes); 2. Indian Ocean network (maritime routes from East Africa to China); 3. Trans-Saharan routes (across the Sahara connecting West Africa to North Africa/Mediterranean); 4. Mediterranean Sea trade (connecting Europe, North Africa, and the Middle East).",
    tags: ["trade networks", "silk road", "indian ocean", "trans-saharan", "mediterranean"],
  },
  {
    id: "w2-019",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "What was the significance of Marco Polo's travels?",
    back: "Marco Polo (1271–1295) traveled from Venice to the court of Kublai Khan in China, spending ~17 years in Asia. His account (Il Milione) introduced Europeans to Chinese civilization, inspiring curiosity about Asia and eventually motivating Columbus's search for a western sea route to 'the Indies.'",
    tags: ["marco polo", "mongols", "china", "europe", "exploration"],
  },
  {
    id: "w2-020",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    front: "How did the fall of the Western Roman Empire affect European trade?",
    back: "The fall of Rome (476 CE) disrupted Mediterranean trade, reduced urbanization, and fragmented political authority in Western Europe. Long-distance trade declined, replaced by local subsistence economies and manorialism. However, Byzantine Constantinople and the Islamic world maintained Mediterranean commerce that eventually reintegrated Western Europe.",
    tags: ["rome", "europe", "trade", "medieval", "fragmentation"],
  },

  // ─────────────────────────────────────────────
  // UNIT 3 — Land-Based Empires (1450–1750)
  // ─────────────────────────────────────────────
  {
    id: "w3-001",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What were the Gunpowder Empires and why are they significant?",
    back: "The Gunpowder Empires — Ottoman, Safavid, and Mughal — used firearms and cannons to conquer and consolidate large territories. Their military power rested on gunpowder technology. They represent a shift from cavalry-based nomadic conquest to infantry and artillery-based imperial expansion.",
    tags: ["gunpowder empires", "ottoman", "safavid", "mughal", "military"],
  },
  {
    id: "w3-002",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "How did the Ottoman Empire use the devshirme system?",
    back: "The devshirme was a system where Christian boys from the Balkans were taken, converted to Islam, educated, and trained as soldiers (Janissaries) or administrators. This gave the sultan loyal servants unconnected to Ottoman noble families, strengthening centralized power against potential aristocratic rivals.",
    tags: ["ottoman", "devshirme", "janissaries", "administration"],
  },
  {
    id: "w3-003",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the significance of the fall of Constantinople in 1453?",
    back: "The Ottoman conquest of Constantinople ended the Byzantine Empire, gave the Ottomans control of Eurasian trade routes, and demonstrated the power of gunpowder artillery (used to breach previously impenetrable walls). It pushed European powers to seek alternative sea routes to Asia, directly motivating the Age of Exploration.",
    tags: ["constantinople", "ottoman", "1453", "byzantine"],
  },
  {
    id: "w3-004",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the Safavid Empire's religious policy and its significance?",
    back: "The Safavid Empire made Twelver Shia Islam the state religion of Persia (Iran), creating a lasting Sunni-Shia divide in the Islamic world. This caused persistent conflict with the Sunni Ottoman Empire (Battle of Chaldiran, 1514) and shaped the religious geography of the Middle East to this day.",
    tags: ["safavid", "shia", "sunni", "islam", "persia"],
  },
  {
    id: "w3-005",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "How did Akbar the Great's religious policy strengthen the Mughal Empire?",
    back: "Akbar pursued sulh-i-kul ('universal peace'), eliminating the jizya tax on non-Muslims, marrying Hindu Rajput princesses, employing Hindus in his administration, and creating the syncretic Din-i-Ilahi faith. This helped integrate the majority Hindu population, built broad legitimacy, and consolidated Mughal power.",
    tags: ["akbar", "mughal", "religious tolerance", "india"],
  },
  {
    id: "w3-006",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "How did the Qing Dynasty consolidate control over China?",
    back: "The Manchu Qing (1644–1912) maintained control through: requiring Han men to wear the queue (Manchu hairstyle) as submission, preserving Chinese Confucian administrative traditions, employing Han officials in a dual-track system, conducting civil service exams, and presenting themselves as legitimate Confucian rulers.",
    tags: ["qing", "china", "manchu", "administration"],
  },
  {
    id: "w3-007",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the significance of Peter the Great's westernization of Russia?",
    back: "Peter the Great (r. 1682–1725) westernized Russia by adopting European technology, dress, and administrative practices. He built St. Petersburg as a 'window to the West,' expanded Russia to the Baltic Sea, created a Table of Ranks (meritocratic bureaucracy), modernized the military, and forced nobles to shave their beards.",
    tags: ["russia", "peter the great", "westernization", "expansion"],
  },
  {
    id: "w3-008",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the Ottoman millet system?",
    back: "The millet system allowed religious minorities (Christians, Jews) within the Ottoman Empire to govern themselves according to their own religious laws in matters of personal status (marriage, inheritance, education). This granted significant autonomy to non-Muslims, helping the diverse empire maintain stability without forced conversion.",
    tags: ["ottoman", "millet", "religious minorities", "tolerance"],
  },
  {
    id: "w3-009",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the role of the tax farming system in land-based empires?",
    back: "Tax farming (used by Ottomans, Mughals, and others) contracted private individuals to collect taxes in a region, paying the government a fixed sum and keeping the surplus. It provided immediate revenue without large bureaucracies but encouraged over-extraction from peasants and reduced central control over provinces.",
    tags: ["tax farming", "ottoman", "mughal", "administration", "economics"],
  },
  {
    id: "w3-010",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the significance of the Mughal Taj Mahal?",
    back: "The Taj Mahal (built 1632–1653 by Shah Jahan) was a mausoleum for his wife Mumtaz Mahal. It represents the height of Mughal architectural achievement, blending Persian, Islamic, and Indian styles. It required 20,000 workers over 20 years and symbolized the wealth, aesthetic refinement, and power of the Mughal Empire at its peak.",
    tags: ["mughal", "taj mahal", "architecture", "india", "shah jahan"],
  },
  {
    id: "w3-011",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "How did Suleiman the Magnificent expand Ottoman power?",
    back: "Suleiman I (r. 1520–1566) conquered Belgrade, Rhodes, Hungary (Battle of Mohacs, 1526), and besieged Vienna (1529). He codified Ottoman law (earning the title 'Lawgiver'), patronized the arts, and expanded into North Africa and the Persian Gulf. His reign marked the height of Ottoman power and territory.",
    tags: ["suleiman", "ottoman", "expansion", "law"],
  },
  {
    id: "w3-012",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the significance of the Thirty Years' War (1618–1648) for European state-building?",
    back: "The Thirty Years' War was a devastating conflict fought primarily in the Holy Roman Empire. The Peace of Westphalia (1648) established the principle of state sovereignty and non-interference in internal affairs — the foundation of the modern international state system. It ended religious warfare between Catholics and Protestants in Germany.",
    tags: ["thirty years war", "europe", "westphalia", "sovereignty", "state building"],
  },
  {
    id: "w3-013",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the role of the Janissaries in the Ottoman Empire?",
    back: "Janissaries were an elite infantry corps of the Ottoman army, recruited through the devshirme system. They were among the first military units to use firearms systematically, giving the Ottomans a military advantage. Over time they became a powerful political force, able to depose sultans who threatened their privileges.",
    tags: ["janissaries", "ottoman", "military", "devshirme"],
  },
  {
    id: "w3-014",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "How did the Russian Empire expand eastward under the Tsars?",
    back: "Russia expanded across Siberia from the 1580s to 1640s, reaching the Pacific by 1639. Cossack warriors and the promise of fur wealth drove expansion. Russia established tribute relationships with indigenous Siberian peoples, gained access to enormous natural resources, and eventually reached Alaska, creating a transcontinental empire.",
    tags: ["russia", "siberia", "expansion", "fur trade", "cossacks"],
  },
  {
    id: "w3-015",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the significance of Aurangzeb's reign for the Mughal Empire?",
    back: "Aurangzeb (r. 1658–1707) reversed Akbar's religious tolerance: he reinstated the jizya tax on non-Muslims, banned Hindu practices, and destroyed temples. This alienated the Hindu majority, sparked Maratha rebellions under Shivaji, and began the Mughal Empire's decline. His reign illustrates how religious policy can destabilize multi-ethnic empires.",
    tags: ["aurangzeb", "mughal", "religious policy", "decline", "india"],
  },
  {
    id: "w3-016",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the role of the Silk Road in the decline of land-based empires?",
    back: "As European sea routes (around Africa to Asia) became dominant after 1500, overland Silk Road trade declined in relative importance. Empires like the Ottomans that taxed Silk Road commerce saw reduced revenues. This was one factor in gradual economic stagnation, though the Silk Roads never fully disappeared.",
    tags: ["silk road", "decline", "sea routes", "trade", "ottoman"],
  },
  {
    id: "w3-017",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the significance of the Battle of Lepanto (1571)?",
    back: "The Battle of Lepanto was a naval battle where a coalition of Catholic maritime states (the Holy League, led by Spain) decisively defeated the Ottoman fleet in the Mediterranean. While the Ottomans quickly rebuilt their navy, Lepanto marked a check on Ottoman westward expansion and demonstrated European naval capability.",
    tags: ["lepanto", "ottoman", "spain", "naval", "1571"],
  },
  {
    id: "w3-018",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the significance of Louis XIV's court at Versailles?",
    back: "Louis XIV (r. 1643–1715) built the Palace of Versailles and required nobles to live there, keeping them under royal supervision and away from their power bases. He centralized power ('L'état, c'est moi' — 'I am the state'), built a professional bureaucracy and army, established French cultural dominance, and represents absolute monarchy at its height.",
    tags: ["louis XIV", "france", "versailles", "absolutism", "europe"],
  },
  {
    id: "w3-019",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "How did the Ottoman Empire handle its religiously diverse population?",
    back: "The Ottomans used the millet system, granting religious autonomy to non-Muslim communities. The empire was officially Islamic but pragmatic — Christians and Jews were dhimmis (protected subjects) who paid the jizya tax. This multi-confessional tolerance allowed the empire to govern a diverse population spanning three continents.",
    tags: ["ottoman", "diversity", "millet", "dhimmi", "tolerance"],
  },
  {
    id: "w3-020",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    front: "What was the significance of the Safavid-Ottoman conflict?",
    back: "The Safavid-Ottoman rivalry (16th–18th centuries) was driven by: Sunni-Shia religious differences, competition for territory (Iraq, Anatolia), and the Ottomans' fear of Safavid influence on Shia Muslims in Ottoman territory. Their conflicts (e.g., Battle of Chaldiran, 1514) defined the modern boundary between Turkey and Iran.",
    tags: ["safavid", "ottoman", "conflict", "sunni", "shia"],
  },

  // ─────────────────────────────────────────────
  // UNIT 4 — Transoceanic Interconnections (1450–1750)
  // ─────────────────────────────────────────────
  {
    id: "w4-001",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the Columbian Exchange and what were its most significant effects?",
    back: "The Columbian Exchange (after 1492) was the transfer of plants, animals, diseases, and people between the Americas, Europe, Africa, and Asia. Key transfers: potatoes/maize/tomatoes (Americas → Europe/Asia, causing population booms); horses/cattle/smallpox (Europe → Americas, causing indigenous demographic collapse); sugar (Americas plantation system).",
    tags: ["columbian exchange", "americas", "europe", "disease", "trade"],
  },
  {
    id: "w4-002",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the encomienda system and how did it function?",
    back: "The encomienda granted Spanish colonizers (encomenderos) the right to extract labor and tribute from indigenous people in exchange for Christianizing them. In practice it became brutal exploitation. Bartolomé de las Casas documented abuses and advocated for indigenous rights, helping eventually replace encomienda with other labor systems.",
    tags: ["encomienda", "spanish", "colonial", "americas", "labor"],
  },
  {
    id: "w4-003",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "How did the trans-Atlantic slave trade develop and what drove it?",
    back: "The trans-Atlantic slave trade (1500s–1800s) transported ~12.5 million enslaved Africans to the Americas. Drivers: massive labor demand on sugar/tobacco/cotton plantations; indigenous American population collapse from disease; African kingdoms' participation in slave raiding for European goods (guns, textiles). Brazil received the most enslaved people (~4.9 million).",
    tags: ["slave trade", "atlantic", "africa", "americas", "plantation"],
  },
  {
    id: "w4-004",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the significance of the Portuguese trading post empire?",
    back: "Portugal established fortified trading posts (feitorias) around Africa, in India (Goa), and Southeast Asia rather than conquering large territories. They used naval power (caravel, gunpowder) to control key straits and ports, monopolizing the spice trade and disrupting existing Indian Ocean commerce, forcing merchants to pay tolls.",
    tags: ["portugal", "trading posts", "indian ocean", "spice trade"],
  },
  {
    id: "w4-005",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the Manila Galleon trade and why was it significant?",
    back: "The Manila Galleon trade (1565–1815) connected Acapulco (Mexico) with Manila (Philippines), shipping American silver to Asia in exchange for Chinese silk and porcelain. Significant as the first direct, sustained trans-Pacific trade link, it integrated the Americas into the global economy and fueled Chinese economic growth with silver.",
    tags: ["manila galleon", "silver", "trade", "pacific", "china"],
  },
  {
    id: "w4-006",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What caused the demographic collapse of indigenous Americans?",
    back: "Causes: epidemic diseases (smallpox, measles, typhus) to which indigenous people had no immunity (90% of deaths), warfare, forced labor under encomienda, and famine. The population of central Mexico fell from ~25 million in 1519 to ~1 million by 1600. This collapse justified expanding the African slave trade.",
    tags: ["indigenous", "disease", "demographic collapse", "americas"],
  },
  {
    id: "w4-007",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the significance of the joint-stock company in European expansion?",
    back: "Joint-stock companies (Dutch East India Company/VOC, British East India Company/EIC) pooled investor capital and shared risks of overseas ventures. They enabled large-scale colonization and trade, exercised quasi-governmental powers (armies, treaty-making), and represent an early form of modern corporations.",
    tags: ["joint stock", "voc", "east india company", "colonialism", "trade"],
  },
  {
    id: "w4-008",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "How did the hacienda system function in colonial Latin America?",
    back: "Haciendas were large agricultural estates owned by Spanish colonists. Indigenous and mestizo workers were bound through debt peonage — they owed money to the hacienda owner and could rarely pay it off. Haciendas produced cash crops (sugar, wheat, cattle) and replaced the encomienda as the primary labor system.",
    tags: ["hacienda", "latin america", "colonial", "labor", "debt peonage"],
  },
  {
    id: "w4-009",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the significance of the Dutch East India Company (VOC)?",
    back: "The VOC (1602–1799) was the world's first publicly traded company. It dominated Asian trade, established colonies in Indonesia, Ceylon, and South Africa, controlled the nutmeg and clove monopoly in the Spice Islands (by massacring the indigenous population of Banda), and at its peak was the wealthiest company in history.",
    tags: ["voc", "dutch", "east india", "spice islands", "monopoly"],
  },
  {
    id: "w4-010",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the significance of Potosí in the global silver trade?",
    back: "Potosí (modern Bolivia) contained the largest silver deposits in the world, discovered 1545. Using mit'a (forced indigenous labor), Spain extracted ~45,000 tons of silver over 300 years. This silver financed the Spanish Empire, flowed through global trade to China (which needed it for taxes), and caused inflation across Europe (Price Revolution).",
    tags: ["potosi", "silver", "spain", "global trade", "inflation"],
  },
  {
    id: "w4-011",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the casta system in colonial Latin America?",
    back: "The casta system was a racial hierarchy in Spanish colonies: Peninsulares (Spanish-born) at the top, Criollos (American-born Spanish), then Mestizos (Spanish-indigenous mix), Mulatos (Spanish-African mix), indigenous people, and enslaved Africans at the bottom. This system determined legal rights, occupations, and social status.",
    tags: ["casta", "colonial", "latin america", "race", "hierarchy"],
  },
  {
    id: "w4-012",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "How did sugar production transform the Atlantic world?",
    back: "Sugar cultivation on Caribbean and Brazilian plantations required massive labor — initially indigenous (who died), then African enslaved people. Sugar drove the trans-Atlantic slave trade, created enormous wealth for European planters and merchants, and established the plantation system. By 1700, sugar was the most valuable commodity in European trade.",
    tags: ["sugar", "plantation", "caribbean", "slave trade", "atlantic"],
  },
  {
    id: "w4-013",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the Protestant Reformation and how did it affect European colonialism?",
    back: "The Protestant Reformation (1517, Luther's 95 Theses) split Western Christianity into Catholic and Protestant. It fueled religious wars, motivated some to seek religious freedom in the Americas (Pilgrims), justified northern European (Protestant Dutch, English) competition with Catholic Spain and Portugal for colonial empires, and shaped colonial cultures.",
    tags: ["protestant reformation", "luther", "europe", "colonialism", "religion"],
  },
  {
    id: "w4-014",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the significance of the Treaty of Tordesillas (1494)?",
    back: "The Treaty of Tordesillas, brokered by the Pope, divided the non-Christian world between Spain (west) and Portugal (east) along a line in the Atlantic. This gave Portugal Brazil and the African/Asian trade routes, and Spain the rest of the Americas. It formalized European claims to colonize and was ignored by non-Catholic powers.",
    tags: ["tordesillas", "spain", "portugal", "colonialism", "treaty"],
  },
  {
    id: "w4-015",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "How did the Columbian Exchange affect European population growth?",
    back: "New World crops — especially the potato and maize — dramatically increased caloric supply in Europe, supporting population growth. The potato, rich in calories and vitamins, transformed Irish and Eastern European diets. By the 1800s, Europe's population had doubled, partly driven by agricultural changes from New World crops.",
    tags: ["columbian exchange", "potato", "europe", "population", "agriculture"],
  },
  {
    id: "w4-016",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the Middle Passage?",
    back: "The Middle Passage was the sea voyage from West Africa to the Americas that enslaved Africans were forced to endure. Ships were packed with captives in horrific conditions — chained, lying in their own waste, with little food or water. Death rates ranged from 10–25%. Approximately 1.8 million enslaved people died during the crossing.",
    tags: ["middle passage", "slave trade", "africa", "americas", "mortality"],
  },
  {
    id: "w4-017",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the significance of the Columbian Exchange on African history?",
    back: "New World crops (maize, manioc/cassava, sweet potatoes) spread to Africa and transformed African agriculture, supporting population growth that partially offset losses from the slave trade. However, European demand for enslaved labor devastated West and Central African communities through warfare, family separation, and demographic decline.",
    tags: ["columbian exchange", "africa", "agriculture", "slave trade"],
  },
  {
    id: "w4-018",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the role of the Catholic Church in Spanish colonialism?",
    back: "The Catholic Church was central to Spanish colonial ideology: the Requerimiento demanded indigenous people submit to the Pope and Spanish Crown before conquest; missionaries (Franciscans, Jesuits, Dominicans) converted indigenous people; and the Church built missions, schools, and hospitals. Some clergy (like Las Casas) also advocated for indigenous rights.",
    tags: ["catholic church", "spain", "colonialism", "missionaries", "indigenous"],
  },
  {
    id: "w4-019",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was the significance of Vasco da Gama's voyage (1497–1499)?",
    back: "Vasco da Gama became the first European to reach India by sailing around Africa (Cape of Good Hope). This opened a direct sea route bypassing Ottoman-controlled overland routes, allowing Portugal to access the spice trade directly. It demonstrated the viability of the Cape route and began the Portuguese Empire in Asia.",
    tags: ["vasco da gama", "portugal", "india", "cape of good hope", "exploration"],
  },
  {
    id: "w4-020",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    front: "What was syncretism and give an example in colonial Latin America?",
    back: "Syncretism is the blending of different religious or cultural traditions. In colonial Latin America, indigenous and African peoples blended their spiritual practices with Catholicism. Example: the Virgin of Guadalupe blended Catholic Marian devotion with the Aztec goddess Tonantzin; enslaved Africans in Brazil created Candomblé, combining African Yoruba religion with Catholic saints.",
    tags: ["syncretism", "religion", "latin america", "colonial", "catholic"],
  },

  // ─────────────────────────────────────────────
  // UNIT 5 — Revolutions (1750–1900)
  // ─────────────────────────────────────────────
  {
    id: "w5-001",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What Enlightenment ideas influenced the American and French Revolutions?",
    back: "Key ideas: natural rights (Locke — life, liberty, property), popular sovereignty, social contract (people can revolt if government breaks contract), separation of powers (Montesquieu), and use of reason over tradition/religion (Voltaire). These challenged divine right of kings and aristocratic privilege, justifying revolutionary action.",
    tags: ["enlightenment", "american revolution", "french revolution", "natural rights"],
  },
  {
    id: "w5-002",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What was the significance of the Haitian Revolution (1791–1804)?",
    back: "The Haitian Revolution was the only successful large-scale slave revolt in history, establishing Haiti as the first Black republic and second independent nation in the Western Hemisphere. Led by Toussaint Louverture and Dessalines, it challenged racial hierarchy globally, inspired enslaved people worldwide, and forced Napoleon to sell Louisiana.",
    tags: ["haiti", "revolution", "slavery", "toussaint", "independence"],
  },
  {
    id: "w5-003",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "How did the Industrial Revolution begin in Britain and why there?",
    back: "Britain industrialized first due to: abundant coal and iron deposits, capital from trade and empire, colonial markets and raw materials, political stability (Parliament protecting property rights), enclosure movement creating a mobile landless workforce, and innovations like Watt's steam engine (1769) and Hargreaves' spinning jenny.",
    tags: ["industrial revolution", "britain", "steam engine", "textile"],
  },
  {
    id: "w5-004",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What were the social effects of the Industrial Revolution on the working class?",
    back: "Industrialization created harsh conditions: child labor in mines and factories, 14+ hour workdays, dangerous machinery, urban slums (Manchester, London), and poverty. It created the urban proletariat, which organized into labor unions (Luddites, Chartists, trade unions) and socialist movements demanding better conditions and political rights.",
    tags: ["industrial revolution", "working class", "labor", "urbanization"],
  },
  {
    id: "w5-005",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What was the significance of the Latin American independence movements (1810–1825)?",
    back: "Most of Latin America gained independence from Spain and Portugal, led by creole elites (Simón Bolívar, José de San Martín, Miguel Hidalgo). Inspired by Enlightenment ideas and the American/French Revolutions, these movements created republics but largely maintained existing social hierarchies — criollos replaced peninsulares at the top.",
    tags: ["latin america", "independence", "bolivar", "creole", "revolution"],
  },
  {
    id: "w5-006",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What was the role of nationalism in 19th-century revolutions?",
    back: "Nationalism — belief that people sharing a common culture, language, and history should have their own state — drove revolutions across Europe. It led to Italian unification (Garibaldi, Cavour, 1861) and German unification (Bismarck, 1871), challenged multi-ethnic empires (Ottoman, Habsburg), and justified both independence movements and imperialism.",
    tags: ["nationalism", "revolution", "unification", "19th century"],
  },
  {
    id: "w5-007",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What was the significance of the abolition of slavery in the 19th century?",
    back: "Britain abolished the slave trade in 1807, slavery in its empire in 1833. The US abolished slavery in 1865 after the Civil War. Abolition was driven by Enlightenment ideals, economic shifts (wage labor more profitable), religious movements (Quakers, evangelicals), and enslaved people's resistance. It transformed labor systems but often replaced slavery with other forms of coerced labor.",
    tags: ["abolition", "slavery", "britain", "civil war", "labor"],
  },
  {
    id: "w5-008",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What was the significance of the French Revolution's radical phase (1793–1794)?",
    back: "The Reign of Terror under Robespierre and the Committee of Public Safety executed ~17,000 people (including the king and queen) to defend the revolution from internal and external enemies. It demonstrated the revolutionary potential for mass political violence, produced the Napoleonic era, and spread revolutionary ideas across Europe through French armies.",
    tags: ["french revolution", "terror", "robespierre", "napoleon", "europe"],
  },
  {
    id: "w5-009",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What were the causes and consequences of the American Revolution?",
    back: "Causes: taxation without representation (Stamp Act, Townshend Acts), Enlightenment ideas about natural rights, and colonial self-governance traditions. Consequences: first modern democratic republic based on Enlightenment principles (Constitution, Bill of Rights), inspired other revolutions (French, Latin American), and forced Britain to rethink its imperial approach.",
    tags: ["american revolution", "enlightenment", "independence", "democracy"],
  },
  {
    id: "w5-010",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "How did Napoleon spread revolutionary ideas across Europe?",
    back: "Napoleon's armies carried the Napoleonic Code (equal legal rights, religious tolerance, meritocracy over aristocracy) across Europe, abolishing feudalism and reforming legal systems in conquered territories. Though later seen as a conqueror, he spread revolutionary principles that provoked nationalist responses, ultimately leading to his defeat and the reshaping of Europe at the Congress of Vienna (1815).",
    tags: ["napoleon", "france", "revolution", "legal code", "nationalism"],
  },
  {
    id: "w5-011",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What was the significance of the Taiping Rebellion (1850–1864)?",
    back: "The Taiping Rebellion was one of history's deadliest conflicts (~20–30 million deaths). Led by Hong Xiuquan (who believed he was Jesus's brother), it challenged Qing authority, proposed radical social reforms (land redistribution, gender equality), and was ultimately suppressed with British and French help. It severely weakened the Qing Dynasty.",
    tags: ["taiping", "china", "qing", "rebellion", "religion"],
  },
  {
    id: "w5-012",
    unit: "unit-5",
    unitName: "Revolutions",
    front: "What were the key inventions of the Industrial Revolution?",
    back: "Key inventions: steam engine (Watt, 1769) powering factories and locomotives; spinning jenny (Hargreaves), water frame, and power loom (transforming textile production); Bessemer converter (cheap steel production); telegraph (Morse, long-distance communication); and railroad (Stephenson, 1825). These transformed production, transportation, and communication.",
    tags: ["industrial revolution", "inventions", "steam engine", "technology"],
  },

  // ─────────────────────────────────────────────
  // UNIT 6 — Consequences of Industrialization (1750–1900)
  // ─────────────────────────────────────────────
  {
    id: "w6-001",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What was the 'Scramble for Africa' and what drove it?",
    back: "The Scramble for Africa (1881–1914) was European powers' rapid colonization of nearly all of Africa (only Ethiopia and Liberia remained independent). Driven by: industrial need for raw materials and new markets, nationalist competition, Social Darwinism, and new technologies (steamships, quinine preventing malaria, Maxim gun giving military advantage).",
    tags: ["scramble for africa", "imperialism", "colonialism", "europe"],
  },
  {
    id: "w6-002",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What was the Berlin Conference (1884–1885)?",
    back: "European powers met in Berlin to regulate colonization of Africa — without African participation. They established rules for claiming territory (effective occupation) and drew colonial boundaries ignoring existing ethnic, cultural, and political divisions. These arbitrary borders, cutting across 10,000+ ethnic groups, created conflicts that persist in Africa today.",
    tags: ["berlin conference", "africa", "colonialism", "borders"],
  },
  {
    id: "w6-003",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "How did Japan respond to Western imperialism through the Meiji Restoration?",
    back: "After Commodore Perry forced Japan open (1853), Japan launched the Meiji Restoration (1868): rapidly industrialized by adopting Western technology and education; built a modern military (won wars against China, 1895, and Russia, 1905); abolished feudalism; created a constitutional government; and began its own imperial expansion (Korea, Taiwan, Manchuria).",
    tags: ["meiji", "japan", "industrialization", "imperialism", "modernization"],
  },
  {
    id: "w6-004",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What was Social Darwinism and how was it used to justify imperialism?",
    back: "Social Darwinism misapplied Darwin's evolution to human societies, arguing some races/nations were naturally superior. It justified European imperialism as a natural process and framed colonialism as beneficial ('civilizing mission,' Kipling's 'White Man's Burden'). It also justified domestic social hierarchies, opposing welfare as interference with 'natural selection.'",
    tags: ["social darwinism", "imperialism", "racism", "ideology"],
  },
  {
    id: "w6-005",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What were the effects of British colonialism in India?",
    back: "Britain deindustrialized India by flooding it with cheap manufactured textiles, destroying the local textile industry. It built railroads for resource extraction and troop movement, introduced English education creating a Western-educated elite (who later led independence movements), unified India administratively, and extracted massive wealth — estimated at $45 trillion over 200 years.",
    tags: ["british india", "colonialism", "deindustrialization", "railroad"],
  },
  {
    id: "w6-006",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What was the significance of the Opium Wars for China?",
    back: "Britain fought two Opium Wars (1839–42, 1856–60) to force China to allow opium imports. China's defeats led to: unequal treaties (Treaty of Nanjing, 1842), treaty ports open to foreign trade, extraterritoriality for foreigners, Hong Kong ceded to Britain, and most-favored-nation status for Western powers. These humiliations fueled Chinese nationalism and reform movements.",
    tags: ["opium war", "china", "britain", "unequal treaties", "imperialism"],
  },
  {
    id: "w6-007",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "How did indentured servitude replace slavery after abolition?",
    back: "After slavery was abolished, British planters imported millions of indentured laborers from India, China, and other Asian countries to work Caribbean and Pacific plantations. Workers signed 5-year contracts, often under false pretenses, with promised return passage. Conditions were often as brutal as slavery — hence critics called it 'new system of slavery.'",
    tags: ["indentured servitude", "labor", "post-slavery", "india", "migration"],
  },
  {
    id: "w6-008",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What was the significance of the Sepoy Mutiny (Indian Rebellion) of 1857?",
    back: "The Sepoy Mutiny began when Indian soldiers (sepoys) in the British East India Company's army mutinied over rumored use of beef and pork fat in rifle cartridges (violating Hindu and Muslim dietary laws). The rebellion spread broadly but was suppressed. Britain dissolved the EIC and took direct Crown control of India (British Raj), ending 'company rule.'",
    tags: ["sepoy mutiny", "india", "british", "east india company", "rebellion"],
  },
  {
    id: "w6-009",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What was Ethiopia's significance in the Scramble for Africa?",
    back: "Ethiopia was the only African nation (besides Liberia) to successfully resist European colonization. Emperor Menelik II modernized the military, purchased European weapons, and defeated Italian forces at the Battle of Adwa (1896). Ethiopia became a symbol of African independence and later influenced pan-Africanism and decolonization movements.",
    tags: ["ethiopia", "africa", "menelik", "adwa", "resistance"],
  },
  {
    id: "w6-010",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What was the significance of the Suez Canal (1869) for imperialism?",
    back: "The Suez Canal (built using forced Egyptian labor) cut sailing time between Europe and Asia by 40%, dramatically reducing shipping costs. Britain purchased a controlling stake in 1875, making it a key strategic asset for the British Empire. Egypt's debt crisis from canal construction led to increasing British control and eventually occupation (1882).",
    tags: ["suez canal", "egypt", "britain", "imperialism", "trade"],
  },
  {
    id: "w6-011",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "How did industrialization create new social classes?",
    back: "Industrialization created: the industrial bourgeoisie (factory owners and capitalists) who accumulated enormous wealth; the urban proletariat (factory workers) who sold their labor for wages; a growing middle class (managers, professionals, clerks). Karl Marx analyzed these class tensions in the Communist Manifesto (1848), predicting class conflict would lead to socialist revolution.",
    tags: ["class", "industrial revolution", "bourgeoisie", "proletariat", "marx"],
  },
  {
    id: "w6-012",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What was the Congo Free State and its significance?",
    back: "Leopold II of Belgium personally owned the Congo Free State (1885–1908), using forced labor to extract rubber and ivory. Workers who failed quotas faced severed hands or death. An estimated 1–10 million Congolese died. International outcry led Belgium to take over from Leopold. It remains one of history's most brutal examples of colonial exploitation.",
    tags: ["congo", "leopold", "belgium", "colonialism", "atrocity"],
  },
  {
    id: "w6-013",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    front: "What was the significance of the railroad for industrialization and imperialism?",
    back: "Railroads were the defining technology of 19th-century industrialization: they reduced transportation costs, integrated national markets, enabled resource extraction from continental interiors, facilitated troop movement (key for imperialism), and created massive demand for steel and coal. In colonies (India, Africa), railroads served imperial extraction rather than local development.",
    tags: ["railroad", "industrial revolution", "imperialism", "transportation"],
  },

  // ─────────────────────────────────────────────
  // UNIT 7 — Global Conflict (1900–present)
  // ─────────────────────────────────────────────
  {
    id: "w7-001",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What were the MAIN causes of World War I?",
    back: "MAIN: Militarism (European arms race, especially Germany vs. Britain naval rivalry), Alliance system (Triple Alliance vs. Triple Entente created chain reaction), Imperialism (competition for colonies fueling tension), Nationalism (ethnic tensions in the Balkans, Austrian-Serbian rivalry). The assassination of Archduke Franz Ferdinand in Sarajevo (1914) triggered the alliance system.",
    tags: ["WWI", "causes", "militarism", "nationalism", "alliance"],
  },
  {
    id: "w7-002",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "How did World War I transform warfare?",
    back: "WWI introduced industrial-scale killing: trench warfare creating a stalemate on the Western Front, poison gas (first used by Germany, 1915), machine guns making frontal assault suicidal, tanks (Britain, 1916), airplanes for reconnaissance and combat, and artillery barrages killing thousands in minutes. ~17 million total deaths demonstrated the catastrophic potential of industrial warfare.",
    tags: ["WWI", "warfare", "technology", "trench warfare"],
  },
  {
    id: "w7-003",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What was the significance of the Russian Revolution of 1917?",
    back: "The February Revolution (1917) overthrew the Tsar; the October Revolution brought the Bolsheviks under Lenin to power. Russia became the world's first communist state, withdrew from WWI (Treaty of Brest-Litovsk), nationalized industry, and eventually created the Soviet Union (1922) — establishing communism as a global ideological alternative to capitalism.",
    tags: ["russian revolution", "bolsheviks", "communism", "soviet union"],
  },
  {
    id: "w7-004",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "How did the Treaty of Versailles (1919) contribute to World War II?",
    back: "Versailles imposed: war guilt clause (Article 231) forcing Germany to accept sole responsibility; $33 billion in reparations; military restrictions (100,000 soldiers); and territorial losses (Alsace-Lorraine, Polish Corridor, colonies). This caused economic devastation, hyperinflation, and national humiliation that fueled resentment exploited by Hitler and the Nazi Party.",
    tags: ["versailles", "WWI", "WWII", "germany", "reparations"],
  },
  {
    id: "w7-005",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What was the Holocaust and what were its causes?",
    back: "The Holocaust was Nazi Germany's systematic genocide of 6 million Jews and millions of others (Roma, disabled people, Soviets, political opponents, LGBTQ+ people). Causes: centuries of European antisemitism, Nazi racial ideology, the totalitarian Nazi state's bureaucratic efficiency, wartime dehumanization, ordinary people's compliance, and widespread bystander indifference.",
    tags: ["holocaust", "genocide", "nazi", "WWII", "antisemitism"],
  },
  {
    id: "w7-006",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What role did colonial troops play in World War I and II?",
    back: "European empires mobilized millions of colonial subjects: 1+ million Indians, 600,000+ Africans, troops from Southeast Asia, the Caribbean, and Australians/Canadians. This wartime service raised expectations for self-governance — promises made (e.g., Balfour Declaration, Wilsonian self-determination) were denied after both wars, accelerating anti-colonial nationalism.",
    tags: ["colonial troops", "WWI", "WWII", "nationalism", "decolonization"],
  },
  {
    id: "w7-007",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What was the significance of the atomic bombings of Hiroshima and Nagasaki?",
    back: "The US dropped atomic bombs on Hiroshima (Aug 6, 1945) and Nagasaki (Aug 9, 1945), killing 100,000–200,000 people instantly and more from radiation. Japan surrendered, ending WWII. The bombings ushered in the nuclear age, began the arms race, created deterrence doctrine, and remain controversial regarding necessity and morality.",
    tags: ["atomic bomb", "hiroshima", "WWII", "nuclear", "japan"],
  },
  {
    id: "w7-008",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What was the Armenian Genocide (1915–1923)?",
    back: "The Ottoman government systematically killed approximately 1–1.5 million Armenians during WWI, using forced deportations into the Syrian desert, massacres, and starvation. The Ottoman government claimed Armenians were a security threat (collaborating with Russia). It is considered the first genocide of the 20th century and remains a source of diplomatic tension.",
    tags: ["armenian genocide", "ottoman", "WWI", "genocide"],
  },
  {
    id: "w7-009",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What was fascism and how did it rise in Europe in the 1920s–1930s?",
    back: "Fascism is an ultra-nationalist, authoritarian ideology rejecting democracy, communism, and individual rights in favor of state power, militarism, and racial/national supremacy. It rose due to: WWI trauma and humiliation (Versailles), economic devastation of Great Depression, fear of communism among business elites, and weakness of democratic institutions. Hitler (Germany) and Mussolini (Italy) were its leading exemplars.",
    tags: ["fascism", "hitler", "mussolini", "WWII", "nationalism"],
  },
  {
    id: "w7-010",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What was the significance of the Great Depression for global politics?",
    back: "The Great Depression (1929–1939) caused massive unemployment worldwide (25% in the US), destabilized democratic governments, created conditions for fascist and authoritarian regimes, and led to economic nationalism (protective tariffs worsening the Depression). It discredited laissez-faire capitalism and contributed to WWII by fueling extremism in Germany and Japan.",
    tags: ["great depression", "economics", "fascism", "WWII", "politics"],
  },
  {
    id: "w7-011",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What was the Mandate System after WWI and what were its effects?",
    back: "The League of Nations created the Mandate System, giving Britain and France control over former Ottoman and German territories (Palestine, Syria, Iraq, Namibia) as 'mandates' rather than colonies, supposedly to prepare them for self-rule. In practice it was a disguised form of colonialism that drew arbitrary borders (especially in the Middle East) creating lasting conflicts.",
    tags: ["mandate system", "league of nations", "WWI", "middle east", "colonialism"],
  },
  {
    id: "w7-012",
    unit: "unit-7",
    unitName: "Global Conflict",
    front: "What was the significance of the Battle of Britain (1940)?",
    back: "After France fell (June 1940), Nazi Germany launched an air campaign against Britain (the Blitz) hoping to force surrender or enable invasion. The Royal Air Force, aided by radar and codebreaking (Enigma), repelled the Luftwaffe. Britain's survival kept an Allied western front open, eventually enabling D-Day and Germany's defeat on two fronts.",
    tags: ["britain", "WWII", "air war", "nazi", "radar"],
  },

  // ─────────────────────────────────────────────
  // UNIT 8 — Cold War & Decolonization (1900–present)
  // ─────────────────────────────────────────────
  {
    id: "w8-001",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was the Cold War and what were its key characteristics?",
    back: "The Cold War (1947–1991) was geopolitical rivalry between the US (capitalism/democracy) and Soviet Union (communism), never escalating into direct military conflict (MAD — mutually assured destruction). Key features: nuclear arms race, proxy wars (Korea, Vietnam, Angola, Afghanistan), space race, ideological competition, Berlin Wall (1961–1989), and division of Europe via NATO vs. Warsaw Pact.",
    tags: ["cold war", "US", "soviet union", "nuclear", "proxy war"],
  },
  {
    id: "w8-002",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was the significance of Indian independence and partition in 1947?",
    back: "India gained independence from Britain in 1947 under Nehru (Congress) after Gandhi's nonviolent movement. Simultaneously it was partitioned into Hindu-majority India and Muslim-majority Pakistan (demanded by Jinnah's Muslim League). Partition caused 1–2 million deaths and 15 million refugees in communal violence. It became the model for decolonization, showing both possibility and violent potential.",
    tags: ["india", "independence", "partition", "gandhi", "decolonization"],
  },
  {
    id: "w8-003",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was the Non-Aligned Movement?",
    back: "The Non-Aligned Movement (1961) was formed at the Bandung Conference by newly independent nations (India/Nehru, Egypt/Nasser, Yugoslavia/Tito, Ghana/Nkrumah, Indonesia/Sukarno) refusing to align with either superpower. It represented developing nations' desire for autonomy, challenged both US and Soviet imperialism, and called for economic equity between Global North and South.",
    tags: ["non-aligned", "cold war", "decolonization", "third world"],
  },
  {
    id: "w8-004",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was the significance of the Chinese Communist Revolution (1949)?",
    back: "Mao Zedong's Communist Party defeated Chiang Kai-shek's Nationalists (who fled to Taiwan), establishing the People's Republic of China. This brought the world's most populous nation into the communist bloc. The US response ('who lost China?') intensified Cold War fears, contributed to McCarthyism, and drove deeper US involvement in Korea and Vietnam.",
    tags: ["china", "communism", "mao", "revolution", "cold war"],
  },
  {
    id: "w8-005",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What were the causes and effects of the Korean War (1950–1953)?",
    back: "North Korea (communist, Soviet-backed) invaded South Korea (US-backed) in June 1950. The US led a UN coalition; China intervened when UN forces approached the Yalu River. Armistice in 1953 restored the pre-war border (38th parallel). Effects: ~3 million deaths, Korea remains divided today, US learned not to invade China — lessons applied (and then forgotten) in Vietnam.",
    tags: ["korean war", "cold war", "US", "china", "communism"],
  },
  {
    id: "w8-006",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was apartheid in South Africa?",
    back: "Apartheid (1948–1994) was institutionalized racial segregation and white minority rule in South Africa. Black South Africans were denied political rights, forced to live in Bantustans, subjected to pass laws, and denied access to quality education. It ended through: ANC resistance, Nelson Mandela's imprisoned moral authority, international sanctions, internal uprisings (Soweto, 1976), and negotiated transition.",
    tags: ["apartheid", "south africa", "mandela", "racism", "colonialism"],
  },
  {
    id: "w8-007",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was the significance of the Vietnam War for the Cold War?",
    back: "The US intervened in Vietnam (1965–1973) to prevent communist North Vietnam from reunifying the country, applying the Domino Theory. Despite massive military superiority, the US was defeated by guerrilla warfare, supply lines (Ho Chi Minh Trail), and declining domestic support. Vietnam demonstrated the limits of US power and military force in achieving political objectives.",
    tags: ["vietnam", "cold war", "US", "communism", "guerrilla"],
  },
  {
    id: "w8-008",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was the Cuban Missile Crisis (1962) and why was it significant?",
    back: "The Cuban Missile Crisis brought the US and Soviet Union closest to nuclear war. The Soviet Union placed nuclear missiles in Cuba; the US blockaded Cuba and demanded their removal. After 13 days of tense negotiation, the Soviets removed missiles in exchange for US promise not to invade Cuba and secret removal of US missiles from Turkey. Led to the Moscow-Washington hotline.",
    tags: ["cuban missile crisis", "cold war", "nuclear", "kennedy", "khrushchev"],
  },
  {
    id: "w8-009",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was the Truman Doctrine and containment?",
    back: "The Truman Doctrine (1947) pledged US support for countries resisting communist expansion. George Kennan's containment strategy proposed preventing Soviet expansion without direct confrontation. It led to the Marshall Plan (rebuilding Western Europe), NATO (1949), and US involvement in Korea, Vietnam, and dozens of covert operations to prevent communist governments.",
    tags: ["truman doctrine", "containment", "cold war", "marshall plan", "NATO"],
  },
  {
    id: "w8-010",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was the significance of decolonization in Africa (1950s–1970s)?",
    back: "Most of Africa gained independence from European colonizers between 1957 (Ghana, first sub-Saharan nation) and the 1970s. Decolonization was driven by: nationalist movements (Nkrumah, Kenyatta, Nyerere), weakening of European powers post-WWII, Cold War dynamics (US and Soviet support for independence movements), and UN pressure. However, neo-colonialism (economic control without political control) often continued.",
    tags: ["decolonization", "africa", "independence", "nationalism", "cold war"],
  },
  {
    id: "w8-011",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What was the significance of the Iranian Revolution (1979)?",
    back: "The Iranian Revolution overthrew Shah Pahlavi (a US-backed secular autocrat) and established an Islamic Republic under Ayatollah Khomeini. It represented a rejection of Western secularism and US imperialism, inspired Islamic movements globally, created the Iran-Iraq War (1980–88), took US hostages (52 for 444 days), and reoriented Middle Eastern politics.",
    tags: ["iran", "revolution", "1979", "khomeini", "cold war"],
  },
  {
    id: "w8-012",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    front: "What were the Bandung principles and why were they significant?",
    back: "The Bandung Conference (1955, Indonesia) brought together 29 newly independent Asian and African nations. They adopted principles of peaceful coexistence, anti-colonialism, racial equality, and non-interference. It was the founding moment of the Global South as a political force and directly led to the Non-Aligned Movement (1961).",
    tags: ["bandung", "decolonization", "non-aligned", "africa", "asia"],
  },

  // ─────────────────────────────────────────────
  // UNIT 9 — Globalization (1900–present)
  // ─────────────────────────────────────────────
  {
    id: "w9-001",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What is globalization and what has driven it since 1945?",
    back: "Globalization is the increasing interconnection of economies, cultures, and politics worldwide. Drivers since 1945: containerization (reduced shipping costs by 90%), internet (instant global communication), multinational corporations, free trade agreements (GATT, WTO, NAFTA), Bretton Woods institutions (IMF, World Bank), and end of Cold War opening previously closed economies.",
    tags: ["globalization", "trade", "internet", "multinational", "economics"],
  },
  {
    id: "w9-002",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What was the significance of the fall of the Soviet Union (1991)?",
    back: "The Soviet Union's collapse ended the Cold War and bipolar world order, leaving the US as the sole superpower ('unipolar moment'). It led to: independence for 15 Soviet republics (including Ukraine, Kazakhstan, Baltic states), democratization attempts across Eastern Europe, NATO expansion, economic 'shock therapy' in Russia causing depression, and a wave of ethnic conflicts (Yugoslavia, Chechnya).",
    tags: ["soviet union", "cold war", "1991", "russia", "democracy"],
  },
  {
    id: "w9-003",
    unit: "unit-9",
    unitName: "Globalization",
    front: "How has globalization affected developing nations?",
    back: "Globalization has had mixed effects: economic growth in some regions (East Asian Tigers — South Korea, Taiwan, Singapore, Hong Kong); increased access to technology and markets; but also: exploitation of cheap labor in global supply chains, environmental degradation (offshoring pollution), cultural homogenization, dependency on multinationals, and vulnerability to global financial crises (1997 Asian crisis, 2008 global recession).",
    tags: ["globalization", "developing nations", "inequality", "trade"],
  },
  {
    id: "w9-004",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What is the significance of China's economic rise since the 1980s?",
    back: "Deng Xiaoping's market reforms (1978+) — 'special economic zones,' foreign investment, privatization — transformed China into the world's second-largest economy. China became the 'world's factory' through export-led growth, lifted 800 million from poverty (greatest poverty reduction in history), and is now challenging US geopolitical dominance through the Belt and Road Initiative.",
    tags: ["china", "economic growth", "globalization", "deng xiaoping"],
  },
  {
    id: "w9-005",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What are the causes and effects of climate change as a global issue?",
    back: "Causes: burning fossil fuels since industrialization, deforestation, industrial agriculture releasing CO₂ and methane. Effects: rising sea levels (threatening Bangladesh, Pacific islands), extreme weather events, agricultural disruption, species extinction, and climate refugees. Represents a collective action problem — nations must cooperate, but economic incentives favor defection (Paris Agreement, 2015).",
    tags: ["climate change", "globalization", "environment", "industrialization"],
  },
  {
    id: "w9-006",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What is the significance of religious fundamentalism in the post-Cold War era?",
    back: "After the Cold War, religious identity often replaced ideological identity as a source of conflict (Samuel Huntington's 'Clash of Civilizations'). Islamic fundamentalism (Al-Qaeda, ISIS), Hindu nationalism (BJP in India), and Christian nationalism all emerged as political forces. The 9/11 attacks (2001) and subsequent 'War on Terror' (Afghanistan, Iraq) reshaped global politics.",
    tags: ["fundamentalism", "religion", "terrorism", "post-cold war"],
  },
  {
    id: "w9-007",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What was the significance of the Green Revolution?",
    back: "The Green Revolution (1940s–1970s) used high-yield crop varieties, chemical fertilizers, pesticides, and irrigation to dramatically increase food production in developing countries. It prevented famines in India and elsewhere, but also increased inequality (large farms benefited more), caused environmental damage, and created dependency on chemical inputs and Western seed corporations.",
    tags: ["green revolution", "agriculture", "development", "food"],
  },
  {
    id: "w9-008",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What is the significance of the World Trade Organization (WTO)?",
    back: "The WTO (1995, replacing GATT) sets international trade rules, adjudicates trade disputes, and pushes for trade liberalization (reducing tariffs and barriers). It has enabled massive growth in global trade but critics argue it favors wealthy nations, undermines environmental/labor protections, and limits developing nations' ability to protect infant industries.",
    tags: ["WTO", "trade", "globalization", "economics"],
  },
  {
    id: "w9-009",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What was the significance of the AIDS epidemic as a global health crisis?",
    back: "HIV/AIDS emerged in the 1980s, initially in Sub-Saharan Africa and among gay men in the US. It became a global epidemic killing 40+ million people. Sub-Saharan Africa was hardest hit (70% of cases), devastating demographics and economies. The epidemic illustrated global health interdependence, the cost of pharmaceutical patents on access in poor countries, and the impact of stigma on public health response.",
    tags: ["AIDS", "health", "africa", "globalization", "epidemic"],
  },
  {
    id: "w9-010",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What is neo-colonialism and how does it operate today?",
    back: "Neo-colonialism is economic and political control of developing nations without formal colonial rule, through: multinational corporations extracting resources and profits; IMF/World Bank structural adjustment programs imposing economic policies; military bases and interventions; cultural dominance (media, language). Critics argue the Global South remains economically subordinate to wealthy nations despite political independence.",
    tags: ["neo-colonialism", "globalization", "development", "economics", "africa"],
  },
  {
    id: "w9-011",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What was the significance of the internet and digital revolution for globalization?",
    back: "The internet (1990s+) transformed global communication, commerce, and culture: enabled instant global communication, e-commerce (Amazon, Alibaba), remote work, social movements (Arab Spring, Black Lives Matter), and surveillance capitalism. It also created new inequalities (digital divide), enabled misinformation, and gave rise to platform monopolies crossing national borders.",
    tags: ["internet", "digital revolution", "globalization", "communication"],
  },
  {
    id: "w9-012",
    unit: "unit-9",
    unitName: "Globalization",
    front: "What is the significance of migration as a feature of globalization?",
    back: "Globalization has accelerated international migration: economic migration (workers moving to wealthy countries for jobs), refugee flows (from conflicts in Syria, Afghanistan, South Sudan), and brain drain (skilled workers leaving developing nations). Migration creates remittance flows (developing nations received $700B+ in 2020), cultural exchange, and political backlash (anti-immigration nationalism).",
    tags: ["migration", "globalization", "refugees", "economics"],
  },
];
