export type MCQQuestion = {
  id: string;
  unit: string;
  unitName: string;
  question: string;
  stimulus?: string;
  stimulusType?: "primary_source" | "secondary_source" | "data" | "map" | "image";
  stimulusAttribution?: string;
  choices: { A: string; B: string; C: string; D: string };
  correct: "A" | "B" | "C" | "D";
  explanation: string;
  skill: string;
  difficulty: "easy" | "medium" | "hard";
};

export const AP_WORLD_MCQ: MCQQuestion[] = [
  // ─────────────────────────────────────────────
  // UNIT 1 — The Global Tapestry (1200–1450)
  // ─────────────────────────────────────────────
  {
    id: "mcq-w1-001",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    stimulus: "The merchants of China are like the merchants of the whole world, for they alone engage in trade throughout the whole of it. Their wealth is immeasurable… They sail by sea to the eastern and western parts of the world.",
    stimulusType: "primary_source",
    stimulusAttribution: "Ibn Battuta, Rihla (Travels), 14th century",
    question: "The passage best supports which of the following conclusions about the 13th–14th century global economy?",
    choices: {
      A: "Chinese merchants dominated long-distance trade networks across Eurasia and the Indian Ocean",
      B: "The Silk Road had declined significantly by the 14th century due to Mongol disruption",
      C: "European merchants had established dominance over Indian Ocean trade",
      D: "Trade was primarily conducted overland rather than by sea routes during this period",
    },
    correct: "A",
    explanation: "Ibn Battuta's account highlights the centrality of Chinese merchants in global trade networks during the 14th century. The passage describes sea travel and broad geographic reach, directly supporting Answer A. The other options contradict the passage or historical evidence.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-002",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "Which of the following best explains why Islam spread so rapidly along Indian Ocean trade routes between 1200 and 1450?",
    choices: {
      A: "Muslim rulers used military conquest to force conversion in coastal trading cities",
      B: "Sufi missionaries and Muslim merchants spread the faith through peaceful contact and commerce",
      C: "The collapse of Buddhism created a religious vacuum filled by Islam",
      D: "The Mongol Empire mandated Islam as the official religion of the Silk Roads",
    },
    correct: "B",
    explanation: "Islam spread primarily through peaceful means along trade routes — Muslim merchants established diaspora communities and Sufi missionaries adapted to local cultures. Military conquest was not the primary driver along the Indian Ocean network.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-003",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "The use of the civil service examination in Song Dynasty China primarily served to:",
    choices: {
      A: "Ensure military commanders were selected based on merit",
      B: "Create a bureaucracy based on Confucian education rather than hereditary aristocracy",
      C: "Promote Buddhism as the state ideology",
      D: "Allow merchants to gain political influence commensurate with their economic power",
    },
    correct: "B",
    explanation: "The civil service examination system selected government officials based on knowledge of Confucian texts, creating a meritocratic bureaucracy. This reduced the power of the hereditary aristocracy and promoted educated administrators loyal to the emperor.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w1-004",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    stimulus: "Mali is the greatest of the [African] empires… The king of this country is mighty, and most of the land of the blacks obeys him. He rules a large territory, with numerous armies and abundant wealth. Mansa Musa's gifts in Cairo were so extravagant that they depressed the price of gold in Egypt for twelve years.",
    stimulusType: "primary_source",
    stimulusAttribution: "Al-Umari, Egyptian scholar and administrator, c. 1340",
    question: "The account above most directly illustrates which of the following about the Mali Empire?",
    choices: {
      A: "Mali's military power was the primary source of its political influence in Africa",
      B: "The Mali Empire's wealth derived primarily from agriculture and crop production",
      C: "Mali's control of trans-Saharan gold trade was central to its power and regional influence",
      D: "Islamic rulers in Mali were less powerful than those in North Africa",
    },
    correct: "C",
    explanation: "The passage emphasizes Mali's gold wealth and its effects across North Africa (depressing gold prices in Egypt), directly pointing to control of gold trade as Mali's primary power base. The trans-Saharan gold trade was the engine of Mali's economic and political power.",
    skill: "Argumentation",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-005",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "Which of the following best explains why the Mongols are considered a major cause of both the disruption and expansion of Eurasian trade in the 13th century?",
    choices: {
      A: "The Mongols destroyed trade networks through conquest but later established the Pax Mongolica that secured routes",
      B: "The Mongols created entirely new trade routes that had not existed before their conquests",
      C: "The Mongols converted to Islam and used religious networks to expand trade",
      D: "The Mongols introduced paper money throughout Eurasia, stimulating commerce",
    },
    correct: "A",
    explanation: "The Mongols initially devastated regions through conquest (sacking Baghdad, 1258), disrupting existing trade. However, once their empire was consolidated, the Pax Mongolica created safe conditions for long-distance trade from China to Europe, allowing figures like Marco Polo to travel safely.",
    skill: "Continuity and Change Over Time",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-006",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    stimulus: "The Swahili coast, showing major city-states: Mogadishu, Malindi, Mombasa, Kilwa, Sofala. Arrows indicate trade flows: gold and ivory from interior Africa → coast; Indian textiles and Chinese porcelain → coast from the east; and Arab dhows navigating via monsoon winds.",
    stimulusType: "map",
    stimulusAttribution: "Trade network of the Swahili Coast, c. 1300",
    question: "Based on the map description, which of the following conclusions about Swahili city-states is most directly supported?",
    choices: {
      A: "Swahili cities produced most of the goods they traded rather than serving as intermediaries",
      B: "Swahili cities served as commercial intermediaries connecting interior Africa to Indian Ocean trade networks",
      C: "The Swahili coast was primarily integrated into Mediterranean rather than Indian Ocean trade",
      D: "Swahili city-states relied on overland caravan routes rather than maritime commerce",
    },
    correct: "B",
    explanation: "The map shows Swahili cities as nodes linking interior African products (gold, ivory) with maritime Indian Ocean trade (Indian textiles, Chinese porcelain). This confirms their role as intermediaries — they did not produce these goods but facilitated their exchange.",
    skill: "Argumentation",
    difficulty: "easy",
  },
  {
    id: "mcq-w1-007",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "The foot binding practice in Song Dynasty China most directly reflected which of the following?",
    choices: {
      A: "The spread of Buddhist ideas about female spiritual purity",
      B: "Neo-Confucian values reinforcing patriarchal control over elite women",
      C: "Practical requirements of agricultural labor in Song China",
      D: "A practice adopted from contact with Central Asian nomadic cultures",
    },
    correct: "B",
    explanation: "Foot binding was linked to Neo-Confucian social norms that emphasized female chastity, obedience, and confinement to domestic roles. It restricted women's mobility and signaled elite status (laboring women couldn't afford it), reflecting patriarchal social hierarchies reinforced by Neo-Confucianism.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-008",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "Which of the following most accurately describes the role of the Aztec tributary system in consolidating imperial power?",
    choices: {
      A: "It directly governed all conquered territories through Aztec-appointed administrators",
      B: "It allowed conquered peoples to maintain local governance in exchange for tribute payments to Tenochtitlan",
      C: "It eliminated local political structures and replaced them with a standardized Aztec legal code",
      D: "It was based primarily on military service obligations rather than economic tribute",
    },
    correct: "B",
    explanation: "The Aztec Empire ruled indirectly — conquered peoples maintained their own rulers and governance in exchange for paying tribute (goods, labor, sacrificial captives) to Tenochtitlan. This minimized administrative costs but bred resentment that Spanish conquistadors would later exploit.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-009",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "The invention of the printing press in China most directly contributed to which of the following during the Song Dynasty?",
    choices: {
      A: "The spread of democratic ideas challenging imperial authority",
      B: "Increased commercialization by facilitating the use of paper money and government documents",
      C: "The decline of Confucianism as Buddhism's texts were more widely printed",
      D: "Greater political decentralization as local rulers could print their own laws",
    },
    correct: "B",
    explanation: "Printing technology in Song China most directly facilitated commerce by enabling mass production of paper money, government financial documents, and administrative records. This supported Song China's sophisticated commercial economy rather than spreading political or religious challenges.",
    skill: "Causation",
    difficulty: "hard",
  },
  {
    id: "mcq-w1-010",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "Which of the following best explains why the Inca Empire could administer a vast territory without a written language?",
    choices: {
      A: "The Inca relied on an oral tradition maintained by a specialized class of memorizers",
      B: "The Inca used quipus (knotted strings), a road network, and mit'a labor obligations to maintain administrative control",
      C: "The Inca limited their empire to areas with homogeneous populations requiring little administration",
      D: "The Inca adopted the writing systems of conquered Andean civilizations",
    },
    correct: "B",
    explanation: "The Inca compensated for the absence of writing through multiple systems: quipus encoded numerical and administrative data; 40,000+ km of roads enabled rapid communication; chasquis (relay runners) delivered messages; and mit'a labor obligations built infrastructure and supplied the state. Together these enabled sophisticated administration.",
    skill: "Argumentation",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-011",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "How did the introduction of Champa rice most significantly transform Song Dynasty China?",
    choices: {
      A: "It allowed China to export rice as a primary trade commodity on the Silk Roads",
      B: "It increased agricultural productivity, supporting population growth and urbanization",
      C: "It shifted China's economy from manufacturing to agriculture",
      D: "It strengthened the power of the peasantry relative to the landed aristocracy",
    },
    correct: "B",
    explanation: "Champa rice's drought-resistance and fast-ripening properties allowed multiple harvests per year on poor soils. This dramatically increased food production, supporting population growth (from ~50 million to ~100 million) that fueled urbanization and commercialization — creating the large cities and markets that made Song China the world's most sophisticated economy.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-012",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    stimulus: "The Great Zimbabwe complex consists of massive dry-stone walls, some reaching 11 meters high and 5 meters thick, built without mortar. No European-style construction techniques were used. The complex served as the capital of a kingdom that controlled gold trade routes to the Swahili Coast.",
    stimulusType: "secondary_source",
    stimulusAttribution: "Archaeological survey of Great Zimbabwe, modern scholarship",
    question: "The evidence described above most directly challenges which of the following historical claims?",
    choices: {
      A: "That sub-Saharan African societies developed complex political and economic systems independently",
      B: "Early European claims that Great Zimbabwe must have been built by non-African peoples",
      C: "That the Swahili Coast had no connections to the African interior",
      D: "That gold was not an important trade commodity before 1450",
    },
    correct: "B",
    explanation: "Early European colonizers claimed Great Zimbabwe was built by outsiders (Phoenicians, Arabs) because they could not believe sub-Saharan Africans had built such sophisticated structures. The archaeological evidence of the construction method — sophisticated but distinctly African, without European techniques — directly refutes these colonial claims.",
    skill: "Argumentation",
    difficulty: "hard",
  },
  {
    id: "mcq-w1-013",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "Which of the following best describes the significance of the Byzantine Empire in the period 1200–1450?",
    choices: {
      A: "Byzantium conquered most of the Levant and restored the eastern Roman Empire to its classical peak",
      B: "Despite weakening from the Fourth Crusade, Byzantium remained a key node connecting European and Asian trade until 1453",
      C: "Byzantium converted to Islam and became part of the Islamic trade network",
      D: "Byzantium was the primary origin of plague transmission into Western Europe",
    },
    correct: "B",
    explanation: "Although the Fourth Crusade (1204) severely weakened Byzantium, it remained a crucial trade node controlling Constantinople's straits connecting the Mediterranean to the Black Sea and Central Asian trade routes. Its final fall to the Ottomans (1453) shifted this strategic control to Ottoman hands, driving European exploration for alternative routes.",
    skill: "Continuity and Change Over Time",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-014",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "The Delhi Sultanate's primary significance for Indian history was that it:",
    choices: {
      A: "Unified all of South Asia under a single centralized administration for the first time",
      B: "Introduced Islam to South Asia and established a precedent for Muslim rule that influenced the later Mughal Empire",
      C: "Destroyed the Hindu caste system and created social equality across India",
      D: "Repelled all Mongol invasions and maintained Indian cultural isolation",
    },
    correct: "B",
    explanation: "The Delhi Sultanate established Islam as a major religion in South Asia, introduced Persian administrative and artistic traditions, and created the political precedent for Muslim rule that the Mughal Empire would later build on. While it repelled some Mongol invasions, it didn't maintain isolation — it actively integrated Persian culture.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w1-015",
    unit: "unit-1",
    unitName: "The Global Tapestry",
    question: "Which of the following continuities best characterized all major civilizations in the period 1200–1450?",
    choices: {
      A: "Democratic governance structures with elected representation",
      B: "Patriarchal social structures limiting women's public roles",
      C: "Monotheistic religious beliefs as the basis of political authority",
      D: "Economies based primarily on industrial manufacturing",
    },
    correct: "B",
    explanation: "Patriarchal social structures — limiting women's public roles, property rights, and political participation — were common across virtually all major civilizations in this period (China, the Islamic world, India, Europe, the Americas). This represents a meaningful continuity across diverse cultures, while the other options were not universal features.",
    skill: "Continuity and Change Over Time",
    difficulty: "medium",
  },

  // ─────────────────────────────────────────────
  // UNIT 2 — Networks of Exchange (1200–1450)
  // ─────────────────────────────────────────────
  {
    id: "mcq-w2-001",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    stimulus: "In the year 1347, the plague came from the east. It spread from city to city, from country to country… People died in great numbers, so many that it was impossible to bury them properly. The priests themselves died, so that even the last rites were denied to the dying.",
    stimulusType: "primary_source",
    stimulusAttribution: "Florentine chronicler, c. 1348",
    question: "The account above most directly illustrates which of the following about the Black Death?",
    choices: {
      A: "The plague originated in Europe and spread eastward along trade routes",
      B: "Religious institutions collapsed completely as a result of the plague",
      C: "Trade networks facilitated disease transmission across long distances, with devastating social effects",
      D: "European governments effectively contained the spread of the plague through quarantine measures",
    },
    correct: "C",
    explanation: "The passage shows the plague arriving from the east (via trade routes) and causing massive social disruption (inability to bury the dead, death of priests, collapse of normal social functioning). This illustrates the role of trade networks in disease transmission and the devastating social consequences of pandemic disease.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w2-002",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    question: "Ibn Battuta's extensive travels across the Islamic world in the 14th century most directly demonstrate which of the following?",
    choices: {
      A: "The Islamic world was politically unified under a single caliphate",
      B: "Islam provided a shared cultural and commercial framework enabling long-distance travel and interaction",
      C: "Only Muslim scholars could travel safely across Eurasia during this period",
      D: "Trade routes had declined significantly after the Mongol invasions",
    },
    correct: "B",
    explanation: "Ibn Battuta's ability to travel from Morocco to Mali, East Africa, India, and China over 75,000+ miles was enabled by Islam's shared language (Arabic), legal traditions, commercial norms, and hospitality networks for fellow Muslims. This demonstrates Islam's role as a unifying cultural framework for long-distance travel and trade.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w2-003",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    stimulus: "The voyages of Zheng He, 1405–1433: Seven voyages from China to Southeast Asia, India, Arabia, and the East African coast. Ships included 'treasure ships' up to 400 feet long — far larger than any European vessel of the era. The fleet carried thousands of sailors and soldiers and returned with tribute, exotic animals, and diplomatic relationships.",
    stimulusType: "secondary_source",
    stimulusAttribution: "Historical summary of the Ming treasure fleet voyages",
    question: "The Ming Dynasty's decision to ban maritime trade (haijin) after Zheng He's voyages most directly illustrates which of the following?",
    choices: {
      A: "China's maritime technology was inferior to European technology by the mid-15th century",
      B: "Internal political shifts — specifically Confucian opposition to trade — could reverse expansionary foreign policies",
      C: "The voyages proved commercially unprofitable, making their discontinuation economically rational",
      D: "European competition forced China to withdraw from Indian Ocean trade",
    },
    correct: "B",
    explanation: "The haijin policy reflected internal political dynamics: Confucian scholars viewed maritime trade as undignified and Zheng He's patron (the Yongle Emperor) had died. The scholar-gentry class reasserted traditional Confucian suspicion of merchants, showing how domestic political ideology can override demonstrably powerful capabilities.",
    skill: "Causation",
    difficulty: "hard",
  },
  {
    id: "mcq-w2-004",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    question: "Which of the following best explains why Sufism was more effective than orthodox Islamic law in spreading Islam to Southeast Asia and Sub-Saharan Africa?",
    choices: {
      A: "Sufi missionaries used military force more effectively than orthodox Muslim armies",
      B: "Sufism's mystical practices and accommodation of local customs made conversion culturally accessible",
      C: "Orthodox Islamic legal scholars refused to travel to distant regions",
      D: "Sufi missionaries offered material incentives that orthodox missionaries could not provide",
    },
    correct: "B",
    explanation: "Sufism spread Islam through mystical poetry, music, and practices that could be adapted to local spiritual traditions. Unlike orthodox Islamic law (sharia) which demanded significant behavioral changes, Sufism often allowed gradual Islamization while accommodating existing customs, making conversion more attractive to local populations.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w2-005",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    question: "The spread of the Black Death along Silk Road trade routes in the 14th century is best understood as evidence of which of the following?",
    choices: {
      A: "The deliberate use of biological warfare by the Mongol Empire",
      B: "The unintended consequences of increased commercial connectivity across Eurasia",
      C: "The failure of Islamic medical practices compared to Chinese medicine",
      D: "The exclusive responsibility of nomadic peoples for spreading disease",
    },
    correct: "B",
    explanation: "The Black Death's rapid spread along trade routes illustrates that increased connectivity has unintended consequences — the same networks that carried silk, spices, and ideas also carried disease. The Mongol-facilitated Pax Mongolica that boosted trade also accelerated plague transmission from its origins in Central Asia westward.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w2-006",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    question: "Diasporic merchant communities in the period 1200–1450 primarily served to:",
    choices: {
      A: "Replace local economies with standardized global trade practices",
      B: "Create trust networks and commercial infrastructure enabling long-distance trade",
      C: "Spread democratic political ideas to trading partners across Eurasia",
      D: "Undermine local governments by accumulating greater wealth than ruling classes",
    },
    correct: "B",
    explanation: "Merchant diasporas (Chinese in Southeast Asia, Indian in East Africa, Jewish across Eurasia, Arab across the Indian Ocean) reduced transaction costs by creating trust networks based on shared cultural norms, religious bonds, and community enforcement. They were commercial infrastructure, not political reformers.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w2-007",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    stimulus: "From China we receive: silk textiles, porcelain, and musk. From India we receive: pepper, ginger, cinnamon, and other spices, cotton cloth, and gems. From Arabia we receive: incense and horses. We send in return: gold and ivory from the interior of Africa.",
    stimulusType: "primary_source",
    stimulusAttribution: "Account of trade at a Swahili port city, c. 1300",
    question: "The trading patterns described in the passage most directly demonstrate which of the following about Indian Ocean trade?",
    choices: {
      A: "African merchants dominated Indian Ocean trade networks",
      B: "The Indian Ocean trade was a multilateral exchange system connecting diverse regional economies",
      C: "Chinese silk was the most important commodity in all Indian Ocean trade",
      D: "Arab merchants controlled all trade between Africa and Asia",
    },
    correct: "B",
    explanation: "The passage shows goods flowing from China, India, and Arabia into a Swahili port, with African gold and ivory flowing out. This multilateral exchange — with different regions supplying different commodities based on their comparative advantages — characterizes the Indian Ocean system as an interconnected, multi-directional network rather than one dominated by any single actor.",
    skill: "Argumentation",
    difficulty: "easy",
  },
  {
    id: "mcq-w2-008",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    question: "Which of the following best explains why the Hanseatic League developed in Northern Europe in the 13th century?",
    choices: {
      A: "Northern European rulers established the League to collect taxes from merchants",
      B: "Merchants formed the League to protect their shared commercial interests and establish standardized trade practices",
      C: "The Catholic Church organized the League to fund crusades to the Holy Land",
      D: "Mongol invasions from the east forced northern merchants to cooperate for military defense",
    },
    correct: "B",
    explanation: "The Hanseatic League was a merchant-initiated coalition formed to protect shared commercial interests: secure trading privileges, standardize weights and measures, provide protection against pirates, and give members collective bargaining power against rulers. It demonstrates how merchants could organize powerful institutions without state authority.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w2-009",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    question: "Which of the following most accurately describes how 'Indianization' affected Southeast Asian kingdoms between 200 CE and 1450?",
    choices: {
      A: "Southeast Asian kingdoms were conquered and directly administered by Indian rulers",
      B: "Southeast Asian rulers selectively adopted Indian religious concepts, writing, and political ideas while maintaining local traditions",
      C: "Indianization eliminated all pre-existing cultural practices in Southeast Asia",
      D: "Indian merchants forced Southeast Asian rulers to convert to Hinduism or Buddhism as a trade requirement",
    },
    correct: "B",
    explanation: "Indianization was a selective process — Southeast Asian rulers adopted Indian concepts of divine kingship, Sanskrit writing, Hinduism and Buddhism because these enhanced their own legitimacy and administrative capacity, not because they were conquered. Local languages, traditions, and practices continued alongside adopted Indian elements.",
    skill: "Causation",
    difficulty: "hard",
  },
  {
    id: "mcq-w2-010",
    unit: "unit-2",
    unitName: "Networks of Exchange",
    question: "The fact that the Mongols promoted trade by reducing tariffs and protecting merchants most directly illustrates which of the following historical concepts?",
    choices: {
      A: "Continuity — nomadic peoples had always supported long-distance trade",
      B: "Cross-cultural interaction — the Mongols adopted Chinese commercial practices",
      C: "That political power and commercial interest could align to expand trade networks",
      D: "That military conquest inevitably leads to long-term economic prosperity",
    },
    correct: "C",
    explanation: "The Mongols had strong incentives to promote trade — they taxed it and used it to access luxury goods. Their protection of merchants and reduction of tariffs illustrates that political actors can shape commercial networks when their interests align with merchants' interests, making the Pax Mongolica a deliberate policy rather than a coincidence.",
    skill: "Argumentation",
    difficulty: "hard",
  },

  // ─────────────────────────────────────────────
  // UNIT 3 — Land-Based Empires (1450–1750)
  // ─────────────────────────────────────────────
  {
    id: "mcq-w3-001",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    stimulus: "We, the Janissaries, are the weapon of the Sultan. We are taken as boys from the Christian villages of the Balkans, raised in the faith of Islam, and trained in the arts of war… We owe our loyalty to the Sultan alone, not to any family or noble house. We are the heart of the Ottoman army.",
    stimulusType: "primary_source",
    stimulusAttribution: "Account attributed to an Ottoman Janissary, 16th century",
    question: "The devshirme system described in the passage primarily served which purpose for Ottoman sultans?",
    choices: {
      A: "Generating tax revenue from Christian populations in the Balkans",
      B: "Creating a loyal military and administrative class outside the traditional Ottoman noble hierarchy",
      C: "Forcing mass conversion of Christians to Islam to strengthen religious unity",
      D: "Replacing agricultural labor lost to plague with trained military recruits",
    },
    correct: "B",
    explanation: "The key feature of the devshirme system was that Janissaries owed loyalty exclusively to the Sultan, not to noble families. This gave the Sultan a powerful counterweight to Ottoman nobles who might challenge imperial authority — the boys had no family connections, lands, or competing loyalties within the empire.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w3-002",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    question: "The Ottoman, Safavid, and Mughal Empires are grouped as 'Gunpowder Empires' primarily because they:",
    choices: {
      A: "All originated as gunpowder-producing states that exported weapons technology",
      B: "Used firearms and cannon to conquer and consolidate large territories, transforming military power",
      C: "All allied with each other to use gunpowder against European colonial powers",
      D: "Were the first states in history to develop gunpowder weapons",
    },
    correct: "B",
    explanation: "The 'Gunpowder Empires' label reflects how these states leveraged firearms and artillery as the basis of their military power and territorial expansion. Gunpowder weapons (especially cannon) allowed them to defeat cavalry-based nomadic rivals and besiege fortified cities, fundamentally changing how empires were built. China invented gunpowder — they did not.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w3-003",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    question: "The Safavid Empire's establishment of Twelver Shia Islam as the state religion of Persia is best understood as an example of:",
    choices: {
      A: "Religious tolerance enabling the empire to integrate diverse populations",
      B: "Using religious identity to distinguish the Safavid state from Sunni Ottoman rivals and build internal cohesion",
      C: "A compromise negotiated between Sunni and Shia leaders to end religious warfare",
      D: "The spread of Islam through peaceful missionary activity into previously non-Muslim territory",
    },
    correct: "B",
    explanation: "The Safavid imposition of Shia Islam served political purposes: it distinguished Persia from the Sunni Ottoman Empire (justifying ongoing conflict), created a distinctive Persian-Shia identity that built internal cohesion, and gave the Safavid rulers religious legitimacy through their claimed descent from Shia Imams.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w3-004",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    stimulus: "I have never persecuted anyone for their faith. I have allowed Hindus to practice their religion openly. I have appointed many Hindus to high positions. I have abolished the jizya tax that Muslims traditionally levy on non-believers. I seek to rule justly over all my subjects, regardless of their faith.",
    stimulusType: "primary_source",
    stimulusAttribution: "Attributed to Emperor Akbar, Mughal court chronicle, c. 1590",
    question: "Akbar's policies described in the passage most directly served to:",
    choices: {
      A: "Convert the Hindu majority to Islam through gentle persuasion rather than force",
      B: "Undermine the authority of Islamic scholars within the Mughal court",
      C: "Build political legitimacy and stability in an empire where Hindus were the majority",
      D: "Respond to European criticism of Muslim treatment of religious minorities",
    },
    correct: "C",
    explanation: "Akbar's religious tolerance (sulh-i-kul) was fundamentally a political strategy — a Muslim emperor ruling a majority-Hindu population needed Hindu cooperation. By removing the jizya, appointing Hindu administrators, and respecting Hindu practices, he built broad legitimacy across the empire's diverse population, strengthening Mughal power.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w3-005",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    question: "Which of the following best explains how the Qing Dynasty maintained control over China after the Manchu conquest of 1644?",
    choices: {
      A: "The Manchu completely replaced Chinese culture and government with Manchu institutions",
      B: "The Manchu converted to Buddhism, the majority religion of Han Chinese",
      C: "The Manchu preserved Chinese administrative traditions and Confucian governance while maintaining Manchu cultural markers",
      D: "The Manchu eliminated the Chinese scholar-gentry class and replaced it with Manchu nobles",
    },
    correct: "C",
    explanation: "The Qing's successful strategy involved a dual approach: preserve Chinese Confucian administrative structures (civil service exam, Chinese bureaucrats) to govern the Han majority, while maintaining Manchu cultural distinctiveness (the queue hairstyle, Manchu language in official documents) to assert Manchu identity and prevent assimilation.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w3-006",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    question: "Peter the Great's westernization reforms in Russia most directly reflect which of the following historical patterns?",
    choices: {
      A: "Smaller states adopting the technologies and practices of more powerful neighbors to remain competitive",
      B: "Democratic revolutions spreading from Western Europe to Eastern Europe",
      C: "The universal appeal of Enlightenment ideas transcending national boundaries",
      D: "The decline of absolute monarchy across Europe in the early 18th century",
    },
    correct: "A",
    explanation: "Peter the Great's reforms exemplify a recurring historical pattern: a state that perceives itself as falling behind adopts the technologies, military practices, and administrative methods of more powerful neighbors. Just as Meiji Japan would later do, Russia selectively adopted Western practices to compete as a great power without abandoning autocratic rule.",
    skill: "Comparison",
    difficulty: "hard",
  },
  {
    id: "mcq-w3-007",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    question: "The millet system used by the Ottoman Empire is best described as an example of:",
    choices: {
      A: "Forced assimilation of religious minorities into Islamic culture",
      B: "A pragmatic approach to governing a religiously diverse empire by granting communal autonomy",
      C: "Democratic representation of minority communities in Ottoman government",
      D: "Ottoman weakness that allowed minorities to resist central authority",
    },
    correct: "B",
    explanation: "The millet system granted religious minorities (Christians, Jews) the right to govern themselves in personal matters (marriage, inheritance, education) according to their own religious laws. This pragmatic system reduced the administrative burden of governing diversity, minimized resistance from minorities, and allowed the Ottomans to extract taxes without forcing cultural conversion.",
    skill: "Argumentation",
    difficulty: "medium",
  },
  {
    id: "mcq-w3-008",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    question: "The fall of Constantinople to the Ottomans in 1453 most directly contributed to which of the following developments?",
    choices: {
      A: "The Crusades, as European powers sought to recapture the city",
      B: "European efforts to find alternative sea routes to Asia, stimulating the Age of Exploration",
      C: "The decline of the Silk Road as merchants abandoned overland routes entirely",
      D: "The spread of the plague from Asia into Western Europe",
    },
    correct: "B",
    explanation: "Ottoman control of Constantinople and key trade routes increased the cost of reaching Asian spice markets for European traders. This drove European powers (especially Portugal and Spain) to search for alternative sea routes — directly motivating Vasco da Gama's voyage around Africa and Columbus's westward voyage.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w3-009",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    question: "Which of the following represents the most significant similarity between the Ottoman Empire and the Mughal Empire?",
    choices: {
      A: "Both empires were founded by Turkish peoples with roots in Central Asian nomadic cultures",
      B: "Both empires successfully prevented any territorial losses throughout their history",
      C: "Both empires used religious legitimacy and pragmatic governance of diverse populations to consolidate power",
      D: "Both empires abandoned Islam in favor of syncretic religious systems by the 17th century",
    },
    correct: "C",
    explanation: "Both the Ottoman and Mughal empires faced the challenge of ruling religiously diverse populations as Muslim minorities or ruling classes. Both developed pragmatic governance strategies (millet system for Ottomans; sulh-i-kul for Mughals under Akbar) that used religious legitimacy while accommodating diversity to maintain stability.",
    skill: "Comparison",
    difficulty: "medium",
  },
  {
    id: "mcq-w3-010",
    unit: "unit-3",
    unitName: "Land-Based Empires",
    question: "The tax farming system, used by the Ottoman and Mughal empires, is best understood as:",
    choices: {
      A: "A progressive reform that shifted the tax burden from peasants to wealthy merchants",
      B: "A practical solution to administrative capacity limitations that also created incentives for exploitation",
      C: "A system modeled directly on Chinese administrative practices",
      D: "Evidence that early modern empires lacked genuine central authority",
    },
    correct: "B",
    explanation: "Tax farming solved the problem of governing large territories without large bureaucracies — the state could simply sell tax collection rights to private individuals. However, this created incentives for tax farmers to extract maximum revenue from peasants, often exceeding official rates, causing resentment and rural unrest that contributed to imperial decline.",
    skill: "Causation",
    difficulty: "hard",
  },

  // ─────────────────────────────────────────────
  // UNIT 4 — Transoceanic Interconnections (1450–1750)
  // ─────────────────────────────────────────────
  {
    id: "mcq-w4-001",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    stimulus: "Between 1492 and 1600, the indigenous population of central Mexico declined from approximately 25 million to 1 million — a reduction of 96%. The primary cause was epidemic diseases including smallpox, measles, and typhus, to which indigenous populations had no prior immunity.",
    stimulusType: "data",
    stimulusAttribution: "Historical demographic estimates, modern scholarship (Cook and Borah, 1963; subsequent revisions)",
    question: "The demographic data above most directly illustrates which of the following effects of the Columbian Exchange?",
    choices: {
      A: "European military conquest was the leading cause of indigenous population decline",
      B: "The introduction of new diseases caused catastrophic population collapse among previously isolated populations",
      C: "The Columbian Exchange had equally devastating effects on European and indigenous populations",
      D: "Indigenous populations declined primarily due to forced labor in the encomienda system",
    },
    correct: "B",
    explanation: "The data shows 96% population decline from 1492–1600, and explicitly states disease was the primary cause. Populations with no prior exposure to Old World diseases had no immunity. Military conquest and forced labor contributed to mortality but could not account for such rapid and total collapse — that scale required epidemic disease.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w4-002",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    question: "The encomienda system in Spanish colonial America most directly represented:",
    choices: {
      A: "A form of voluntary labor migration by indigenous peoples seeking economic opportunity",
      B: "A system of forced indigenous labor justified by the obligation to Christianize",
      C: "A wage labor system modeled on European feudal practices",
      D: "An indigenous-designed system of tribute payment to Spanish authorities",
    },
    correct: "B",
    explanation: "The encomienda granted Spanish colonizers the right to extract labor and tribute from indigenous peoples, theoretically in exchange for converting them to Christianity. In practice it was coercive exploitation — the Christianization rationale masked forced labor, contributing to indigenous mortality and prompting criticism from reformers like Bartolomé de las Casas.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w4-003",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    stimulus: "Estimated volume of the trans-Atlantic slave trade by century: 1500s — 366,000; 1600s — 1.3 million; 1700s — 6.1 million; 1800s (until 1867) — 3.9 million. Peak decades occurred in the late 18th century, driven by Caribbean sugar production.",
    stimulusType: "data",
    stimulusAttribution: "Trans-Atlantic Slave Trade Database, Emory University",
    question: "The data above most directly supports which of the following conclusions about the trans-Atlantic slave trade?",
    choices: {
      A: "The slave trade declined in the 18th century as European nations moved toward abolition",
      B: "The slave trade was primarily driven by tobacco production in North America",
      C: "The slave trade expanded dramatically in the 18th century, driven by demand for plantation labor",
      D: "The trade was relatively small scale and localized throughout most of its history",
    },
    correct: "C",
    explanation: "The data clearly shows exponential growth — from 366,000 in the 1500s to 6.1 million in the 1700s. The passage identifies Caribbean sugar as the peak driver. Sugar's insatiable demand for labor in brutal plantation conditions drove the dramatic 18th-century expansion of the slave trade.",
    skill: "Argumentation",
    difficulty: "medium",
  },
  {
    id: "mcq-w4-004",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    question: "The Manila Galleon trade (1565–1815) is significant primarily because it:",
    choices: {
      A: "Connected the Americas to Europe for the first time",
      B: "Was the first sustained trade link connecting the Americas directly to Asia",
      C: "Allowed Japan to export goods to the Americas via the Pacific",
      D: "Replaced the Silk Road as the primary route for Chinese goods reaching Europe",
    },
    correct: "B",
    explanation: "The Manila Galleon trade created the first regular, direct commercial link between the Americas and Asia across the Pacific. American silver flowed to China in exchange for Chinese goods, integrating the Americas into the global silver economy and completing the first truly global trade network linking all inhabited continents.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w4-005",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    stimulus: "The Company [Dutch East India Company] shall have the right to appoint governors, build fortresses, raise troops, wage war and conclude peace treaties with princes in Asia, Africa, and America, and administer justice. The Company acts in the name of the States-General of the Netherlands.",
    stimulusType: "primary_source",
    stimulusAttribution: "Charter of the Dutch East India Company (VOC), 1602",
    question: "The powers granted to the Dutch East India Company in the passage most directly illustrate which of the following?",
    choices: {
      A: "The Dutch government directly administered all colonial territories through the Company",
      B: "Joint-stock companies could be granted quasi-governmental powers, blurring the line between commerce and empire",
      C: "The Company was primarily a military organization with secondary commercial interests",
      D: "European companies were required to obtain permission from Asian rulers before trading",
    },
    correct: "B",
    explanation: "The charter explicitly grants the VOC governmental powers (raise troops, wage war, appoint governors, administer justice) alongside commercial functions. This shows the blurring of commercial and imperial functions — the VOC was simultaneously a profit-seeking corporation and a de facto government in the territories it controlled.",
    skill: "Argumentation",
    difficulty: "medium",
  },
  {
    id: "mcq-w4-006",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    question: "Which of the following best explains why African rulers participated in the trans-Atlantic slave trade?",
    choices: {
      A: "African rulers were forced by European military superiority to supply enslaved people",
      B: "African rulers received European goods (firearms, textiles) in exchange and gained military advantages over rivals",
      C: "The concept of slavery was introduced to Africa by European merchants",
      D: "African rulers were unaware that enslaved people would not be returned after a period of service",
    },
    correct: "B",
    explanation: "African rulers were rational actors who participated because it was economically and militarily advantageous — European goods (especially firearms) provided military advantages over rivals. This doesn't minimize the moral catastrophe of the slave trade, but explains African elite participation as self-interested within a system created by European demand.",
    skill: "Causation",
    difficulty: "hard",
  },
  {
    id: "mcq-w4-007",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    question: "The casta system in colonial Latin America is best understood as serving which primary function?",
    choices: {
      A: "Ensuring equality of opportunity for all racial groups within the Spanish colonial system",
      B: "Legally encoding racial hierarchy to maintain Spanish colonial control and distribute privileges",
      C: "Providing a scientific classification of racial characteristics for medical purposes",
      D: "Creating a representative system in which different racial groups had political advocates",
    },
    correct: "B",
    explanation: "The casta system was fundamentally a system of social control — it determined legal rights, occupational access, taxation, and social status based on racial ancestry. It concentrated power in the hands of peninsulares and criollos while legally subordinating mixed-race and indigenous peoples, maintaining colonial hierarchies.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w4-008",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    question: "The flow of American silver to China in the 16th–18th centuries most directly had which of the following effects on the Chinese economy?",
    choices: {
      A: "It caused rapid inflation in China similar to Europe's Price Revolution",
      B: "It enabled China to convert to a silver-based tax system and fueled Chinese commercial expansion",
      C: "It led China to abandon its tribute system in favor of direct trade",
      D: "It caused China to become economically dependent on Spanish colonial mining",
    },
    correct: "B",
    explanation: "The Ming Dynasty had converted to a silver-based tax system (Single Whip Reform, 1581), creating enormous demand for silver. American silver supplied this demand, enabling tax collection, fueling China's commercial economy, and integrating China deeply into the global silver trade network. China was the engine pulling silver from the Americas through trade.",
    skill: "Causation",
    difficulty: "hard",
  },
  {
    id: "mcq-w4-009",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    question: "Religious syncretism in colonial Latin America, as seen in practices like the Virgin of Guadalupe, most directly demonstrates which of the following?",
    choices: {
      A: "The complete success of Spanish missionary efforts to eliminate indigenous religious practices",
      B: "How colonized peoples adapted imposed religious systems by blending them with indigenous traditions",
      C: "That Catholic missionaries in Latin America were more tolerant than those in Asia",
      D: "The failure of colonial authorities to enforce religious conformity",
    },
    correct: "B",
    explanation: "Syncretism shows cultural agency — indigenous and African peoples were not passive recipients of Catholicism but active interpreters who blended it with their own traditions. The Virgin of Guadalupe (blending Catholic Mary with the Aztec goddess Tonantzin) represents this creative adaptation, giving colonial-era religion distinctly local meaning.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w4-010",
    unit: "unit-4",
    unitName: "Transoceanic Interconnections",
    question: "Which of the following best describes the primary difference between Spanish and Portuguese colonial approaches in the 16th century?",
    choices: {
      A: "Spain focused on territorial conquest and settlement while Portugal established trading post networks",
      B: "Portugal focused on converting indigenous peoples while Spain focused only on resource extraction",
      C: "Spain operated through joint-stock companies while Portugal used direct royal administration",
      D: "Portugal established large plantation agriculture while Spain did not use enslaved labor",
    },
    correct: "A",
    explanation: "Spain conquered and settled large territories in the Americas (New Spain, Peru) through the encomienda and later hacienda systems. Portugal, with a smaller population, built a network of fortified trading posts around Africa and Asia (feitorias), controlling key ports and straits rather than governing interior territories.",
    skill: "Comparison",
    difficulty: "medium",
  },

  // ─────────────────────────────────────────────
  // UNIT 5 — Revolutions (1750–1900)
  // ─────────────────────────────────────────────
  {
    id: "mcq-w5-001",
    unit: "unit-5",
    unitName: "Revolutions",
    stimulus: "The state of nature has a law of nature to govern it, which obliges every one: and reason, which is that law, teaches all mankind who will but consult it, that being all equal and independent, no one ought to harm another in his life, health, liberty, or possessions.",
    stimulusType: "primary_source",
    stimulusAttribution: "John Locke, Second Treatise of Government, 1689",
    question: "The ideas expressed in the passage most directly influenced which of the following?",
    choices: {
      A: "The development of Social Darwinism in the 19th century",
      B: "The American Declaration of Independence and the French Declaration of the Rights of Man",
      C: "The communist ideology developed by Marx and Engels in the 19th century",
      D: "The conservative reaction against the French Revolution led by Edmund Burke",
    },
    correct: "B",
    explanation: "Locke's natural rights philosophy — that all people are equal by nature and have rights to life, liberty, and property — directly shaped the language of the American Declaration of Independence (Jefferson's 'life, liberty, and the pursuit of happiness') and the French Declaration of the Rights of Man (1789).",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w5-002",
    unit: "unit-5",
    unitName: "Revolutions",
    question: "The Haitian Revolution (1791–1804) is considered the most radical of the Atlantic Revolutions primarily because it:",
    choices: {
      A: "Established the first democratic constitution in the Western Hemisphere",
      B: "Was the only successful large-scale slave revolution, directly challenging racial hierarchy and slavery",
      C: "Eliminated all social inequality and established economic equality among all citizens",
      D: "Inspired an immediate end to slavery throughout the Americas",
    },
    correct: "B",
    explanation: "The Haitian Revolution was radical precisely because it struck at slavery and racial hierarchy — institutions the American and French Revolutions had largely preserved despite their equality rhetoric. It was led by enslaved people who created the first Black republic, directly implementing the Enlightenment promise that 'all men are equal' in a way that terrified slaveholders across the Americas.",
    skill: "Argumentation",
    difficulty: "medium",
  },
  {
    id: "mcq-w5-003",
    unit: "unit-5",
    unitName: "Revolutions",
    stimulus: "The working classes of England and France do not enjoy the benefits of the factories they build. They labor 14 hours daily, breathe coal dust and cotton fibers, and live in conditions little better than those of serfs. Yet the same factories that impoverish workers enrich their owners beyond the dreams of the aristocracy.",
    stimulusType: "secondary_source",
    stimulusAttribution: "Adapted from reformist writings, England, c. 1840",
    question: "The conditions described in the passage most directly led to which of the following?",
    choices: {
      A: "The immediate overthrow of industrial capitalism by socialist revolutions in Britain and France",
      B: "The growth of labor movements, trade unions, and socialist political theory",
      C: "Government regulations that quickly eliminated industrial working conditions",
      D: "The migration of the working class from urban factories to rural agricultural areas",
    },
    correct: "B",
    explanation: "The harsh conditions of early industrialization created the social conditions for working-class organization: trade unions emerged (despite being initially illegal), socialist and communist theory developed (Marx's Communist Manifesto, 1848), and political movements (Chartism in Britain) demanded worker rights. Immediate revolution did not occur in Britain or France.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w5-004",
    unit: "unit-5",
    unitName: "Revolutions",
    question: "Why did Latin American independence movements (1810–1825) largely fail to change the social hierarchy even after achieving political independence?",
    choices: {
      A: "Spain retained economic control through trade agreements that maintained the old social structure",
      B: "The movements were led by creole elites who wanted political independence but not social revolution",
      C: "The Catholic Church prevented social change by supporting the existing hierarchy",
      D: "Indigenous populations resisted independence movements, preserving the Spanish-imposed system",
    },
    correct: "B",
    explanation: "Latin American independence movements were led by criollos (American-born Spanish) who resented Spanish-born peninsulares controlling political offices, but had no interest in dismantling racial and economic hierarchies from which they benefited. They replaced peninsulares at the top without changing the fundamental casta structure beneath them.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w5-005",
    unit: "unit-5",
    unitName: "Revolutions",
    question: "Britain industrialized before any other nation primarily because of which combination of factors?",
    choices: {
      A: "British democratic government provided more freedom for inventors than absolute monarchies elsewhere",
      B: "Britain had abundant coal and iron, capital from trade, colonial markets, and a mobile workforce created by enclosure",
      C: "Britain's geographic isolation prevented foreign powers from stealing its innovations",
      D: "Britain's superior educational system produced more inventors than other European nations",
    },
    correct: "B",
    explanation: "Britain's industrialization resulted from a convergence of factors: coal and iron as essential raw materials; capital accumulated through empire and trade; colonial markets and raw material sources; the enclosure movement that drove peasants off common lands into cities seeking wage work; and political stability protecting property rights. No single factor explains it — the combination does.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w5-006",
    unit: "unit-5",
    unitName: "Revolutions",
    question: "Which of the following best explains why nationalism both drove and limited 19th-century revolutions?",
    choices: {
      A: "Nationalism united people for independence but often excluded minority groups within new nation-states",
      B: "Nationalism spread democratic governance while simultaneously promoting religious uniformity",
      C: "Nationalism promoted economic equality while opposing political equality",
      D: "Nationalism strengthened multinational empires while weakening independent nations",
    },
    correct: "A",
    explanation: "Nationalism was simultaneously liberating and exclusionary. It drove independence movements and unifications (Italy, Germany, Latin America) by mobilizing people around shared identity. But nationalist movements typically defined the 'nation' in ways that excluded ethnic minorities, creating new minorities within new states (e.g., German Jews, Hungarians in Austria-Hungary).",
    skill: "Argumentation",
    difficulty: "hard",
  },
  {
    id: "mcq-w5-007",
    unit: "unit-5",
    unitName: "Revolutions",
    question: "The abolition of the slave trade by Britain in 1807 and of slavery itself in 1833 was primarily driven by:",
    choices: {
      A: "Economic calculations showing slave labor was less profitable than free wage labor",
      B: "A combination of Enlightenment ideals, religious activism, and enslaved people's resistance",
      C: "Pressure from the United States threatening trade sanctions against Britain",
      D: "Declining importance of colonies as Britain shifted focus to industrial production",
    },
    correct: "B",
    explanation: "British abolition resulted from multiple converging forces: Enlightenment arguments that slavery was incompatible with natural rights; evangelical religious movements (Quakers, Methodists, Wilberforce's Clapham Sect) mobilizing public opinion; and crucially, enslaved people's own resistance (uprisings like the Baptist War of 1831 in Jamaica) demonstrating slavery's unsustainability.",
    skill: "Causation",
    difficulty: "medium",
  },

  // ─────────────────────────────────────────────
  // UNIT 6 — Consequences of Industrialization (1750–1900)
  // ─────────────────────────────────────────────
  {
    id: "mcq-w6-001",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    stimulus: "Take up the White Man's burden — Send forth the best ye breed — Go bind your sons to exile to serve your captives' need; To wait, in heavy harness, on fluttered folk and wild — Your new-caught, sullen peoples, half devil and half child.",
    stimulusType: "primary_source",
    stimulusAttribution: "Rudyard Kipling, 'The White Man's Burden,' 1899 (written about US colonization of the Philippines)",
    question: "The poem most directly reflects which ideology used to justify European and American imperialism?",
    choices: {
      A: "Social Darwinism and the 'civilizing mission' — the belief that Western peoples had a duty to rule 'inferior' races",
      B: "Economic liberalism — the belief that free trade would benefit colonized peoples",
      C: "Religious evangelism — the exclusive motivation of Christian missionary work",
      D: "Nationalism — the desire to spread democratic ideals to colonized peoples",
    },
    correct: "A",
    explanation: "Kipling's poem exemplifies the 'civilizing mission' ideology — that Western peoples had a racial duty ('White Man's Burden') to colonize and 'improve' non-Western peoples described as 'half devil and half child.' This justified imperialism as benevolent obligation rather than exploitation, drawing on Social Darwinist ideas of racial hierarchy.",
    skill: "Argumentation",
    difficulty: "easy",
  },
  {
    id: "mcq-w6-002",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    question: "Japan's Meiji Restoration is best understood as an example of which of the following historical patterns?",
    choices: {
      A: "Successful military resistance to Western imperialism through traditional means",
      B: "A state selectively adopting Western technology and institutions to resist Western domination",
      C: "A popular democratic revolution overthrowing a feudal monarchy",
      D: "Western powers granting self-governance to a colony as reward for cooperation",
    },
    correct: "B",
    explanation: "The Meiji Restoration exemplifies a recurring pattern: a state perceiving external threat selectively adopts the technologies and institutions of threatening powers to become competitive. Japan adopted Western military technology, industrial methods, and constitutional government not to become Western but to resist Western imperialism — ultimately successfully (defeating Russia, 1905).",
    skill: "Comparison",
    difficulty: "medium",
  },
  {
    id: "mcq-w6-003",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    stimulus: "European claims in Africa, 1880 vs. 1914: In 1880, approximately 10% of Africa was under European control (mostly coastal areas). By 1914, approximately 90% of Africa was under European colonial rule. Only Ethiopia and Liberia remained independent.",
    stimulusType: "data",
    stimulusAttribution: "Historical atlas of African colonization",
    question: "The rapid change in African colonial control shown in the data is best explained by which of the following?",
    choices: {
      A: "African states voluntarily sought European governance to benefit from industrial technologies",
      B: "A convergence of industrial technologies, nationalist competition among European powers, and ideological justifications",
      C: "Military conquests by a single dominant European power that then distributed territories to allies",
      D: "Population pressure in Europe forcing emigration to Africa on an unprecedented scale",
    },
    correct: "B",
    explanation: "The Scramble for Africa (1881–1914) resulted from converging factors: new technologies (steamships, quinine against malaria, Maxim guns) making conquest feasible; nationalist competition among European powers fearing rivals would gain advantages; and ideological justifications (Social Darwinism, civilizing mission) making conquest morally acceptable to European publics.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w6-004",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    question: "The Opium Wars most directly resulted in which of the following changes to China's relationship with Western powers?",
    choices: {
      A: "China joined the global economy voluntarily, benefiting from expanded trade",
      B: "China modernized its military and government in response to defeat, similar to Japan's Meiji Restoration",
      C: "Western powers imposed unequal treaties granting extraterritoriality, treaty ports, and trade concessions",
      D: "China's Qing Dynasty collapsed immediately following the wars",
    },
    correct: "C",
    explanation: "The Opium Wars resulted in the 'unequal treaties' (Treaty of Nanjing, 1842; Treaty of Tianjin, 1858): treaty ports where foreigners could live and trade; extraterritoriality (foreigners exempt from Chinese law); most-favored-nation status; and forced legalization of opium. These terms systematically undermined Chinese sovereignty and fueled nationalist humiliation.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w6-005",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    question: "How did British colonial rule in India best exemplify the economic dimension of imperialism?",
    choices: {
      A: "Britain invested heavily in Indian industrialization to create a trading partner",
      B: "Britain used India as a source of raw materials and a market for British manufactured goods, deindustrializing India",
      C: "Britain allowed India to develop its own industries to fund colonial administration",
      D: "Britain's primary economic interest was recruiting Indian soldiers for military service",
    },
    correct: "B",
    explanation: "British India exemplified economic imperialism: Britain extracted raw materials (cotton, indigo, jute) from India, processed them in British factories, then sold manufactured goods back to India. British textiles destroyed India's own textile industry (once the world's most sophisticated). India financed British industrialization rather than its own.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w6-006",
    unit: "unit-6",
    unitName: "Consequences of Industrialization",
    question: "The Battle of Adwa (1896) in which Ethiopia defeated Italy is significant primarily because it:",
    choices: {
      A: "Was the first time an African army used European-style military tactics",
      B: "Demonstrated that a non-European nation could defeat a European colonial power, inspiring anti-colonial movements",
      C: "Led to the immediate decolonization of East Africa by European powers",
      D: "Caused Italy to abandon its imperial ambitions entirely",
    },
    correct: "B",
    explanation: "Adwa was symbolically enormously important: it proved that a non-European, non-white nation could defeat a European military using modern weapons. Ethiopia became a powerful symbol of African resistance and dignity, directly inspiring pan-Africanist movements, later anti-colonial nationalists, and the founders of organizations like the African Union.",
    skill: "Causation",
    difficulty: "medium",
  },

  // ─────────────────────────────────────────────
  // UNIT 7 — Global Conflict (1900–present)
  // ─────────────────────────────────────────────
  {
    id: "mcq-w7-001",
    unit: "unit-7",
    unitName: "Global Conflict",
    stimulus: "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender.",
    stimulusType: "primary_source",
    stimulusAttribution: "Winston Churchill, speech to the House of Commons, June 4, 1940",
    question: "The speech was delivered in the context of which of the following events?",
    choices: {
      A: "The Battle of the Somme during World War I",
      B: "Nazi Germany's conquest of France and the beginning of the Battle of Britain",
      C: "The Allied invasion of Normandy (D-Day)",
      D: "The beginning of the Blitz bombing campaign against British cities",
    },
    correct: "B",
    explanation: "Churchill's speech was delivered days after the Dunkirk evacuation, following Nazi Germany's rapid conquest of France. Britain now stood largely alone against Nazi-controlled continental Europe. The speech's defiance was meant to signal that Britain would not negotiate peace with Hitler, even as the situation appeared dire.",
    skill: "Contextualization",
    difficulty: "medium",
  },
  {
    id: "mcq-w7-002",
    unit: "unit-7",
    unitName: "Global Conflict",
    question: "The Treaty of Versailles (1919) is considered a major cause of World War II primarily because it:",
    choices: {
      A: "Failed to hold Germany militarily accountable for the war",
      B: "Created harsh conditions (reparations, war guilt, territorial losses) that fueled German resentment and economic instability",
      C: "Allowed Germany to maintain a large army that it later used for aggression",
      D: "Divided Germany into zones of occupation, preventing recovery",
    },
    correct: "B",
    explanation: "Versailles imposed the war guilt clause, $33 billion in reparations, severe military restrictions, and major territorial losses. These created: economic devastation contributing to hyperinflation (1923) and Great Depression impact; national humiliation exploited by Nazi propaganda; and structural instability of the Weimar Republic making democratic governance difficult.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w7-003",
    unit: "unit-7",
    unitName: "Global Conflict",
    stimulus: "Causes of World War I: Militarism — major European powers had been building up armies and navies for decades; Alliance System — Europe was divided into two armed camps (Triple Alliance vs. Triple Entente); Imperialism — European powers competed intensely for colonies; Nationalism — ethnic minority groups sought independence from multi-ethnic empires.",
    stimulusType: "secondary_source",
    stimulusAttribution: "AP World History: Modern Course Description, College Board",
    question: "Which of the following best illustrates how nationalism contributed to the outbreak of WWI?",
    choices: {
      A: "Germany's naval buildup threatened British imperial supremacy",
      B: "Serbian nationalism and Austro-Hungarian fear of Pan-Slavism created the immediate trigger (Archduke Franz Ferdinand's assassination)",
      C: "French revanchism over Alsace-Lorraine drove France to provoke Germany",
      D: "Russian industrial expansion threatened German economic interests in Eastern Europe",
    },
    correct: "B",
    explanation: "The MAIN causes all contributed, but nationalism provides the most direct explanation for the war's trigger: the assassin Gavrilo Princip was a Serbian nationalist; Austria-Hungary's ultimatum to Serbia reflected fear that Serbian nationalism would inspire South Slavic minorities to break from the empire; and this specific ethnic-national conflict activated the alliance system.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w7-004",
    unit: "unit-7",
    unitName: "Global Conflict",
    question: "The Russian Revolution of 1917 is significant for world history primarily because it:",
    choices: {
      A: "Was the first successful revolution against an absolute monarchy in European history",
      B: "Created the world's first communist state and established communism as a global ideological alternative to capitalism",
      C: "Demonstrated that democracy could be established in a traditionally authoritarian society",
      D: "Caused Russia to join the Allied powers and turn the tide of World War I",
    },
    correct: "B",
    explanation: "The Russian Revolution's world-historical significance was establishing a communist state — demonstrating that Marxist revolution was not just theory. This created an ideological rival to capitalism that divided the world for 70+ years (Cold War), inspired communist movements globally, and produced the Soviet Union as a major geopolitical power.",
    skill: "Causation",
    difficulty: "easy",
  },
  {
    id: "mcq-w7-005",
    unit: "unit-7",
    unitName: "Global Conflict",
    question: "Which of the following best explains why colonial subjects who fought for European empires in WWI and WWII later supported independence movements?",
    choices: {
      A: "Colonial soldiers received military training they later used against colonial powers",
      B: "Colonial subjects expected self-determination promises implicit in the wars' stated ideals to be fulfilled after victory",
      C: "Colonial military service automatically granted citizenship in metropolitan countries",
      D: "European powers promised independence in exchange for military support during the wars",
    },
    correct: "B",
    explanation: "Colonial subjects fought partly because of explicit promises (e.g., British hints at Indian self-governance, Wilson's Fourteen Points calling for national self-determination). When post-war settlements denied independence and restored colonial rule, the gap between democratic war rhetoric and colonial reality fueled nationalism and independence movements.",
    skill: "Causation",
    difficulty: "medium",
  },

  // ─────────────────────────────────────────────
  // UNIT 8 — Cold War & Decolonization (1900–present)
  // ─────────────────────────────────────────────
  {
    id: "mcq-w8-001",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    stimulus: "We must be the great arsenal of democracy. For us this is an emergency as serious as war itself. We must apply ourselves to our task with the same resolution, the same sense of urgency, the same spirit of patriotism and sacrifice as we would show were we at war.",
    stimulusType: "primary_source",
    stimulusAttribution: "Franklin D. Roosevelt, 'Arsenal of Democracy' radio address, December 29, 1940",
    question: "The speech is most significant for the Cold War era primarily because it:",
    choices: {
      A: "Announced US entry into World War II",
      B: "Committed the US to an interventionist foreign policy that later became the basis for Cold War containment",
      C: "Introduced the Marshall Plan to rebuild Europe after the war",
      D: "Declared the United States a nuclear power",
    },
    correct: "B",
    explanation: "Roosevelt's 'Arsenal of Democracy' speech represented a shift from American isolationism to interventionism — the US would actively support democracies against authoritarian threats. This interventionist principle, established in WWII, became the ideological foundation for Cold War containment policy (Truman Doctrine) and US interventions across the globe.",
    skill: "Continuity and Change Over Time",
    difficulty: "hard",
  },
  {
    id: "mcq-w8-002",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    question: "The Non-Aligned Movement founded at Bandung (1955) most directly represented which of the following?",
    choices: {
      A: "A military alliance of newly independent nations to defend against superpower aggression",
      B: "Newly independent nations asserting their right to self-determination outside the Cold War binary",
      C: "A communist alternative to both US capitalism and Soviet communism",
      D: "An economic union of developing nations modeled on the European Common Market",
    },
    correct: "B",
    explanation: "The Non-Aligned Movement represented newly independent nations rejecting the superpower demand that they choose sides in the Cold War. Leaders like Nehru, Nasser, and Sukarno argued that Cold War alignment replicated the colonial dependency they had just escaped. The movement asserted a 'third way' — independence from both Washington and Moscow.",
    skill: "Argumentation",
    difficulty: "medium",
  },
  {
    id: "mcq-w8-003",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    question: "The US policy of containment, as articulated by George Kennan and implemented through the Truman Doctrine, was based on which assumption?",
    choices: {
      A: "That the Soviet Union could be defeated militarily before it developed nuclear weapons",
      B: "That Soviet communism would eventually collapse if prevented from expanding to new territories",
      C: "That economic aid to developing nations would prevent them from choosing communism",
      D: "That direct military confrontation with the Soviet Union was necessary to preserve democracy",
    },
    correct: "B",
    explanation: "Kennan's containment strategy held that the Soviet system contained inherent contradictions (economic inefficiency, repression) that would cause it to collapse — but only if prevented from expanding, which would provide external victories masking internal weaknesses. If contained, Soviet communism would eventually implode from within. This proved accurate when the Soviet Union collapsed in 1991.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w8-004",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    stimulus: "Today the peoples of Africa are awakening from a long sleep of colonialism. Africa is not a geographical expression but a political reality. We must build an Africa that is united, free, and capable of defending itself against the neo-colonialism that threatens to replace the old colonialism.",
    stimulusType: "primary_source",
    stimulusAttribution: "Kwame Nkrumah, speech at the founding of the Organization of African Unity, 1963",
    question: "Nkrumah's concept of 'neo-colonialism' most directly refers to which of the following?",
    choices: {
      A: "The threat of military reconquest of Africa by European colonial powers",
      B: "Economic and political control of formally independent African nations through economic dependency on wealthy nations",
      C: "The persistence of ethnic conflicts that European colonizers deliberately created",
      D: "The refusal of European nations to grant independence to remaining African colonies",
    },
    correct: "B",
    explanation: "Nkrumah coined 'neo-colonialism' to describe how formally independent nations could remain economically subordinate to wealthy nations through debt, trade dependency, multinational corporations, and political pressure — 'the last stage of imperialism.' He argued that political independence without economic independence was incomplete liberation.",
    skill: "Argumentation",
    difficulty: "medium",
  },
  {
    id: "mcq-w8-005",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    question: "Which of the following best explains why the Vietnamese communists were able to defeat both France (1954) and the United States (1975)?",
    choices: {
      A: "Superior military technology acquired from the Soviet Union and China",
      B: "Guerrilla tactics, nationalist support, and the political unsustainability of foreign occupation",
      C: "US and French military forces were poorly trained and equipped for any military conflict",
      D: "The Vietnamese communist government had established a superior economic system",
    },
    correct: "B",
    explanation: "The Viet Minh and later Viet Cong used guerrilla tactics that neutralized conventional military superiority (hiding among civilian populations, supply lines through jungles). Crucially, Ho Chi Minh successfully framed the conflicts as nationalist struggles against foreign occupation, winning popular support that made prolonged foreign occupation politically and militarily unsustainable.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w8-006",
    unit: "unit-8",
    unitName: "Cold War & Decolonization",
    question: "The partition of India in 1947 most directly resulted from which of the following?",
    choices: {
      A: "British deliberate policy to keep India divided and manageable after independence",
      B: "The failure of the Indian National Congress to accommodate Muslim political concerns, combined with British partition policies",
      C: "Pakistan's military superiority, which forced the partition terms",
      D: "A UN-supervised referendum in which Muslim-majority areas voted for separation",
    },
    correct: "B",
    explanation: "Partition resulted from a combination: the Muslim League under Jinnah argued Muslims would face permanent Hindu-majority discrimination in a unified India; Congress under Gandhi and Nehru rejected separate Muslim electorates; and departing British administrators (Mountbatten) accepted partition as the fastest exit despite its catastrophic human costs.",
    skill: "Causation",
    difficulty: "hard",
  },

  // ─────────────────────────────────────────────
  // UNIT 9 — Globalization (1900–present)
  // ─────────────────────────────────────────────
  {
    id: "mcq-w9-001",
    unit: "unit-9",
    unitName: "Globalization",
    stimulus: "Global trade as percentage of world GDP: 1950 — 5.5%; 1970 — 8%; 1990 — 15%; 2008 — 31%; 2020 — 25% (COVID impact). Major drivers identified: containerization reducing shipping costs by ~90%; telecommunications revolution; reduction of trade barriers via GATT/WTO.",
    stimulusType: "data",
    stimulusAttribution: "World Bank, World Development Indicators, various years",
    question: "The data above most directly illustrates which of the following about globalization?",
    choices: {
      A: "Economic globalization has proceeded consistently without interruption since 1950",
      B: "Global trade growth has been driven primarily by government subsidies to export industries",
      C: "Technological and political changes have dramatically increased economic integration, though subject to disruption",
      D: "Globalization has reduced economic differences between wealthy and poor nations",
    },
    correct: "C",
    explanation: "The data shows dramatic trade growth from 5.5% to 31% of GDP (technological and institutional drivers), but also a 2020 decline (COVID disruption). This illustrates globalization as a powerful but not inevitable process — it can be reversed by pandemics, wars, or political decisions — driven by both technology (containerization) and politics (GATT/WTO).",
    skill: "Argumentation",
    difficulty: "medium",
  },
  {
    id: "mcq-w9-002",
    unit: "unit-9",
    unitName: "Globalization",
    question: "China's rapid economic development since Deng Xiaoping's reforms (1978) is best understood as an example of:",
    choices: {
      A: "The universal superiority of free market capitalism over state-directed economies",
      B: "A state-directed export-led development model that selectively adopted market mechanisms",
      C: "The natural outcome of China joining the World Trade Organization",
      D: "Democratic political reforms enabling economic growth",
    },
    correct: "B",
    explanation: "China's model was not free-market capitalism — the Chinese Communist Party maintained control of key industries, directed investment, managed currency, and set development priorities. Rather, China selectively adopted market mechanisms (private enterprise, foreign investment) within a state-directed framework, proving that economic growth doesn't require Western-style liberal democracy.",
    skill: "Argumentation",
    difficulty: "hard",
  },
  {
    id: "mcq-w9-003",
    unit: "unit-9",
    unitName: "Globalization",
    question: "Which of the following best represents a continuity between 19th-century imperialism and late 20th-century globalization?",
    choices: {
      A: "Wealthy nations using military force to open markets in developing nations",
      B: "Economic relationships that concentrated wealth in wealthy nations at the expense of developing nations",
      C: "European nations maintaining direct political control over their former colonies",
      D: "Resource extraction conducted exclusively through multinational rather than state-owned companies",
    },
    correct: "B",
    explanation: "Critics of globalization (dependency theorists, Nkrumah's neo-colonialism) argue that even without political control, economic relationships continued to concentrate wealth in wealthy nations: multinational corporations extracted profits from low-wage production; IMF 'structural adjustment programs' imposed economic policies; and commodity dependence kept developing nations economically subordinate.",
    skill: "Continuity and Change Over Time",
    difficulty: "hard",
  },
  {
    id: "mcq-w9-004",
    unit: "unit-9",
    unitName: "Globalization",
    stimulus: "The fall of the Berlin Wall, November 9, 1989, was greeted with jubilation by millions across Eastern Europe. Within two years, the Soviet Union ceased to exist. Fifteen new nations emerged from its dissolution, and the Cold War's bipolar world order was replaced by what commentators called a 'unipolar moment' of American dominance.",
    stimulusType: "secondary_source",
    stimulusAttribution: "Contemporary historical summary",
    question: "Which of the following most directly resulted from the Soviet Union's collapse described above?",
    choices: {
      A: "The United States reduced its military presence globally as external threats diminished",
      B: "Former Soviet states immediately achieved stable democratic governance and economic prosperity",
      C: "The collapse created a power vacuum leading to ethnic conflicts, NATO expansion debates, and new geopolitical competition",
      D: "China replaced the Soviet Union as the primary rival to US global dominance within five years",
    },
    correct: "C",
    explanation: "Soviet collapse created instability: ethnic conflicts emerged in Yugoslavia (Balkans wars), Chechnya, and the Caucasus; debates over NATO expansion created tensions with Russia; and multiple successor states struggled with 'shock therapy' economic transitions causing depression. Rather than a peaceful 'end of history,' the collapse created new conflicts and geopolitical competitions.",
    skill: "Causation",
    difficulty: "medium",
  },
  {
    id: "mcq-w9-005",
    unit: "unit-9",
    unitName: "Globalization",
    question: "Climate change is best understood as a 'collective action problem' in which of the following senses?",
    choices: {
      A: "No single nation has the technical capacity to address climate change alone",
      B: "Individual nations have economic incentives to continue emitting greenhouse gases while hoping others will reduce emissions",
      C: "Climate change primarily affects developing nations that have the least political power to address it",
      D: "Environmental problems can only be solved through collective rather than individual action",
    },
    correct: "B",
    explanation: "Climate change is a classic collective action problem: each nation has an incentive to continue emitting (economic benefit) while hoping others bear the cost of reducing emissions (free rider problem). If all nations reason this way, the collective outcome (continued warming) is worse for everyone. International agreements like the Paris Accord attempt to coordinate action but face this fundamental challenge.",
    skill: "Argumentation",
    difficulty: "hard",
  },
  {
    id: "mcq-w9-006",
    unit: "unit-9",
    unitName: "Globalization",
    question: "Which of the following represents the most significant change brought about by the internet and digital revolution in the context of globalization?",
    choices: {
      A: "The elimination of economic inequality between developed and developing nations",
      B: "The replacement of face-to-face commerce with exclusively digital transactions",
      C: "The acceleration of information flow, enabling both greater connectivity and new forms of conflict (misinformation, cyber warfare)",
      D: "The restoration of cultural diversity as local cultures gained global platforms",
    },
    correct: "C",
    explanation: "The internet's most significant effect on globalization was accelerating information flow — enabling instant global communication, e-commerce, and coordination (including social movements like Arab Spring). But it also created new vulnerabilities: cyber warfare, misinformation campaigns, and digital surveillance. The same connectivity that empowers civil society also enables authoritarian control.",
    skill: "Argumentation",
    difficulty: "medium",
  },
];
