export const AP_WORLD = {
  id: "ap-world",
  name: "AP World History: Modern",
  examDate: "May 2025",
  totalUnits: 9,
  units: [
    { id: "unit-1", name: "The Global Tapestry", period: "1200–1450", weight: "8–10%", examWeight: 9 },
    { id: "unit-2", name: "Networks of Exchange", period: "1200–1450", weight: "8–10%", examWeight: 9 },
    { id: "unit-3", name: "Land-Based Empires", period: "1450–1750", weight: "12–15%", examWeight: 13.5 },
    { id: "unit-4", name: "Transoceanic Interconnections", period: "1450–1750", weight: "12–15%", examWeight: 13.5 },
    { id: "unit-5", name: "Revolutions", period: "1750–1900", weight: "12–15%", examWeight: 13.5 },
    { id: "unit-6", name: "Consequences of Industrialization", period: "1750–1900", weight: "12–15%", examWeight: 13.5 },
    { id: "unit-7", name: "Global Conflict", period: "1900–present", weight: "8–10%", examWeight: 9 },
    { id: "unit-8", name: "Cold War & Decolonization", period: "1900–present", weight: "8–10%", examWeight: 9 },
    { id: "unit-9", name: "Globalization", period: "1900–present", weight: "8–10%", examWeight: 9 },
  ],
  frqTypes: [
    {
      id: "saq",
      name: "Short Answer Question (SAQ)",
      description: "3 parts (a, b, c) — no thesis required. Targets specific historical reasoning skills.",
      timeMinutes: 40,
      count: 3,
      points: 3,
    },
    {
      id: "dbq",
      name: "Document-Based Question (DBQ)",
      description: "Thesis + evidence from 7 documents + outside evidence + HAPP analysis.",
      timeMinutes: 60,
      count: 1,
      points: 7,
      rubricCategories: ["Thesis/Claim", "Contextualization", "Evidence (Document)", "Evidence (Beyond Document)", "Analysis & Reasoning"],
    },
    {
      id: "leq",
      name: "Long Essay Question (LEQ)",
      description: "Thesis + evidence + historical reasoning (comparison, causation, or continuity/change over time).",
      timeMinutes: 40,
      count: 1,
      points: 6,
      rubricCategories: ["Thesis/Claim", "Contextualization", "Evidence", "Analysis & Reasoning"],
    },
  ],
  mcqCount: 55,
  mcqTime: 55,
};
